/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Pika Complete API
 * Complete API documentation including public, admin, and internal endpoints
 * OpenAPI spec version: 1.0.0
 */
import type { AddressResponseCoordinates } from './addressResponseCoordinates'
import type { AddressType } from './addressType'

/**
 * Single address details
 */
export interface AddressResponse {
  /** Universally Unique Identifier */
  id: string
  userId: string
  /**
   * @minLength 1
   * @maxLength 255
   */
  street: string
  /**
   * Apartment, suite, etc.
   * @maxLength 255
   */
  street2?: string
  /**
   * @minLength 1
   * @maxLength 100
   */
  city: string
  /**
   * State or province
   * @minLength 1
   * @maxLength 100
   */
  state: string
  /**
   * @minLength 1
   * @maxLength 20
   */
  postalCode: string
  /**
   * ISO 3166-1 alpha-2 country code
   * @minLength 2
   * @maxLength 2
   */
  country: string
  /** Optional geo coordinates */
  coordinates?: AddressResponseCoordinates
  type: AddressType
  /**
   * Custom label
   * @maxLength 100
   */
  label?: string
  isDefault?: boolean
  isPrimary?: boolean
  isVerified?: boolean
  verifiedAt?: string
  /**
   * Delivery instructions
   * @maxLength 500
   */
  instructions?: string
  /** @maxLength 50 */
  accessCode?: string
  /** When the record was created */
  createdAt: string
  /** When the record was last updated */
  updatedAt: string
}
