/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Pika Complete API
 * Complete API documentation including public, admin, and internal endpoints
 * OpenAPI spec version: 1.0.0
 */

export type AddressListResponseDataItemType =
  (typeof AddressListResponseDataItemType)[keyof typeof AddressListResponseDataItemType]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AddressListResponseDataItemType = {
  HOME: 'HOME',
  WORK: 'WORK',
  BILLING: 'BILLING',
  SHIPPING: 'SHIPPING',
  OTHER: 'OTHER',
} as const
