/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Pika Complete API
 * Complete API documentation including public, admin, and internal endpoints
 * OpenAPI spec version: 1.0.0
 */
import type { AdminCreatePayoutRequestAction } from './adminCreatePayoutRequestAction'

/**
 * Process pending payouts
 */
export interface AdminCreatePayoutRequest {
  /**
   * @minItems 1
   * @maxItems 100
   */
  payoutIds: string[]
  action: AdminCreatePayoutRequestAction
  /** @maxLength 500 */
  reason?: string
  /** ISO 8601 datetime with timezone */
  delayUntil?: string
}
