/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * The VoucherBook Complete API
 * Complete API documentation including public, admin, and internal endpoints
 * OpenAPI spec version: 1.0.0
 */

export type AdminCreatePayoutRequestAction =
  (typeof AdminCreatePayoutRequestAction)[keyof typeof AdminCreatePayoutRequestAction]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AdminCreatePayoutRequestAction = {
  approve: 'approve',
  reject: 'reject',
  delay: 'delay',
} as const
