/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Pika Complete API
 * Complete API documentation including public, admin, and internal endpoints
 * OpenAPI spec version: 1.0.0
 */
import type { AdminUpdateUserStatusRequestStatus } from './adminUpdateUserStatusRequestStatus'

export interface AdminUpdateUserStatusRequest {
  /** User account status */
  status: AdminUpdateUserStatusRequestStatus
  /** @maxLength 500 */
  reason?: string
  /**
   * Suspension duration in days
   */
  duration?: number
  notifyUser?: boolean
}
