/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Pika Complete API
 * Complete API documentation including public, admin, and internal endpoints
 * OpenAPI spec version: 1.0.0
 */

/**
 * Supported storage provider
 */
export type AdminFileQueryParamsProvider =
  (typeof AdminFileQueryParamsProvider)[keyof typeof AdminFileQueryParamsProvider]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AdminFileQueryParamsProvider = {
  awsS3: 'awsS3',
  local: 'local',
  minio: 'minio',
} as const
