/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Pika Complete API
 * Complete API documentation including public, admin, and internal endpoints
 * OpenAPI spec version: 1.0.0
 */
import type { AdminBusinessVoucherStatsResponsePeriod } from './adminBusinessVoucherStatsResponsePeriod'
import type { AdminBusinessVoucherStatsResponseTopPerformingVouchersItem } from './adminBusinessVoucherStatsResponseTopPerformingVouchersItem'

export interface AdminBusinessVoucherStatsResponse {
  /** Universally Unique Identifier */
  businessId: string
  period: AdminBusinessVoucherStatsResponsePeriod
  /** @minimum 0 */
  totalVouchers: number
  /** @minimum 0 */
  activeVouchers: number
  /** @minimum 0 */
  expiredVouchers: number
  /** @minimum 0 */
  totalRedemptions: number
  /** @minimum 0 */
  totalScans: number
  /**
   * @minimum 0
   * @maximum 1
   */
  averageRedemptionRate: number
  /** @maxItems 10 */
  topPerformingVouchers: AdminBusinessVoucherStatsResponseTopPerformingVouchersItem[]
}
