/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Pika Complete API
 * Complete API documentation including public, admin, and internal endpoints
 * OpenAPI spec version: 1.0.0
 */
import type { AdminVerifyUserResponseUser } from './adminVerifyUserResponseUser'

/**
 * User verification response
 */
export interface AdminVerifyUserResponse {
  success?: boolean
  message?: string
  /** Detailed user information for admin */
  user?: AdminVerifyUserResponseUser
}
