/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Pika Complete API
 * Complete API documentation including public, admin, and internal endpoints
 * OpenAPI spec version: 1.0.0
 */
import type { VoucherState } from './voucherState'
import type { VoucherDiscountType } from './voucherDiscountType'
import type { AdminVoucherDetailResponseLocation } from './adminVoucherDetailResponseLocation'
import type { AdminVoucherDetailResponseImageUrl } from './adminVoucherDetailResponseImageUrl'
import type { AdminVoucherDetailResponseMaxRedemptions } from './adminVoucherDetailResponseMaxRedemptions'
import type { AdminVoucherDetailResponseMetadata } from './adminVoucherDetailResponseMetadata'
import type { AdminVoucherDetailResponseDeletedAt } from './adminVoucherDetailResponseDeletedAt'
import type { AdminVoucherDetailResponseBusiness } from './adminVoucherDetailResponseBusiness'
import type { AdminVoucherDetailResponseCategory } from './adminVoucherDetailResponseCategory'
import type { AdminVoucherDetailResponseCodesItem } from './adminVoucherDetailResponseCodesItem'
import type { AdminVoucherDetailResponseRedemptionsItem } from './adminVoucherDetailResponseRedemptionsItem'
import type { AdminVoucherDetailResponseScansItem } from './adminVoucherDetailResponseScansItem'
import type { AdminVoucherDetailResponseCustomerVouchersItem } from './adminVoucherDetailResponseCustomerVouchersItem'
import type { AdminVoucherDetailResponseDaysUntilExpiry } from './adminVoucherDetailResponseDaysUntilExpiry'

/**
 * Detailed voucher information for admin with industry-standard include relations
 */
export interface AdminVoucherDetailResponse {
  /** Universally Unique Identifier */
  id: string
  /** Universally Unique Identifier */
  businessId: string
  /** Universally Unique Identifier */
  categoryId: string
  state: VoucherState
  /** Voucher title in requested language */
  title: string
  /** Voucher description in requested language */
  description: string
  /** Voucher terms and conditions in requested language */
  terms: string
  discountType: VoucherDiscountType
  /** Decimal number with 2 decimal places */
  discountValue: number
  currency?: string
  location: AdminVoucherDetailResponseLocation
  imageUrl: AdminVoucherDetailResponseImageUrl
  /** ISO 8601 datetime with timezone */
  validFrom: string
  /** ISO 8601 datetime with timezone */
  expiresAt: string
  maxRedemptions: AdminVoucherDetailResponseMaxRedemptions
  maxRedemptionsPerUser?: number
  currentRedemptions?: number
  scanCount?: number
  claimCount?: number
  metadata: AdminVoucherDetailResponseMetadata
  /** ISO 8601 datetime with timezone */
  deletedAt: AdminVoucherDetailResponseDeletedAt
  /** Complete business object when ?include=business */
  business?: AdminVoucherDetailResponseBusiness
  /** Complete category object when ?include=category */
  category?: AdminVoucherDetailResponseCategory
  /** Voucher codes when ?include=codes */
  codes?: AdminVoucherDetailResponseCodesItem[]
  /** Redemption history when ?include=redemptions */
  redemptions?: AdminVoucherDetailResponseRedemptionsItem[]
  /** Scan analytics when ?include=scans */
  scans?: AdminVoucherDetailResponseScansItem[]
  /** Customer wallet entries when ?include=customerVouchers */
  customerVouchers?: AdminVoucherDetailResponseCustomerVouchersItem[]
  isActive: boolean
  isExpired: boolean
  /**
   * @minimum 0
   * @maximum 1
   */
  redemptionRate: number
  daysUntilExpiry: AdminVoucherDetailResponseDaysUntilExpiry
  /** When the record was created */
  createdAt: string
  /** When the record was last updated */
  updatedAt: string
}
