/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * The VoucherBook Complete API
 * Complete API documentation including public, admin, and internal endpoints
 * OpenAPI spec version: 1.0.0
 */

/**
 * Revenue by payment method (all keys optional)
 */
export type AdminFinancialReportResponseSummaryRevenueByPaymentMethod = {
  /** @minimum 0 */
  card?: number
  /** @minimum 0 */
  bankTransfer?: number
  /** @minimum 0 */
  wallet?: number
  /** @minimum 0 */
  cash?: number
}
