/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * The VoucherBook Complete API
 * Complete API documentation including public, admin, and internal endpoints
 * OpenAPI spec version: 1.0.0
 */

/**
 * Terms and conditions translations by language code
 */
export type AdminUpdateVoucherRequestTermsAndConditions = {
  [key: string]: string
}
