/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Pika Complete API
 * Complete API documentation including public, admin, and internal endpoints
 * OpenAPI spec version: 1.0.0
 */
import type { AdminVoucherQueryParamsSortBy } from './adminVoucherQueryParamsSortBy'
import type { AdminVoucherQueryParamsSortOrder } from './adminVoucherQueryParamsSortOrder'
import type { VoucherState } from './voucherState'
import type { VoucherDiscountType } from './voucherDiscountType'
import type { AdminVoucherQueryParamsLat } from './adminVoucherQueryParamsLat'
import type { AdminVoucherQueryParamsLng } from './adminVoucherQueryParamsLng'

export interface AdminVoucherQueryParams {
  /**
   * Page number
   */
  page?: number
  /**
   * Items per page
   * @maximum 100
   */
  limit?: number
  sortBy?: AdminVoucherQueryParamsSortBy
  /** Sort order */
  sortOrder?: AdminVoucherQueryParamsSortOrder
  /** Search query */
  search?: string
  /** Universally Unique Identifier */
  businessId?: string
  /** Universally Unique Identifier */
  categoryId?: string
  state?: VoucherState
  discountType?: VoucherDiscountType
  /** @minimum 0 */
  minDiscount?: number
  /** @minimum 0 */
  maxDiscount?: number
  currency?: string
  /** ISO 8601 datetime with timezone */
  validFromStart?: string
  /** ISO 8601 datetime with timezone */
  validFromEnd?: string
  /** ISO 8601 datetime with timezone */
  expiresAtStart?: string
  /** ISO 8601 datetime with timezone */
  expiresAtEnd?: string
  /** ISO 8601 datetime with timezone */
  createdFromStart?: string
  /** ISO 8601 datetime with timezone */
  createdFromEnd?: string
  /** @minimum 0 */
  minRedemptions?: number
  /** @minimum 0 */
  maxRedemptions?: number
  /** @minimum 0 */
  minScans?: number
  /** @minimum 0 */
  maxScans?: number
  isDeleted?: boolean
  /** Comma-separated relations: business,category,codes,redemptions,scans,customerVouchers,analytics,fraudCases */
  include?: string
  /**
   * Search center latitude
   * @minimum -90
   * @maximum 90
   */
  lat?: AdminVoucherQueryParamsLat
  /**
   * Search center longitude
   * @minimum -180
   * @maximum 180
   */
  lng?: AdminVoucherQueryParamsLng
  /**
   * Search radius in kilometers
   */
  radius?: number
  /** Filter by active status */
  isActive?: boolean
  /** Filter by expired status */
  isExpired?: boolean
  /** Filter vouchers with location */
  hasLocation?: boolean
  /** Filter vouchers with image */
  hasImage?: boolean
}
