/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * The VoucherBook Complete API
 * Complete API documentation including public, admin, and internal endpoints
 * OpenAPI spec version: 1.0.0
 */
import type { AdminVerificationRequestType } from './adminVerificationRequestType'

export interface AdminVerificationRequest {
  type: AdminVerificationRequestType
  token?: string
  /**
   * @minLength 6
   * @maxLength 6
   */
  code?: string
  userId?: string
  email?: string
  phoneNumber?: string
}
