/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Pika Complete API
 * Complete API documentation including public, admin, and internal endpoints
 * OpenAPI spec version: 1.0.0
 */
import type { AdminFileDetailResponseFileType } from './adminFileDetailResponseFileType'
import type { AdminFileDetailResponseStatus } from './adminFileDetailResponseStatus'
import type { AdminFileDetailResponseProvider } from './adminFileDetailResponseProvider'
import type { AdminFileDetailResponseMetadata } from './adminFileDetailResponseMetadata'

/**
 * Admin file details with user information
 */
export interface AdminFileDetailResponse {
  /** Universally Unique Identifier */
  id: string
  userId: string
  userName?: string
  userEmail?: string
  fileKey: string
  fileName: string
  /** */
  fileSize: number
  mimeType: string
  /** File type category */
  fileType: AdminFileDetailResponseFileType
  /** File processing status */
  status: AdminFileDetailResponseStatus
  /** Supported storage provider */
  provider: AdminFileDetailResponseProvider
  bucketName?: string
  region?: string
  /** ISO 8601 datetime with timezone */
  uploadedAt?: string
  /** ISO 8601 datetime with timezone */
  deletedAt?: string
  metadata?: AdminFileDetailResponseMetadata
  error?: string
  isPublic?: boolean
  /** @minimum 0 */
  downloadCount?: number
  /** ISO 8601 datetime with timezone */
  lastAccessedAt?: string
  /** When the record was created */
  createdAt: string
  /** When the record was last updated */
  updatedAt: string
}
