/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * The VoucherBook Complete API
 * Complete API documentation including public, admin, and internal endpoints
 * OpenAPI spec version: 1.0.0
 */

export type AdminBulkFileActionRequestAction =
  (typeof AdminBulkFileActionRequestAction)[keyof typeof AdminBulkFileActionRequestAction]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AdminBulkFileActionRequestAction = {
  delete: 'delete',
  makePublic: 'makePublic',
  makePrivate: 'makePrivate',
  changeStatus: 'changeStatus',
} as const
