/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Pika Complete API
 * Complete API documentation including public, admin, and internal endpoints
 * OpenAPI spec version: 1.0.0
 */

export type AdminBusinessQueryParamsSortBy =
  (typeof AdminBusinessQueryParamsSortBy)[keyof typeof AdminBusinessQueryParamsSortBy]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AdminBusinessQueryParamsSortBy = {
  businessName: 'businessName',
  avgRating: 'avgRating',
  verified: 'verified',
  active: 'active',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
} as const
