/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Pika Complete API
 * Complete API documentation including public, admin, and internal endpoints
 * OpenAPI spec version: 1.0.0
 */
import type { AdminBulkVoucherBookOperationRequestOperation } from './adminBulkVoucherBookOperationRequestOperation'
import type { AdminBulkVoucherBookOperationRequestOptions } from './adminBulkVoucherBookOperationRequestOptions'

export interface AdminBulkVoucherBookOperationRequest {
  /**
   * Voucher book IDs to operate on
   * @minItems 1
   * @maxItems 100
   */
  bookIds: string[]
  /** Operation to perform */
  operation: AdminBulkVoucherBookOperationRequestOperation
  /** Operation-specific options */
  options?: AdminBulkVoucherBookOperationRequestOptions
}
