/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * The VoucherBook Complete API
 * Complete API documentation including public, admin, and internal endpoints
 * OpenAPI spec version: 1.0.0
 */

/**
 * Support ticket status
 */
export type AdminTicketDetailResponseStatus =
  (typeof AdminTicketDetailResponseStatus)[keyof typeof AdminTicketDetailResponseStatus]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AdminTicketDetailResponseStatus = {
  open: 'open',
  assigned: 'assigned',
  inProgress: 'inProgress',
  waitingCustomer: 'waitingCustomer',
  waitingInternal: 'waitingInternal',
  resolved: 'resolved',
  closed: 'closed',
} as const
