/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Pika Complete API
 * Complete API documentation including public, admin, and internal endpoints
 * OpenAPI spec version: 1.0.0
 */

/**
 * Change user role
 */
export type AdminUpdateUserRequestRole =
  (typeof AdminUpdateUserRequestRole)[keyof typeof AdminUpdateUserRequestRole]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AdminUpdateUserRequestRole = {
  admin: 'admin',
  customer: 'customer',
  business: 'business',
} as const
