/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Pika Complete API
 * Complete API documentation including public, admin, and internal endpoints
 * OpenAPI spec version: 1.0.0
 */

export type AdminTransactionDetailResponseDisputeStatus =
  (typeof AdminTransactionDetailResponseDisputeStatus)[keyof typeof AdminTransactionDetailResponseDisputeStatus]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AdminTransactionDetailResponseDisputeStatus = {
  warning: 'warning',
  needsResponse: 'needsResponse',
  underReview: 'underReview',
  won: 'won',
  lost: 'lost',
} as const
