/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Pika Complete API
 * Complete API documentation including public, admin, and internal endpoints
 * OpenAPI spec version: 1.0.0
 */

export type AdminCreateSubscriptionPlanRequestCurrency =
  (typeof AdminCreateSubscriptionPlanRequestCurrency)[keyof typeof AdminCreateSubscriptionPlanRequestCurrency]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AdminCreateSubscriptionPlanRequestCurrency = {
  usd: 'usd',
  eur: 'eur',
  gbp: 'gbp',
} as const
