/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Pika Complete API
 * Complete API documentation including public, admin, and internal endpoints
 * OpenAPI spec version: 1.0.0
 */

/**
 * Generation status
 */
export type AdminGeneratePdfResponseStatus =
  (typeof AdminGeneratePdfResponseStatus)[keyof typeof AdminGeneratePdfResponseStatus]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AdminGeneratePdfResponseStatus = {
  queued: 'queued',
  processing: 'processing',
  completed: 'completed',
  failed: 'failed',
} as const
