/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Pika Complete API
 * Complete API documentation including public, admin, and internal endpoints
 * OpenAPI spec version: 1.0.0
 */

/**
 * Sort order
 */
export type AdminCategoryQueryParamsSortOrder =
  (typeof AdminCategoryQueryParamsSortOrder)[keyof typeof AdminCategoryQueryParamsSortOrder]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AdminCategoryQueryParamsSortOrder = {
  asc: 'asc',
  desc: 'desc',
} as const
