/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * The VoucherBook Complete API
 * Complete API documentation including public, admin, and internal endpoints
 * OpenAPI spec version: 1.0.0
 */
import type { AdminBulkVoucherBookOperationResponseResultsItem } from './adminBulkVoucherBookOperationResponseResultsItem'

export interface AdminBulkVoucherBookOperationResponse {
  /**
   * Number of successful operations
   * @minimum 0
   */
  successful: number
  /**
   * Number of failed operations
   * @minimum 0
   */
  failed: number
  /** Detailed results for each book */
  results: AdminBulkVoucherBookOperationResponseResultsItem[]
}
