/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Pika Complete API
 * Complete API documentation including public, admin, and internal endpoints
 * OpenAPI spec version: 1.0.0
 */

/**
 * Type of voucher scan
 */
export type AdminVoucherDetailResponseScansItemScanType =
  (typeof AdminVoucherDetailResponseScansItemScanType)[keyof typeof AdminVoucherDetailResponseScansItemScanType]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AdminVoucherDetailResponseScansItemScanType = {
  customer: 'customer',
  business: 'business',
} as const
