/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Pika Complete API
 * Complete API documentation including public, admin, and internal endpoints
 * OpenAPI spec version: 1.0.0
 */

/**
 * Field to sort businesses by (admin view)
 */
export type AdminBusinessSortBy =
  (typeof AdminBusinessSortBy)[keyof typeof AdminBusinessSortBy]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AdminBusinessSortBy = {
  businessName: 'businessName',
  avgRating: 'avgRating',
  verified: 'verified',
  active: 'active',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  userId: 'userId',
  categoryId: 'categoryId',
} as const
