/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Pika Complete API
 * Complete API documentation including public, admin, and internal endpoints
 * OpenAPI spec version: 1.0.0
 */
import type { VoucherCodeType } from './voucherCodeType'
import type { AdminVoucherDetailResponseCodesItemMetadata } from './adminVoucherDetailResponseCodesItemMetadata'

export type AdminVoucherDetailResponseCodesItem = {
  /** Universally Unique Identifier */
  id: string
  /** @maxLength 500 */
  code: string
  type: VoucherCodeType
  isActive: boolean
  metadata: AdminVoucherDetailResponseCodesItemMetadata
  /** ISO 8601 datetime with timezone */
  createdAt: string
  /** ISO 8601 datetime with timezone */
  updatedAt: string
}
