/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * The VoucherBook Complete API
 * Complete API documentation including public, admin, and internal endpoints
 * OpenAPI spec version: 1.0.0
 */
import type { AdminTicketDetailResponseType } from './adminTicketDetailResponseType'
import type { AdminTicketDetailResponseStatus } from './adminTicketDetailResponseStatus'
import type { AdminTicketDetailResponsePriority } from './adminTicketDetailResponsePriority'

export interface AdminTicketDetailResponse {
  /** Universally Unique Identifier */
  id: string
  ticketNumber?: string
  userId: string
  userName: string
  userEmail: string
  title: string
  description: string
  /** Support ticket category/type */
  type: AdminTicketDetailResponseType
  /** Support ticket status */
  status: AdminTicketDetailResponseStatus
  /** Support ticket priority level */
  priority: AdminTicketDetailResponsePriority
  /** ISO 8601 datetime with timezone */
  resolvedAt?: string
  assignedTo?: string
  assignedToName?: string
  files?: string[]
  /** When the record was created */
  createdAt: string
  /** When the record was last updated */
  updatedAt: string
}
