/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Pika Complete API
 * Complete API documentation including public, admin, and internal endpoints
 * OpenAPI spec version: 1.0.0
 */
import type { AdminTransactionListResponseDataItemType } from './adminTransactionListResponseDataItemType'
import type { AdminTransactionListResponseDataItemStatus } from './adminTransactionListResponseDataItemStatus'
import type { AdminTransactionListResponseDataItemPaymentMethod } from './adminTransactionListResponseDataItemPaymentMethod'
import type { AdminTransactionListResponseDataItemDisputeStatus } from './adminTransactionListResponseDataItemDisputeStatus'
import type { AdminTransactionListResponseDataItemMetadata } from './adminTransactionListResponseDataItemMetadata'

/**
 * Detailed transaction information for admin
 */
export type AdminTransactionListResponseDataItem = {
  /** Universally Unique Identifier */
  id: string
  type: AdminTransactionListResponseDataItemType
  status: AdminTransactionListResponseDataItemStatus
  /** @minimum 0 */
  amount: number
  /**
   * @minLength 3
   * @maxLength 3
   */
  currency: string
  /** @minimum 0 */
  fee?: number
  /** @minimum 0 */
  tax?: number
  /** @minimum 0 */
  netAmount: number
  userId?: string
  userName?: string
  /** Universally Unique Identifier */
  businessId?: string
  businessName?: string
  paymentMethod: AdminTransactionListResponseDataItemPaymentMethod
  stripePaymentIntentId?: string
  stripeChargeId?: string
  stripeRefundId?: string
  /** Type of related entity */
  referenceType?: string
  /** ID of related entity */
  referenceId?: string
  description?: string
  /** ISO 8601 datetime with timezone */
  processedAt?: string
  failureReason?: string
  failureCode?: string
  disputeStatus?: AdminTransactionListResponseDataItemDisputeStatus
  disputeReason?: string
  refundReason?: string
  /** @minimum 0 */
  refundedAmount?: number
  metadata?: AdminTransactionListResponseDataItemMetadata
  ipAddress?: string
  userAgent?: string
  /** When the record was created */
  createdAt: string
  /** When the record was last updated */
  updatedAt: string
}
