/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Pika Complete API
 * Complete API documentation including public, admin, and internal endpoints
 * OpenAPI spec version: 1.0.0
 */
import type { AdminUserDetailResponseStatus } from './adminUserDetailResponseStatus'
import type { AdminUserDetailResponseRole } from './adminUserDetailResponseRole'

export interface AdminUserDetailResponse {
  id: string
  /** @minLength 1 */
  email: string
  firstName: string
  lastName: string
  phoneNumber?: string
  /**
   * Date in YYYY-MM-DD format
   * @pattern ^\d{4}-\d{2}-\d{2}$
   */
  dateOfBirth?: string
  avatarUrl?: string
  /** User account status */
  status: AdminUserDetailResponseStatus
  /** User role in the system */
  role: AdminUserDetailResponseRole
  emailVerified: boolean
  phoneVerified: boolean
  /** ISO 8601 datetime with timezone */
  lastLoginAt?: string
  /** When the record was created */
  createdAt: string
  /** When the record was last updated */
  updatedAt: string
}
