/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * The VoucherBook Complete API
 * Complete API documentation including public, admin, and internal endpoints
 * OpenAPI spec version: 1.0.0
 */
import type { AdminUpdateFileRequestStatus } from './adminUpdateFileRequestStatus'
import type { AdminUpdateFileRequestMetadata } from './adminUpdateFileRequestMetadata'

export interface AdminUpdateFileRequest {
  fileName?: string
  /** File processing status */
  status?: AdminUpdateFileRequestStatus
  isPublic?: boolean
  metadata?: AdminUpdateFileRequestMetadata
}
