/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * The VoucherBook Complete API
 * Complete API documentation including public, admin, and internal endpoints
 * OpenAPI spec version: 1.0.0
 */

/**
 * Field to sort users by (admin view)
 */
export type AdminUserSortBy =
  (typeof AdminUserSortBy)[keyof typeof AdminUserSortBy]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AdminUserSortBy = {
  createdAt: 'createdAt',
  lastLoginAt: 'lastLoginAt',
  email: 'email',
} as const
