/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Pika Complete API
 * Complete API documentation including public, admin, and internal endpoints
 * OpenAPI spec version: 1.0.0
 */

export type AdminVoucherListResponseDataItemLocationAnyOfType =
  (typeof AdminVoucherListResponseDataItemLocationAnyOfType)[keyof typeof AdminVoucherListResponseDataItemLocationAnyOfType]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AdminVoucherListResponseDataItemLocationAnyOfType = {
  Point: 'Point',
} as const
