/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Pika Complete API
 * Complete API documentation including public, admin, and internal endpoints
 * OpenAPI spec version: 1.0.0
 */
import type { AgentPerformanceResponsePeriod } from './agentPerformanceResponsePeriod'

/**
 * Individual agent performance metrics
 */
export interface AgentPerformanceResponse {
  agentId: string
  agentName: string
  period: AgentPerformanceResponsePeriod
  /** @minimum 0 */
  ticketsHandled: number
  /** @minimum 0 */
  ticketsResolved: number
  /** In minutes */
  averageResponseTime: number
  /** In hours */
  averageResolutionTime: number
  /**
   * @minimum 0
   * @maximum 5
   */
  satisfactionScore?: number
  /**
   * @minimum 0
   * @maximum 100
   */
  firstContactResolutionRate: number
}
