/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Pika Complete API
 * Complete API documentation including public, admin, and internal endpoints
 * OpenAPI spec version: 1.0.0
 */

/**
 * User role in the system
 */
export type ApproveAdminBusiness200UserRole =
  (typeof ApproveAdminBusiness200UserRole)[keyof typeof ApproveAdminBusiness200UserRole]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ApproveAdminBusiness200UserRole = {
  admin: 'admin',
  customer: 'customer',
  business: 'business',
} as const
