/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Pika Complete API
 * Complete API documentation including public, admin, and internal endpoints
 * OpenAPI spec version: 1.0.0
 */
import type { ApproveAdminBusiness200CategoryId } from './approveAdminBusiness200CategoryId'
import type { ApproveAdminBusiness200ApprovedBy } from './approveAdminBusiness200ApprovedBy'
import type { ApproveAdminBusiness200ApprovedAt } from './approveAdminBusiness200ApprovedAt'
import type { ApproveAdminBusiness200DeletedAt } from './approveAdminBusiness200DeletedAt'
import type { ApproveAdminBusiness200User } from './approveAdminBusiness200User'
import type { ApproveAdminBusiness200Category } from './approveAdminBusiness200Category'
import type { ApproveAdminBusiness200BusinessRegistration } from './approveAdminBusiness200BusinessRegistration'

export type ApproveAdminBusiness200 = {
  /** Universally Unique Identifier */
  id: string
  /** User who owns this business */
  userId: string
  /**
   * Business name (resolved translation)
   * @maxLength 255
   */
  businessName: string
  /**
   * Business description (resolved translation)
   * @maxLength 255
   */
  businessDescription?: string
  /** Category this business belongs to */
  categoryId: ApproveAdminBusiness200CategoryId
  /** Whether business is verified */
  verified?: boolean
  /** Whether business is active */
  active?: boolean
  /** Whether business is approved by admin */
  approved?: boolean
  /** Admin who approved the business */
  approvedBy?: ApproveAdminBusiness200ApprovedBy
  /** When the business was approved */
  approvedAt?: ApproveAdminBusiness200ApprovedAt
  /**
   * Average rating of the business
   * @minimum 0
   * @maximum 5
   */
  avgRating?: number
  /** Soft deletion timestamp */
  deletedAt: ApproveAdminBusiness200DeletedAt
  /** Business owner details when ?include=user */
  user?: ApproveAdminBusiness200User
  /** Category information when ?include=category */
  category?: ApproveAdminBusiness200Category
  /** Business registration info when ?include=businessRegistration */
  businessRegistration?: ApproveAdminBusiness200BusinessRegistration
  /** When the record was created */
  createdAt: string
  /** When the record was last updated */
  updatedAt: string
}
