/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Pika Complete API
 * Complete API documentation including public, admin, and internal endpoints
 * OpenAPI spec version: 1.0.0
 */
import type { AssignAdminTicketToAgentBodyPriority } from './assignAdminTicketToAgentBodyPriority'

/**
 * Assign ticket to agent
 */
export type AssignAdminTicketToAgentBody = {
  assigneeId: string
  /** @maxLength 500 */
  note?: string
  /** Support ticket priority level */
  priority?: AssignAdminTicketToAgentBodyPriority
}
