/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Pika Complete API
 * Complete API documentation including public, admin, and internal endpoints
 * OpenAPI spec version: 1.0.0
 */
import type { AssignAdminTicketToAgent200Type } from './assignAdminTicketToAgent200Type'
import type { AssignAdminTicketToAgent200Status } from './assignAdminTicketToAgent200Status'
import type { AssignAdminTicketToAgent200Priority } from './assignAdminTicketToAgent200Priority'

/**
 * Support ticket for admin
 */
export type AssignAdminTicketToAgent200 = {
  /** Universally Unique Identifier */
  id: string
  ticketNumber?: string
  userId: string
  userName: string
  userEmail: string
  title: string
  description: string
  /** Support ticket category/type */
  type: AssignAdminTicketToAgent200Type
  /** Support ticket status */
  status: AssignAdminTicketToAgent200Status
  /** Support ticket priority level */
  priority: AssignAdminTicketToAgent200Priority
  /** ISO 8601 datetime with timezone */
  resolvedAt?: string
  assignedTo?: string
  assignedToName?: string
  files?: string[]
  /** When the record was created */
  createdAt: string
  /** When the record was last updated */
  updatedAt: string
}
