/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * The VoucherBook Complete API
 * Complete API documentation including public, admin, and internal endpoints
 * OpenAPI spec version: 1.0.0
 */
import type { AuthToken200TokenType } from './authToken200TokenType'
import type { AuthToken200User } from './authToken200User'

export type AuthToken200 = {
  /**
   * JWT access token
   * @minLength 1
   */
  accessToken: string
  /** Token type */
  tokenType: AuthToken200TokenType
  /**
   * Token lifetime in seconds
   */
  expiresIn: number
  /**
   * JWT refresh token
   * @minLength 1
   */
  refreshToken?: string
  /** Granted permissions */
  scope?: string
  /** User information for password grant */
  user?: AuthToken200User
}
