/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * The VoucherBook Complete API
 * Complete API documentation including public, admin, and internal endpoints
 * OpenAPI spec version: 1.0.0
 */

/**
 * Type of authentication token
 */
export type AuthRevokeBodyTokenTypeHint =
  (typeof AuthRevokeBodyTokenTypeHint)[keyof typeof AuthRevokeBodyTokenTypeHint]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AuthRevokeBodyTokenTypeHint = {
  accessToken: 'accessToken',
  refreshToken: 'refreshToken',
} as const
