/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * The VoucherBook Complete API
 * Complete API documentation including public, admin, and internal endpoints
 * OpenAPI spec version: 1.0.0
 */
import type { AuthTokenBodyOneOf } from './authTokenBodyOneOf'
import type { AuthTokenBodyOneOfThree } from './authTokenBodyOneOfThree'

export type AuthTokenBody = AuthTokenBodyOneOf | AuthTokenBodyOneOfThree
