/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Pika Complete API
 * Complete API documentation including public, admin, and internal endpoints
 * OpenAPI spec version: 1.0.0
 */

/**
 * Token type
 */
export type AuthToken200TokenType =
  (typeof AuthToken200TokenType)[keyof typeof AuthToken200TokenType]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AuthToken200TokenType = {
  Bearer: 'Bearer',
} as const
