/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Pika Complete API
 * Complete API documentation including public, admin, and internal endpoints
 * OpenAPI spec version: 1.0.0
 */
import type { BatchFavoriteOperationResponseErrorsItem } from './batchFavoriteOperationResponseErrorsItem'

/**
 * Response for batch favorite operations
 */
export interface BatchFavoriteOperationResponse {
  /**
   * Number of items added
   * @minimum 0
   */
  added: number
  /**
   * Number of items removed
   * @minimum 0
   */
  removed: number
  /** List of errors if any operations failed */
  errors: BatchFavoriteOperationResponseErrorsItem[]
}
