/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Pika Complete API
 * Complete API documentation including public, admin, and internal endpoints
 * OpenAPI spec version: 1.0.0
 */
import type { BatchUpdateNotificationStatusRequestUpdatesItemStatus } from './batchUpdateNotificationStatusRequestUpdatesItemStatus'
import type { BatchUpdateNotificationStatusRequestUpdatesItemMetadata } from './batchUpdateNotificationStatusRequestUpdatesItemMetadata'

export type BatchUpdateNotificationStatusRequestUpdatesItem = {
  messageId: string
  status: BatchUpdateNotificationStatusRequestUpdatesItemStatus
  /** ISO 8601 datetime with timezone */
  timestamp: string
  metadata?: BatchUpdateNotificationStatusRequestUpdatesItemMetadata
}
