/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * The VoucherBook Complete API
 * Complete API documentation including public, admin, and internal endpoints
 * OpenAPI spec version: 1.0.0
 */
import type { BatchUploadFiles200SuccessfulItem } from './batchUploadFiles200SuccessfulItem'
import type { BatchUploadFiles200FailedItem } from './batchUploadFiles200FailedItem'

export type BatchUploadFiles200 = {
  successful: BatchUploadFiles200SuccessfulItem[]
  failed: BatchUploadFiles200FailedItem[]
  /** @minimum 0 */
  totalUploaded: number
  /** @minimum 0 */
  totalFailed: number
}
