/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Pika Complete API
 * Complete API documentation including public, admin, and internal endpoints
 * OpenAPI spec version: 1.0.0
 */

export type BatchUpdateNotificationStatusRequestUpdatesItemStatus =
  (typeof BatchUpdateNotificationStatusRequestUpdatesItemStatus)[keyof typeof BatchUpdateNotificationStatusRequestUpdatesItemStatus]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const BatchUpdateNotificationStatusRequestUpdatesItemStatus = {
  DELIVERED: 'DELIVERED',
  OPENED: 'OPENED',
  CLICKED: 'CLICKED',
  BOUNCED: 'BOUNCED',
  FAILED: 'FAILED',
} as const
