/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Pika Complete API
 * Complete API documentation including public, admin, and internal endpoints
 * OpenAPI spec version: 1.0.0
 */

/**
 * User role in the system
 */
export type BatchGetInternalUsers200ItemRole =
  (typeof BatchGetInternalUsers200ItemRole)[keyof typeof BatchGetInternalUsers200ItemRole]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const BatchGetInternalUsers200ItemRole = {
  admin: 'admin',
  customer: 'customer',
  business: 'business',
} as const
