/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Pika Complete API
 * Complete API documentation including public, admin, and internal endpoints
 * OpenAPI spec version: 1.0.0
 */
import type { BatchGetInternalUsers200ItemRole } from './batchGetInternalUsers200ItemRole'
import type { BatchGetInternalUsers200ItemNotificationPreferences } from './batchGetInternalUsers200ItemNotificationPreferences'

/**
 * Internal user data for services
 */
export type BatchGetInternalUsers200Item = {
  id: string
  /** @minLength 1 */
  email: string
  firstName: string
  lastName: string
  phoneNumber?: string
  isActive: boolean
  isVerified: boolean
  /** User role in the system */
  role: BatchGetInternalUsers200ItemRole
  /** ISO 8601 datetime with timezone */
  createdAt: string
  canMakePayments?: boolean
  canBookSessions?: boolean
  hasValidSubscription?: boolean
  stripeCustomerId?: string
  /**
   * @minLength 2
   * @maxLength 2
   */
  language?: string
  timezone?: string
  notificationPreferences: BatchGetInternalUsers200ItemNotificationPreferences
}
