/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Pika Complete API
 * Complete API documentation including public, admin, and internal endpoints
 * OpenAPI spec version: 1.0.0
 */

/**
 * Batch file upload request body
 */
export interface BatchFileUploadRequest {
  /** Target folder for uploads */
  folder?: string
  /** Whether files should be publicly accessible */
  isPublic?: string
}
