/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * The VoucherBook Complete API
 * Complete API documentation including public, admin, and internal endpoints
 * OpenAPI spec version: 1.0.0
 */

/**
 * Batch operations for managing favorite vouchers
 */
export interface BatchFavoriteVouchersRequest {
  /**
   * Voucher IDs to add to favorites (max 50)
   * @maxItems 50
   */
  add?: string[]
  /**
   * Voucher IDs to remove from favorites (max 50)
   * @maxItems 50
   */
  remove?: string[]
}
