/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Pika Complete API
 * Complete API documentation including public, admin, and internal endpoints
 * OpenAPI spec version: 1.0.0
 */
import type { BatchUploadFiles200SuccessfulItemFileType } from './batchUploadFiles200SuccessfulItemFileType'
import type { BatchUploadFiles200SuccessfulItemStatus } from './batchUploadFiles200SuccessfulItemStatus'
import type { BatchUploadFiles200SuccessfulItemProvider } from './batchUploadFiles200SuccessfulItemProvider'
import type { BatchUploadFiles200SuccessfulItemMetadata } from './batchUploadFiles200SuccessfulItemMetadata'

/**
 * Response after successful file upload
 */
export type BatchUploadFiles200SuccessfulItem = {
  /** Storage log ID */
  id: string
  /** Universally Unique Identifier */
  fileId: string
  fileKey: string
  fileName: string
  fileSize: number
  mimeType: string
  /** File type category */
  fileType: BatchUploadFiles200SuccessfulItemFileType
  /** File processing status */
  status: BatchUploadFiles200SuccessfulItemStatus
  /** Supported storage provider */
  provider: BatchUploadFiles200SuccessfulItemProvider
  /** Presigned URL if applicable */
  url?: string
  /** ISO 8601 datetime with timezone */
  uploadedAt: string
  /** File metadata */
  metadata?: BatchUploadFiles200SuccessfulItemMetadata
}
