/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Pika Complete API
 * Complete API documentation including public, admin, and internal endpoints
 * OpenAPI spec version: 1.0.0
 */

export type BatchGetInternalUsers200ItemNotificationPreferences = {
  email?: boolean
  push?: boolean
  sms?: boolean
}
