/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Pika Complete API
 * Complete API documentation including public, admin, and internal endpoints
 * OpenAPI spec version: 1.0.0
 */
import type { BulkDeleteAdminBusinesses200ErrorsItem } from './bulkDeleteAdminBusinesses200ErrorsItem'

export type BulkDeleteAdminBusinesses200 = {
  /** @minimum 0 */
  successful: number
  /** @minimum 0 */
  failed: number
  errors?: BulkDeleteAdminBusinesses200ErrorsItem[]
}
