/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * The VoucherBook Complete API
 * Complete API documentation including public, admin, and internal endpoints
 * OpenAPI spec version: 1.0.0
 */
import type { BulkActionAdminFiles200FailedItem } from './bulkActionAdminFiles200FailedItem'

export type BulkActionAdminFiles200 = {
  successful: string[]
  failed: BulkActionAdminFiles200FailedItem[]
  /** @minimum 0 */
  totalProcessed: number
  /** @minimum 0 */
  totalSuccessful: number
  /** @minimum 0 */
  totalFailed: number
}
