/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * The VoucherBook Complete API
 * Complete API documentation including public, admin, and internal endpoints
 * OpenAPI spec version: 1.0.0
 */
import type { BulkGetInternalVouchers200DataItem } from './bulkGetInternalVouchers200DataItem'
import type { PaginationMetadata } from './paginationMetadata'

/**
 * Batch fetch vouchers response with pagination metadata
 */
export type BulkGetInternalVouchers200 = {
  /** Page items */
  data: BulkGetInternalVouchers200DataItem[]
  pagination: PaginationMetadata
  /** IDs of vouchers that were not found */
  notFound: string[]
}
