/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Pika Complete API
 * Complete API documentation including public, admin, and internal endpoints
 * OpenAPI spec version: 1.0.0
 */

/**
 * Status of voucher from customer perspective
 */
export type BulkGetInternalVouchers200DataItemCustomerVouchersItemStatus =
  (typeof BulkGetInternalVouchers200DataItemCustomerVouchersItemStatus)[keyof typeof BulkGetInternalVouchers200DataItemCustomerVouchersItemStatus]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const BulkGetInternalVouchers200DataItemCustomerVouchersItemStatus = {
  available: 'available',
  claimed: 'claimed',
  redeemed: 'redeemed',
  expired: 'expired',
} as const
