/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * The VoucherBook Complete API
 * Complete API documentation including public, admin, and internal endpoints
 * OpenAPI spec version: 1.0.0
 */

/**
 * Get multiple businesses by IDs
 */
export interface BulkBusinessRequest {
  /**
   * @minItems 1
   * @maxItems 100
   */
  businessIds: string[]
  /** Comma-separated relations: user,category,businessDetails */
  include?: string
}
