/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Pika Complete API
 * Complete API documentation including public, admin, and internal endpoints
 * OpenAPI spec version: 1.0.0
 */

/**
 * Type of discount the voucher provides
 */
export type BulkGetInternalVouchers200DataItemDiscountType =
  (typeof BulkGetInternalVouchers200DataItemDiscountType)[keyof typeof BulkGetInternalVouchers200DataItemDiscountType]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const BulkGetInternalVouchers200DataItemDiscountType = {
  fixed: 'fixed',
  percentage: 'percentage',
} as const
