/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Pika Complete API
 * Complete API documentation including public, admin, and internal endpoints
 * OpenAPI spec version: 1.0.0
 */

export type BulkArchiveAdminVoucherBooks200 = {
  /** Number of books archived */
  archived: number
  /** Number of books that failed to archive */
  failed: number
  /** Error messages for failed operations */
  errors: string[]
}
