/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * The VoucherBook Complete API
 * Complete API documentation including public, admin, and internal endpoints
 * OpenAPI spec version: 1.0.0
 */

/**
 * Bulk email result
 */
export interface BulkEmailResponse {
  /** @minimum 0 */
  sent: number
  /** @minimum 0 */
  failed: number
}
