/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Pika Complete API
 * Complete API documentation including public, admin, and internal endpoints
 * OpenAPI spec version: 1.0.0
 */

export type BulkGetInternalVouchers200DataItemLocationAnyOfType =
  (typeof BulkGetInternalVouchers200DataItemLocationAnyOfType)[keyof typeof BulkGetInternalVouchers200DataItemLocationAnyOfType]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const BulkGetInternalVouchers200DataItemLocationAnyOfType = {
  Point: 'Point',
} as const
