/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Pika Complete API
 * Complete API documentation including public, admin, and internal endpoints
 * OpenAPI spec version: 1.0.0
 */

/**
 * Type of voucher code
 */
export type BulkGetInternalVouchers200DataItemCodesItemType =
  (typeof BulkGetInternalVouchers200DataItemCodesItemType)[keyof typeof BulkGetInternalVouchers200DataItemCodesItemType]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const BulkGetInternalVouchers200DataItemCodesItemType = {
  qr: 'qr',
  short: 'short',
  static: 'static',
} as const
