/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Pika Complete API
 * Complete API documentation including public, admin, and internal endpoints
 * OpenAPI spec version: 1.0.0
 */
import type { BulkUpdateAdminCategoriesBodyUpdates } from './bulkUpdateAdminCategoriesBodyUpdates'

export type BulkUpdateAdminCategoriesBody = {
  /**
   * @minItems 1
   * @maxItems 100
   */
  categoryIds: string[]
  updates: BulkUpdateAdminCategoriesBodyUpdates
}
