/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * The VoucherBook Complete API
 * Complete API documentation including public, admin, and internal endpoints
 * OpenAPI spec version: 1.0.0
 */
import type { BusinessListResponseDataItemUser } from './businessListResponseDataItemUser'
import type { BusinessListResponseDataItemCategory } from './businessListResponseDataItemCategory'
import type { BusinessListResponseDataItemBusinessDetails } from './businessListResponseDataItemBusinessDetails'

export type BusinessListResponseDataItem = {
  /** Universally Unique Identifier */
  id: string
  /** User who owns this business */
  userId: string
  /**
   * Business name in requested language
   * @maxLength 200
   */
  businessName: string
  /**
   * Business description in requested language
   * @maxLength 2000
   */
  businessDescription?: string
  /** Category this business belongs to */
  categoryId: string
  /** Whether business is verified */
  verified?: boolean
  /** Whether business is active */
  active?: boolean
  /** Whether business is approved by admin */
  approved?: boolean
  /**
   * Average rating of the business
   * @minimum 0
   * @maximum 5
   */
  avgRating?: number
  /** Business owner profile when ?include=user */
  user?: BusinessListResponseDataItemUser
  /** Category information when ?include=category */
  category?: BusinessListResponseDataItemCategory
  /** Detailed contact and location information when ?include=businessDetails */
  businessDetails?: BusinessListResponseDataItemBusinessDetails
  /** When the record was created */
  createdAt: string
  /** When the record was last updated */
  updatedAt: string
}
