/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * The VoucherBook Complete API
 * Complete API documentation including public, admin, and internal endpoints
 * OpenAPI spec version: 1.0.0
 */

/**
 * Filter businesses by status
 */
export type BusinessStatusFilter =
  (typeof BusinessStatusFilter)[keyof typeof BusinessStatusFilter]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const BusinessStatusFilter = {
  all: 'all',
  active: 'active',
  inactive: 'inactive',
  verified: 'verified',
  unverified: 'unverified',
} as const
