/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * The VoucherBook Complete API
 * Complete API documentation including public, admin, and internal endpoints
 * OpenAPI spec version: 1.0.0
 */
import type { BusinessRegistrationStep3RequestOperatingHours } from './businessRegistrationStep3RequestOperatingHours'
import type { BusinessRegistrationStep3RequestSocialMedia } from './businessRegistrationStep3RequestSocialMedia'
import type { BusinessRegistrationStep3RequestAdditionalInfo } from './businessRegistrationStep3RequestAdditionalInfo'

export interface BusinessRegistrationStep3Request {
  /** Operating hours */
  operatingHours?: BusinessRegistrationStep3RequestOperatingHours
  /** Social media links */
  socialMedia?: BusinessRegistrationStep3RequestSocialMedia
  /** Additional information */
  additionalInfo?: BusinessRegistrationStep3RequestAdditionalInfo
}
