/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Pika Complete API
 * Complete API documentation including public, admin, and internal endpoints
 * OpenAPI spec version: 1.0.0
 */
import type { BusinessRegistrationStatusResponseRegistrationStatus } from './businessRegistrationStatusResponseRegistrationStatus'

export interface BusinessRegistrationStatusResponse {
  /** Whether user needs to complete registration */
  needsRegistration: boolean
  /**
   * Current registration step number
   * @minimum 0
   * @maximum 3
   */
  currentStep: number
  /** Current registration status */
  registrationStatus: BusinessRegistrationStatusResponseRegistrationStatus
  /** Whether user can access dashboard */
  canAccessDashboard: boolean
  /** Registration ID if exists */
  registrationId?: string
  /** Business ID if created */
  businessId?: string
  /** When the record was created */
  createdAt: string
  /** When the record was last updated */
  updatedAt: string
}
