/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Pika Complete API
 * Complete API documentation including public, admin, and internal endpoints
 * OpenAPI spec version: 1.0.0
 */
import type { BusinessRegistrationStep2RequestAddress } from './businessRegistrationStep2RequestAddress'

export interface BusinessRegistrationStep2Request {
  /**
   * Business description
   * @minLength 1
   * @maxLength 500
   */
  description: string
  /** Business address */
  address: BusinessRegistrationStep2RequestAddress
  /**
   * Business phone number
   * @pattern ^\+[1-9]\d{1,14}$
   */
  phone: string
  /**
   * Business website URL
   * @maxLength 2048
   */
  website?: string
  /**
   * Business contact email
   * @minLength 1
   */
  email?: string
}
