/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * The VoucherBook Complete API
 * Complete API documentation including public, admin, and internal endpoints
 * OpenAPI spec version: 1.0.0
 */

/**
 * Field to sort categories by
 */
export type CategoryQueryParamsSortBy =
  (typeof CategoryQueryParamsSortBy)[keyof typeof CategoryQueryParamsSortBy]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CategoryQueryParamsSortBy = {
  name: 'name',
  sortOrder: 'sortOrder',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
} as const
