/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Pika Complete API
 * Complete API documentation including public, admin, and internal endpoints
 * OpenAPI spec version: 1.0.0
 */
import type { CheckBusinessExistsResponseBusiness } from './checkBusinessExistsResponseBusiness'

/**
 * Business existence check result
 */
export interface CheckBusinessExistsResponse {
  exists: boolean
  isActive?: boolean
  isVerified?: boolean
  /** Internal business data for services */
  business?: CheckBusinessExistsResponseBusiness
}
