/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Pika Complete API
 * Complete API documentation including public, admin, and internal endpoints
 * OpenAPI spec version: 1.0.0
 */

/**
 * Internal category data for services
 */
export type CheckInternalCategoryExists200Category = {
  /** Universally Unique Identifier */
  id: string
  name: string
  description?: string
  icon?: string
  /** Universally Unique Identifier */
  parentId?: string
  isActive: boolean
  sortOrder: number
}
