/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * The VoucherBook Complete API
 * Complete API documentation including public, admin, and internal endpoints
 * OpenAPI spec version: 1.0.0
 */
import type { ClaimVoucher200Voucher } from './claimVoucher200Voucher'
import type { ClaimVoucher200ExpiresAt } from './claimVoucher200ExpiresAt'

export type ClaimVoucher200 = {
  /** Universally Unique Identifier */
  claimId: string
  voucher: ClaimVoucher200Voucher
  claimedAt: string
  expiresAt: ClaimVoucher200ExpiresAt
  /** @minimum 0 */
  walletPosition: number
}
