/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Pika Complete API
 * Complete API documentation including public, admin, and internal endpoints
 * OpenAPI spec version: 1.0.0
 */

/**
 * Type of voucher code
 */
export type ClaimVoucher200VoucherCodesItemType =
  (typeof ClaimVoucher200VoucherCodesItemType)[keyof typeof ClaimVoucher200VoucherCodesItemType]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ClaimVoucher200VoucherCodesItemType = {
  qr: 'qr',
  short: 'short',
  static: 'static',
} as const
