/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Pika Complete API
 * Complete API documentation including public, admin, and internal endpoints
 * OpenAPI spec version: 1.0.0
 */

/**
 * Current state of the voucher lifecycle
 */
export type ClaimVoucher200VoucherState =
  (typeof ClaimVoucher200VoucherState)[keyof typeof ClaimVoucher200VoucherState]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ClaimVoucher200VoucherState = {
  draft: 'draft',
  published: 'published',
  claimed: 'claimed',
  redeemed: 'redeemed',
  expired: 'expired',
  suspended: 'suspended',
} as const
