/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * The VoucherBook Complete API
 * Complete API documentation including public, admin, and internal endpoints
 * OpenAPI spec version: 1.0.0
 */

/**
 * Support ticket priority level
 */
export type CreateSupportProblem201Priority =
  (typeof CreateSupportProblem201Priority)[keyof typeof CreateSupportProblem201Priority]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CreateSupportProblem201Priority = {
  low: 'low',
  medium: 'medium',
  high: 'high',
  urgent: 'urgent',
  critical: 'critical',
} as const
