/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * The VoucherBook Complete API
 * Complete API documentation including public, admin, and internal endpoints
 * OpenAPI spec version: 1.0.0
 */

/**
 * Support ticket category/type
 */
export type CreateSupportProblem201Type =
  (typeof CreateSupportProblem201Type)[keyof typeof CreateSupportProblem201Type]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CreateSupportProblem201Type = {
  billing: 'billing',
  technical: 'technical',
  account: 'account',
  general: 'general',
  bugReport: 'bugReport',
  featureRequest: 'featureRequest',
} as const
