/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Pika Complete API
 * Complete API documentation including public, admin, and internal endpoints
 * OpenAPI spec version: 1.0.0
 */
import type { CreateInternalFileBodyFileType } from './createInternalFileBodyFileType'
import type { CreateInternalFileBodyProvider } from './createInternalFileBodyProvider'
import type { CreateInternalFileBodyMetadata } from './createInternalFileBodyMetadata'

/**
 * Internal file creation request
 */
export type CreateInternalFileBody = {
  userId: string
  fileKey: string
  fileName: string
  /** */
  fileSize: number
  mimeType: string
  /** File type category */
  fileType: CreateInternalFileBodyFileType
  /** Supported storage provider */
  provider: CreateInternalFileBodyProvider
  bucketName?: string
  region?: string
  isPublic?: boolean
  metadata?: CreateInternalFileBodyMetadata
}
