/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Pika Complete API
 * Complete API documentation including public, admin, and internal endpoints
 * OpenAPI spec version: 1.0.0
 */
import type { VoucherState } from './voucherState'
import type { VoucherDiscountType } from './voucherDiscountType'
import type { CreateAdminVoucher201Location } from './createAdminVoucher201Location'
import type { CreateAdminVoucher201ImageUrl } from './createAdminVoucher201ImageUrl'
import type { CreateAdminVoucher201MaxRedemptions } from './createAdminVoucher201MaxRedemptions'
import type { CreateAdminVoucher201Metadata } from './createAdminVoucher201Metadata'
import type { CreateAdminVoucher201DeletedAt } from './createAdminVoucher201DeletedAt'
import type { CreateAdminVoucher201Business } from './createAdminVoucher201Business'
import type { CreateAdminVoucher201Category } from './createAdminVoucher201Category'
import type { CreateAdminVoucher201CodesItem } from './createAdminVoucher201CodesItem'
import type { CreateAdminVoucher201RedemptionsItem } from './createAdminVoucher201RedemptionsItem'
import type { CreateAdminVoucher201ScansItem } from './createAdminVoucher201ScansItem'
import type { CreateAdminVoucher201CustomerVouchersItem } from './createAdminVoucher201CustomerVouchersItem'
import type { CreateAdminVoucher201DaysUntilExpiry } from './createAdminVoucher201DaysUntilExpiry'

export type CreateAdminVoucher201 = {
  /** Universally Unique Identifier */
  id: string
  /** Universally Unique Identifier */
  businessId: string
  /** Universally Unique Identifier */
  categoryId: string
  state: VoucherState
  /** Voucher title in requested language */
  title: string
  /** Voucher description in requested language */
  description: string
  /** Voucher terms and conditions in requested language */
  terms: string
  discountType: VoucherDiscountType
  /** Decimal number with 2 decimal places */
  discountValue: number
  currency?: string
  location: CreateAdminVoucher201Location
  imageUrl: CreateAdminVoucher201ImageUrl
  /** ISO 8601 datetime with timezone */
  validFrom: string
  /** ISO 8601 datetime with timezone */
  expiresAt: string
  maxRedemptions: CreateAdminVoucher201MaxRedemptions
  maxRedemptionsPerUser?: number
  currentRedemptions?: number
  scanCount?: number
  claimCount?: number
  metadata: CreateAdminVoucher201Metadata
  /** ISO 8601 datetime with timezone */
  deletedAt: CreateAdminVoucher201DeletedAt
  /** Complete business object when ?include=business */
  business?: CreateAdminVoucher201Business
  /** Complete category object when ?include=category */
  category?: CreateAdminVoucher201Category
  /** Voucher codes when ?include=codes */
  codes?: CreateAdminVoucher201CodesItem[]
  /** Redemption history when ?include=redemptions */
  redemptions?: CreateAdminVoucher201RedemptionsItem[]
  /** Scan analytics when ?include=scans */
  scans?: CreateAdminVoucher201ScansItem[]
  /** Customer wallet entries when ?include=customerVouchers */
  customerVouchers?: CreateAdminVoucher201CustomerVouchersItem[]
  isActive: boolean
  isExpired: boolean
  /**
   * @minimum 0
   * @maximum 1
   */
  redemptionRate: number
  daysUntilExpiry: CreateAdminVoucher201DaysUntilExpiry
  /** When the record was created */
  createdAt: string
  /** When the record was last updated */
  updatedAt: string
}
