/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Pika Complete API
 * Complete API documentation including public, admin, and internal endpoints
 * OpenAPI spec version: 1.0.0
 */
import type { CreateAdminVoucher201ScansItemLocationAnyOf } from './createAdminVoucher201ScansItemLocationAnyOf'

export type CreateAdminVoucher201ScansItemLocation =
  CreateAdminVoucher201ScansItemLocationAnyOf | null
