/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * The VoucherBook Complete API
 * Complete API documentation including public, admin, and internal endpoints
 * OpenAPI spec version: 1.0.0
 */
import type { CreateNotificationResponseMetadata } from './createNotificationResponseMetadata'

/**
 * Create notification result
 */
export interface CreateNotificationResponse {
  id: string
  userId: string
  title: string
  description: string
  type: string
  isRead: boolean
  isGlobal?: boolean
  metadata?: CreateNotificationResponseMetadata
  createdAt: string
  updatedAt?: string
}
