/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * The VoucherBook Complete API
 * Complete API documentation including public, admin, and internal endpoints
 * OpenAPI spec version: 1.0.0
 */
import type { CreateSupportProblem201Status } from './createSupportProblem201Status'
import type { CreateSupportProblem201Priority } from './createSupportProblem201Priority'
import type { CreateSupportProblem201Type } from './createSupportProblem201Type'

export type CreateSupportProblem201 = {
  /** Universally Unique Identifier */
  id: string
  ticketNumber?: string
  userId: string
  title: string
  description: string
  /** Support ticket status */
  status: CreateSupportProblem201Status
  /** Support ticket priority level */
  priority: CreateSupportProblem201Priority
  /** Support ticket category/type */
  type: CreateSupportProblem201Type
  /** ISO 8601 datetime with timezone */
  resolvedAt?: string
  assignedTo?: string
  files?: string[]
  /** When the record was created */
  createdAt: string
  /** When the record was last updated */
  updatedAt: string
}
