/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * The VoucherBook Complete API
 * Complete API documentation including public, admin, and internal endpoints
 * OpenAPI spec version: 1.0.0
 */
import type { CreateAdminUserBodyRole } from './createAdminUserBodyRole'
import type { CreateAdminUserBodyStatus } from './createAdminUserBodyStatus'

export type CreateAdminUserBody = {
  /** @minLength 1 */
  email: string
  /**
   * @minLength 1
   * @maxLength 50
   */
  firstName: string
  /**
   * @minLength 1
   * @maxLength 50
   */
  lastName: string
  /**
   * Phone number in E.164 format
   * @pattern ^\+[1-9]\d{1,14}$
   */
  phoneNumber?: string
  /**
   * Date in YYYY-MM-DD format
   * @pattern ^\d{4}-\d{2}-\d{2}$
   */
  dateOfBirth?: string
  /**
   * Optional password - if not provided, user will set it on first login
   * @minLength 8
   * @maxLength 128
   */
  password?: string
  /** User role in the system */
  role?: CreateAdminUserBodyRole
  /** User account status */
  status?: CreateAdminUserBodyStatus
  /** Admin can create pre-verified users */
  emailVerified?: boolean
  phoneVerified?: boolean
  /**
   * @minLength 2
   * @maxLength 2
   * @pattern ^[a-z]{2}$
   */
  preferredLanguage?: string
}
