/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Pika Complete API
 * Complete API documentation including public, admin, and internal endpoints
 * OpenAPI spec version: 1.0.0
 */
import type { CreateSubscriptionRequestMetadata } from './createSubscriptionRequestMetadata'

/**
 * Create a new subscription
 */
export interface CreateSubscriptionRequest {
  /** Universally Unique Identifier */
  planId: string
  stripeCustomerId?: string
  /** ISO 8601 datetime with timezone */
  trialEnd?: string
  metadata?: CreateSubscriptionRequestMetadata
}
