/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Pika Complete API
 * Complete API documentation including public, admin, and internal endpoints
 * OpenAPI spec version: 1.0.0
 */
import type { CustomerVoucherStatus } from './customerVoucherStatus'
import type { CreateAdminVoucher201CustomerVouchersItemNotificationPreferences } from './createAdminVoucher201CustomerVouchersItemNotificationPreferences'
import type { CreateAdminVoucher201CustomerVouchersItemRedeemedAt } from './createAdminVoucher201CustomerVouchersItemRedeemedAt'

export type CreateAdminVoucher201CustomerVouchersItem = {
  /** Universally Unique Identifier */
  id: string
  /** Universally Unique Identifier */
  customerId: string
  /** ISO 8601 datetime with timezone */
  claimedAt: string
  status: CustomerVoucherStatus
  notificationPreferences: CreateAdminVoucher201CustomerVouchersItemNotificationPreferences
  /** ISO 8601 datetime with timezone */
  redeemedAt: CreateAdminVoucher201CustomerVouchersItemRedeemedAt
  /** ISO 8601 datetime with timezone */
  createdAt: string
  /** ISO 8601 datetime with timezone */
  updatedAt: string
}
