/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * The VoucherBook Complete API
 * Complete API documentation including public, admin, and internal endpoints
 * OpenAPI spec version: 1.0.0
 */

/**
 * Status of voucher from customer perspective
 */
export type CustomerVoucherStatus =
  (typeof CustomerVoucherStatus)[keyof typeof CustomerVoucherStatus]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CustomerVoucherStatus = {
  available: 'available',
  claimed: 'claimed',
  redeemed: 'redeemed',
  expired: 'expired',
} as const
