/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Pika Complete API
 * Complete API documentation including public, admin, and internal endpoints
 * OpenAPI spec version: 1.0.0
 */

/**
 * Service deregistration confirmation
 */
export type DeregisterInternalService200 = {
  /** Universally Unique Identifier */
  instanceId: string
  serviceName: string
  /** ISO 8601 datetime with timezone */
  deregisteredAt: string
  gracefulShutdown: boolean
  message?: string
}
