/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * The VoucherBook Complete API
 * Complete API documentation including public, admin, and internal endpoints
 * OpenAPI spec version: 1.0.0
 */
import type { DeviceInfoPlatform } from './deviceInfoPlatform'

/**
 * Device information for tracking
 */
export interface DeviceInfo {
  userAgent?: string
  platform?: DeviceInfoPlatform
  appVersion?: string
  deviceId?: string
}
