/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * The VoucherBook Complete API
 * Complete API documentation including public, admin, and internal endpoints
 * OpenAPI spec version: 1.0.0
 */

/**
 * OAuth provider (google or facebook)
 */
export type ExchangeTokenRequestProvider =
  (typeof ExchangeTokenRequestProvider)[keyof typeof ExchangeTokenRequestProvider]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ExchangeTokenRequestProvider = {
  google: 'google',
  facebook: 'facebook',
  apple: 'apple',
} as const
