/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * The VoucherBook Complete API
 * Complete API documentation including public, admin, and internal endpoints
 * OpenAPI spec version: 1.0.0
 */
import type { ExchangeTokenRequestProvider } from './exchangeTokenRequestProvider'

/**
 * Request to exchange OAuth authorization code for tokens
 */
export interface ExchangeTokenRequest {
  /**
   * Authorization code from OAuth provider
   * @minLength 1
   */
  code: string
  /** OAuth provider (google or facebook) */
  provider: ExchangeTokenRequestProvider
  /** Redirect URI used in OAuth flow */
  redirectUri: string
  /** State parameter for CSRF protection */
  state?: string
}
