/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * The VoucherBook Complete API
 * Complete API documentation including public, admin, and internal endpoints
 * OpenAPI spec version: 1.0.0
 */
import type { ExchangeToken200UserRole } from './exchangeToken200UserRole'

/**
 * Authenticated user information
 */
export type ExchangeToken200User = {
  id: string
  /** @minLength 1 */
  email: string
  firstName: string
  lastName: string
  profilePicture?: string
  /** User role in the system */
  role: ExchangeToken200UserRole
}
