/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * The VoucherBook Complete API
 * Complete API documentation including public, admin, and internal endpoints
 * OpenAPI spec version: 1.0.0
 */
import type { VoucherState } from './voucherState'
import type { VoucherDiscountType } from './voucherDiscountType'
import type { ExpireAdminVoucher200Location } from './expireAdminVoucher200Location'
import type { ExpireAdminVoucher200ImageUrl } from './expireAdminVoucher200ImageUrl'
import type { ExpireAdminVoucher200MaxRedemptions } from './expireAdminVoucher200MaxRedemptions'
import type { ExpireAdminVoucher200Metadata } from './expireAdminVoucher200Metadata'
import type { ExpireAdminVoucher200DeletedAt } from './expireAdminVoucher200DeletedAt'
import type { ExpireAdminVoucher200Business } from './expireAdminVoucher200Business'
import type { ExpireAdminVoucher200Category } from './expireAdminVoucher200Category'
import type { ExpireAdminVoucher200CodesItem } from './expireAdminVoucher200CodesItem'
import type { ExpireAdminVoucher200RedemptionsItem } from './expireAdminVoucher200RedemptionsItem'
import type { ExpireAdminVoucher200ScansItem } from './expireAdminVoucher200ScansItem'
import type { ExpireAdminVoucher200CustomerVouchersItem } from './expireAdminVoucher200CustomerVouchersItem'
import type { ExpireAdminVoucher200DaysUntilExpiry } from './expireAdminVoucher200DaysUntilExpiry'

export type ExpireAdminVoucher200 = {
  /** Universally Unique Identifier */
  id: string
  /** Universally Unique Identifier */
  businessId: string
  /** Universally Unique Identifier */
  categoryId?: string
  state: VoucherState
  /** Voucher title in requested language */
  title: string
  /** Voucher description in requested language */
  description: string
  /** Voucher terms and conditions in requested language */
  terms: string
  discountType: VoucherDiscountType
  /** Decimal number with 2 decimal places */
  discountValue: number
  currency?: string
  location: ExpireAdminVoucher200Location
  imageUrl: ExpireAdminVoucher200ImageUrl
  /** ISO 8601 datetime with timezone */
  validFrom: string
  /** ISO 8601 datetime with timezone */
  expiresAt: string
  maxRedemptions: ExpireAdminVoucher200MaxRedemptions
  maxRedemptionsPerUser?: number
  currentRedemptions?: number
  scanCount?: number
  claimCount?: number
  metadata: ExpireAdminVoucher200Metadata
  /** ISO 8601 datetime with timezone */
  deletedAt: ExpireAdminVoucher200DeletedAt
  /** Complete business object when ?include=business */
  business?: ExpireAdminVoucher200Business
  /** Complete category object when ?include=category */
  category?: ExpireAdminVoucher200Category
  /** Voucher codes when ?include=codes */
  codes?: ExpireAdminVoucher200CodesItem[]
  /** Redemption history when ?include=redemptions */
  redemptions?: ExpireAdminVoucher200RedemptionsItem[]
  /** Scan analytics when ?include=scans */
  scans?: ExpireAdminVoucher200ScansItem[]
  /** Customer wallet entries when ?include=customerVouchers */
  customerVouchers?: ExpireAdminVoucher200CustomerVouchersItem[]
  isActive: boolean
  isExpired: boolean
  /**
   * @minimum 0
   * @maximum 1
   */
  redemptionRate: number
  daysUntilExpiry: ExpireAdminVoucher200DaysUntilExpiry
  /** When the record was created */
  createdAt: string
  /** When the record was last updated */
  updatedAt: string
}
