/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * The VoucherBook Complete API
 * Complete API documentation including public, admin, and internal endpoints
 * OpenAPI spec version: 1.0.0
 */
import type { CustomerVoucherStatus } from './customerVoucherStatus'
import type { ExpireAdminVoucher200CustomerVouchersItemNotificationPreferences } from './expireAdminVoucher200CustomerVouchersItemNotificationPreferences'
import type { ExpireAdminVoucher200CustomerVouchersItemRedeemedAt } from './expireAdminVoucher200CustomerVouchersItemRedeemedAt'

export type ExpireAdminVoucher200CustomerVouchersItem = {
  /** Universally Unique Identifier */
  id: string
  /** Universally Unique Identifier */
  customerId: string
  /** ISO 8601 datetime with timezone */
  claimedAt: string
  status: CustomerVoucherStatus
  notificationPreferences: ExpireAdminVoucher200CustomerVouchersItemNotificationPreferences
  /** ISO 8601 datetime with timezone */
  redeemedAt: ExpireAdminVoucher200CustomerVouchersItemRedeemedAt
  /** ISO 8601 datetime with timezone */
  createdAt: string
  /** ISO 8601 datetime with timezone */
  updatedAt: string
}
