/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * The VoucherBook Complete API
 * Complete API documentation including public, admin, and internal endpoints
 * OpenAPI spec version: 1.0.0
 */
import type { ExpireAdminVoucher200ScansItemLocationAnyOfType } from './expireAdminVoucher200ScansItemLocationAnyOfType'

export type ExpireAdminVoucher200ScansItemLocationAnyOf = {
  type: ExpireAdminVoucher200ScansItemLocationAnyOfType
  /** [longitude, latitude] - GeoJSON standard */
  coordinates: [number, number]
}
