/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Pika Complete API
 * Complete API documentation including public, admin, and internal endpoints
 * OpenAPI spec version: 1.0.0
 */
import type { FavoriteBusinessItemBusinessBusinessDetailsOperatingHours } from './favoriteBusinessItemBusinessBusinessDetailsOperatingHours'
import type { FavoriteBusinessItemBusinessBusinessDetailsSocialMedia } from './favoriteBusinessItemBusinessBusinessDetailsSocialMedia'
import type { FavoriteBusinessItemBusinessBusinessDetailsAdditionalInfo } from './favoriteBusinessItemBusinessBusinessDetailsAdditionalInfo'

/**
 * Detailed contact and location information when ?include=businessDetails
 */
export type FavoriteBusinessItemBusinessBusinessDetails = {
  /** Universally Unique Identifier */
  id: string
  /** Business ID this details belong to */
  businessId: string
  /**
   * Business phone number
   * @maxLength 20
   */
  phone?: string
  /**
   * Business email address
   * @maxLength 255
   */
  email?: string
  /**
   * Business website URL
   * @maxLength 255
   */
  website?: string
  /**
   * Business logo image URL
   * @maxLength 512
   */
  logoUrl?: string
  /**
   * Street address
   * @maxLength 255
   */
  street?: string
  /**
   * City
   * @maxLength 100
   */
  city?: string
  /**
   * State or province
   * @maxLength 100
   */
  state?: string
  /**
   * Postal/ZIP code
   * @maxLength 20
   */
  postalCode?: string
  /**
   * Country code (ISO 3166-1 alpha-2)
   * @minLength 2
   * @maxLength 2
   */
  country?: string
  /** Operating hours schedule (JSON) */
  operatingHours?: FavoriteBusinessItemBusinessBusinessDetailsOperatingHours
  /** Social media links (JSON) */
  socialMedia?: FavoriteBusinessItemBusinessBusinessDetailsSocialMedia
  /** Additional business information (JSON) */
  additionalInfo?: FavoriteBusinessItemBusinessBusinessDetailsAdditionalInfo
  /** When the record was created */
  createdAt: string
  /** When the record was last updated */
  updatedAt: string
}
