/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Pika Complete API
 * Complete API documentation including public, admin, and internal endpoints
 * OpenAPI spec version: 1.0.0
 */
import type { FavoriteStatusResponseFavoritedAt } from './favoriteStatusResponseFavoritedAt'

/**
 * Favorite status for an item
 */
export interface FavoriteStatusResponse {
  /** Whether the item is favorited */
  isFavorited: boolean
  /** When the item was favorited (if favorited) */
  favoritedAt?: FavoriteStatusResponseFavoritedAt
}
