/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Pika Complete API
 * Complete API documentation including public, admin, and internal endpoints
 * OpenAPI spec version: 1.0.0
 */
import type { FavoriteBusinessItemCreatedAt } from './favoriteBusinessItemCreatedAt'
import type { FavoriteBusinessItemBusiness } from './favoriteBusinessItemBusiness'

/**
 * A favorite business relationship
 */
export interface FavoriteBusinessItem {
  /** Favorite record ID */
  id: string
  /** Business ID */
  businessId: string
  /** When the business was favorited */
  createdAt: FavoriteBusinessItemCreatedAt
  /** Full business details when ?include=business */
  business?: FavoriteBusinessItemBusiness
}
