/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Pika Complete API
 * Complete API documentation including public, admin, and internal endpoints
 * OpenAPI spec version: 1.0.0
 */
import type { FileUploadResponseFileType } from './fileUploadResponseFileType'
import type { FileUploadResponseStatus } from './fileUploadResponseStatus'
import type { FileUploadResponseProvider } from './fileUploadResponseProvider'
import type { FileUploadResponseMetadata } from './fileUploadResponseMetadata'

/**
 * Response after successful file upload
 */
export interface FileUploadResponse {
  /** Storage log ID */
  id: string
  /** Universally Unique Identifier */
  fileId: string
  fileKey: string
  fileName: string
  fileSize: number
  mimeType: string
  /** File type category */
  fileType: FileUploadResponseFileType
  /** File processing status */
  status: FileUploadResponseStatus
  /** Supported storage provider */
  provider: FileUploadResponseProvider
  /** Presigned URL if applicable */
  url?: string
  /** ISO 8601 datetime with timezone */
  uploadedAt: string
  /** File metadata */
  metadata?: FileUploadResponseMetadata
}
