/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Pika Complete API
 * Complete API documentation including public, admin, and internal endpoints
 * OpenAPI spec version: 1.0.0
 */
import type { FileStorageLogFileType } from './fileStorageLogFileType'
import type { FileStorageLogStatus } from './fileStorageLogStatus'
import type { FileStorageLogProvider } from './fileStorageLogProvider'
import type { FileStorageLogMetadata } from './fileStorageLogMetadata'

/**
 * File storage log entry
 */
export interface FileStorageLog {
  /** Universally Unique Identifier */
  id: string
  userId: string
  /** Storage key/path */
  fileKey: string
  fileName: string
  /**
   * Size in bytes
   */
  fileSize: number
  mimeType: string
  /** File type category */
  fileType: FileStorageLogFileType
  /** File processing status */
  status: FileStorageLogStatus
  /** Supported storage provider */
  provider: FileStorageLogProvider
  bucketName?: string
  region?: string
  /** ISO 8601 datetime with timezone */
  uploadedAt?: string
  /** ISO 8601 datetime with timezone */
  deletedAt?: string
  metadata?: FileStorageLogMetadata
  error?: string
  /** When the record was created */
  createdAt: string
  /** When the record was last updated */
  updatedAt: string
}
