/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Pika Complete API
 * Complete API documentation including public, admin, and internal endpoints
 * OpenAPI spec version: 1.0.0
 */
import type { FileHistoryResponseDataItemFileType } from './fileHistoryResponseDataItemFileType'
import type { FileHistoryResponseDataItemStatus } from './fileHistoryResponseDataItemStatus'
import type { FileHistoryResponseDataItemProvider } from './fileHistoryResponseDataItemProvider'
import type { FileHistoryResponseDataItemMetadata } from './fileHistoryResponseDataItemMetadata'

/**
 * File storage log entry
 */
export type FileHistoryResponseDataItem = {
  /** Universally Unique Identifier */
  id: string
  userId: string
  /** Storage key/path */
  fileKey: string
  fileName: string
  /**
   * Size in bytes
   */
  fileSize: number
  mimeType: string
  /** File type category */
  fileType: FileHistoryResponseDataItemFileType
  /** File processing status */
  status: FileHistoryResponseDataItemStatus
  /** Supported storage provider */
  provider: FileHistoryResponseDataItemProvider
  bucketName?: string
  region?: string
  /** ISO 8601 datetime with timezone */
  uploadedAt?: string
  /** ISO 8601 datetime with timezone */
  deletedAt?: string
  metadata?: FileHistoryResponseDataItemMetadata
  error?: string
  /** When the record was created */
  createdAt: string
  /** When the record was last updated */
  updatedAt: string
}
