/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * The VoucherBook Complete API
 * Complete API documentation including public, admin, and internal endpoints
 * OpenAPI spec version: 1.0.0
 */

export type GenerateAdminVoucherCodes200LocationAnyOfType =
  (typeof GenerateAdminVoucherCodes200LocationAnyOfType)[keyof typeof GenerateAdminVoucherCodes200LocationAnyOfType]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GenerateAdminVoucherCodes200LocationAnyOfType = {
  Point: 'Point',
} as const
