/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Pika Complete API
 * Complete API documentation including public, admin, and internal endpoints
 * OpenAPI spec version: 1.0.0
 */
import type { GenerateAdminVoucherCodes200LocationAnyOfType } from './generateAdminVoucherCodes200LocationAnyOfType'

export type GenerateAdminVoucherCodes200LocationAnyOf = {
  type: GenerateAdminVoucherCodes200LocationAnyOfType
  /** [longitude, latitude] - GeoJSON standard */
  coordinates: [number, number]
}
