/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * The VoucherBook Complete API
 * Complete API documentation including public, admin, and internal endpoints
 * OpenAPI spec version: 1.0.0
 */
import type { GenerateAdminVoucherCodes200ScansItemLocationAnyOfType } from './generateAdminVoucherCodes200ScansItemLocationAnyOfType'

export type GenerateAdminVoucherCodes200ScansItemLocationAnyOf = {
  type: GenerateAdminVoucherCodes200ScansItemLocationAnyOfType
  /** [longitude, latitude] - GeoJSON standard */
  coordinates: [number, number]
}
