/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Pika Complete API
 * Complete API documentation including public, admin, and internal endpoints
 * OpenAPI spec version: 1.0.0
 */
import type { VoucherState } from './voucherState'
import type { VoucherDiscountType } from './voucherDiscountType'
import type { GetAdminVoucherList200DataItemLocation } from './getAdminVoucherList200DataItemLocation'
import type { GetAdminVoucherList200DataItemImageUrl } from './getAdminVoucherList200DataItemImageUrl'
import type { GetAdminVoucherList200DataItemMaxRedemptions } from './getAdminVoucherList200DataItemMaxRedemptions'
import type { GetAdminVoucherList200DataItemMetadata } from './getAdminVoucherList200DataItemMetadata'
import type { GetAdminVoucherList200DataItemDeletedAt } from './getAdminVoucherList200DataItemDeletedAt'
import type { GetAdminVoucherList200DataItemBusiness } from './getAdminVoucherList200DataItemBusiness'
import type { GetAdminVoucherList200DataItemCategory } from './getAdminVoucherList200DataItemCategory'
import type { GetAdminVoucherList200DataItemCodesItem } from './getAdminVoucherList200DataItemCodesItem'
import type { GetAdminVoucherList200DataItemRedemptionsItem } from './getAdminVoucherList200DataItemRedemptionsItem'
import type { GetAdminVoucherList200DataItemScansItem } from './getAdminVoucherList200DataItemScansItem'
import type { GetAdminVoucherList200DataItemCustomerVouchersItem } from './getAdminVoucherList200DataItemCustomerVouchersItem'
import type { GetAdminVoucherList200DataItemDaysUntilExpiry } from './getAdminVoucherList200DataItemDaysUntilExpiry'

export type GetAdminVoucherList200DataItem = {
  /** Universally Unique Identifier */
  id: string
  /** Universally Unique Identifier */
  businessId: string
  /** Universally Unique Identifier */
  categoryId?: string
  state: VoucherState
  /** Voucher title in requested language */
  title: string
  /** Voucher description in requested language */
  description: string
  /** Voucher terms and conditions in requested language */
  terms: string
  discountType: VoucherDiscountType
  /** Decimal number with 2 decimal places */
  discountValue: number
  currency?: string
  location: GetAdminVoucherList200DataItemLocation
  imageUrl: GetAdminVoucherList200DataItemImageUrl
  /** ISO 8601 datetime with timezone */
  validFrom: string
  /** ISO 8601 datetime with timezone */
  expiresAt: string
  maxRedemptions: GetAdminVoucherList200DataItemMaxRedemptions
  maxRedemptionsPerUser?: number
  currentRedemptions?: number
  scanCount?: number
  claimCount?: number
  metadata: GetAdminVoucherList200DataItemMetadata
  /** ISO 8601 datetime with timezone */
  deletedAt: GetAdminVoucherList200DataItemDeletedAt
  /** Complete business object when ?include=business */
  business?: GetAdminVoucherList200DataItemBusiness
  /** Complete category object when ?include=category */
  category?: GetAdminVoucherList200DataItemCategory
  /** Voucher codes when ?include=codes */
  codes?: GetAdminVoucherList200DataItemCodesItem[]
  /** Redemption history when ?include=redemptions */
  redemptions?: GetAdminVoucherList200DataItemRedemptionsItem[]
  /** Scan analytics when ?include=scans */
  scans?: GetAdminVoucherList200DataItemScansItem[]
  /** Customer wallet entries when ?include=customerVouchers */
  customerVouchers?: GetAdminVoucherList200DataItemCustomerVouchersItem[]
  isActive: boolean
  isExpired: boolean
  /**
   * @minimum 0
   * @maximum 1
   */
  redemptionRate: number
  daysUntilExpiry: GetAdminVoucherList200DataItemDaysUntilExpiry
  /** When the record was created */
  createdAt: string
  /** When the record was last updated */
  updatedAt: string
}
