/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * The VoucherBook Complete API
 * Complete API documentation including public, admin, and internal endpoints
 * OpenAPI spec version: 1.0.0
 */
import type { GetAdminVoucherTranslations200Translations } from './getAdminVoucherTranslations200Translations'

export type GetAdminVoucherTranslations200 = {
  /** Universally Unique Identifier */
  voucherId: string
  translations: GetAdminVoucherTranslations200Translations
}
