/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Pika Complete API
 * Complete API documentation including public, admin, and internal endpoints
 * OpenAPI spec version: 1.0.0
 */

export type GetAdminCommentListSortOrder =
  (typeof GetAdminCommentListSortOrder)[keyof typeof GetAdminCommentListSortOrder]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetAdminCommentListSortOrder = {
  ASC: 'ASC',
  DESC: 'DESC',
} as const
