/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * The VoucherBook Complete API
 * Complete API documentation including public, admin, and internal endpoints
 * OpenAPI spec version: 1.0.0
 */
import type { GetAdminSupportTicketById200Type } from './getAdminSupportTicketById200Type'
import type { GetAdminSupportTicketById200Status } from './getAdminSupportTicketById200Status'
import type { GetAdminSupportTicketById200Priority } from './getAdminSupportTicketById200Priority'

export type GetAdminSupportTicketById200 = {
  /** Universally Unique Identifier */
  id: string
  ticketNumber?: string
  userId: string
  userName: string
  userEmail: string
  title: string
  description: string
  /** Support ticket category/type */
  type: GetAdminSupportTicketById200Type
  /** Support ticket status */
  status: GetAdminSupportTicketById200Status
  /** Support ticket priority level */
  priority: GetAdminSupportTicketById200Priority
  /** ISO 8601 datetime with timezone */
  resolvedAt?: string
  assignedTo?: string
  assignedToName?: string
  files?: string[]
  /** When the record was created */
  createdAt: string
  /** When the record was last updated */
  updatedAt: string
}
