/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * The VoucherBook Complete API
 * Complete API documentation including public, admin, and internal endpoints
 * OpenAPI spec version: 1.0.0
 */

export type GetAdminSupportTicketListSortBy =
  (typeof GetAdminSupportTicketListSortBy)[keyof typeof GetAdminSupportTicketListSortBy]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetAdminSupportTicketListSortBy = {
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  resolvedAt: 'resolvedAt',
  priority: 'priority',
  status: 'status',
} as const
