/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Pika Complete API
 * Complete API documentation including public, admin, and internal endpoints
 * OpenAPI spec version: 1.0.0
 */
import type { GetAdminBusinessList200DataItemDeletedAt } from './getAdminBusinessList200DataItemDeletedAt'
import type { GetAdminBusinessList200DataItemUser } from './getAdminBusinessList200DataItemUser'
import type { CategoryResponse } from './categoryResponse'

/**
 * Business information for admin management
 */
export type GetAdminBusinessList200DataItem = {
  /** Universally Unique Identifier */
  id: string
  /** User who owns this business */
  userId: string
  /**
   * Translation key for business name
   * @maxLength 255
   */
  businessNameKey: string
  /**
   * Translation key for business description
   * @maxLength 255
   */
  businessDescriptionKey?: string
  /** Category this business belongs to */
  categoryId: string
  /** Whether business is verified */
  verified?: boolean
  /** Whether business is active */
  active?: boolean
  /**
   * Average rating of the business
   * @minimum 0
   * @maximum 5
   */
  avgRating?: number
  /** Soft deletion timestamp */
  deletedAt: GetAdminBusinessList200DataItemDeletedAt
  /** Business owner details when ?include=user */
  user?: GetAdminBusinessList200DataItemUser
  category?: CategoryResponse
  /** When the record was created */
  createdAt: string
  /** When the record was last updated */
  updatedAt: string
}
