/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Pika Complete API
 * Complete API documentation including public, admin, and internal endpoints
 * OpenAPI spec version: 1.0.0
 */
import type { CustomerVoucherStatus } from './customerVoucherStatus'
import type { GetAdminVoucherById200CustomerVouchersItemNotificationPreferences } from './getAdminVoucherById200CustomerVouchersItemNotificationPreferences'
import type { GetAdminVoucherById200CustomerVouchersItemRedeemedAt } from './getAdminVoucherById200CustomerVouchersItemRedeemedAt'

export type GetAdminVoucherById200CustomerVouchersItem = {
  /** Universally Unique Identifier */
  id: string
  /** Universally Unique Identifier */
  customerId: string
  /** ISO 8601 datetime with timezone */
  claimedAt: string
  status: CustomerVoucherStatus
  notificationPreferences: GetAdminVoucherById200CustomerVouchersItemNotificationPreferences
  /** ISO 8601 datetime with timezone */
  redeemedAt: GetAdminVoucherById200CustomerVouchersItemRedeemedAt
  /** ISO 8601 datetime with timezone */
  createdAt: string
  /** ISO 8601 datetime with timezone */
  updatedAt: string
}
