/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Pika Complete API
 * Complete API documentation including public, admin, and internal endpoints
 * OpenAPI spec version: 1.0.0
 */
import type { GetAdminStorageConfiguration200ProvidersItem } from './getAdminStorageConfiguration200ProvidersItem'
import type { GetAdminStorageConfiguration200GlobalSettings } from './getAdminStorageConfiguration200GlobalSettings'

export type GetAdminStorageConfiguration200 = {
  providers: GetAdminStorageConfiguration200ProvidersItem[]
  globalSettings: GetAdminStorageConfiguration200GlobalSettings
}
