/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Pika Complete API
 * Complete API documentation including public, admin, and internal endpoints
 * OpenAPI spec version: 1.0.0
 */

export type GetAdminTransactionById200Type =
  (typeof GetAdminTransactionById200Type)[keyof typeof GetAdminTransactionById200Type]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetAdminTransactionById200Type = {
  payment: 'payment',
  refund: 'refund',
  transfer: 'transfer',
  payout: 'payout',
  adjustment: 'adjustment',
} as const
