/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Pika Complete API
 * Complete API documentation including public, admin, and internal endpoints
 * OpenAPI spec version: 1.0.0
 */

/**
 * Voucher book status
 */
export type GetAdminVoucherBookById200Status =
  (typeof GetAdminVoucherBookById200Status)[keyof typeof GetAdminVoucherBookById200Status]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetAdminVoucherBookById200Status = {
  draft: 'draft',
  ready_for_print: 'ready_for_print',
  published: 'published',
  archived: 'archived',
} as const
