/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Pika Complete API
 * Complete API documentation including public, admin, and internal endpoints
 * OpenAPI spec version: 1.0.0
 */

export type GetAdminFinancialReportsPeriod =
  (typeof GetAdminFinancialReportsPeriod)[keyof typeof GetAdminFinancialReportsPeriod]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetAdminFinancialReportsPeriod = {
  '7d': '7d',
  '30d': '30d',
  '90d': '90d',
  '1y': '1y',
  custom: 'custom',
} as const
