/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * The VoucherBook Complete API
 * Complete API documentation including public, admin, and internal endpoints
 * OpenAPI spec version: 1.0.0
 */

export type GetAdminFinancialReports200ReportType =
  (typeof GetAdminFinancialReports200ReportType)[keyof typeof GetAdminFinancialReports200ReportType]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetAdminFinancialReports200ReportType = {
  revenue: 'revenue',
  transactions: 'transactions',
  payouts: 'payouts',
  disputes: 'disputes',
  summary: 'summary',
} as const
