/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * The VoucherBook Complete API
 * Complete API documentation including public, admin, and internal endpoints
 * OpenAPI spec version: 1.0.0
 */

/**
 * Supported storage provider
 */
export type GetAdminStorageConfiguration200ProvidersItemName =
  (typeof GetAdminStorageConfiguration200ProvidersItemName)[keyof typeof GetAdminStorageConfiguration200ProvidersItemName]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetAdminStorageConfiguration200ProvidersItemName = {
  awsS3: 'awsS3',
  local: 'local',
  minio: 'minio',
} as const
