/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * The VoucherBook Complete API
 * Complete API documentation including public, admin, and internal endpoints
 * OpenAPI spec version: 1.0.0
 */

export type GetAdminFileListFileType =
  (typeof GetAdminFileListFileType)[keyof typeof GetAdminFileListFileType]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetAdminFileListFileType = {
  image: 'image',
  video: 'video',
  document: 'document',
  audio: 'audio',
  other: 'other',
} as const
