/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * The VoucherBook Complete API
 * Complete API documentation including public, admin, and internal endpoints
 * OpenAPI spec version: 1.0.0
 */

export type GetAdminVoucherBookListBookType =
  (typeof GetAdminVoucherBookListBookType)[keyof typeof GetAdminVoucherBookListBookType]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetAdminVoucherBookListBookType = {
  monthly: 'monthly',
  specialEdition: 'specialEdition',
  regional: 'regional',
  seasonal: 'seasonal',
  promotional: 'promotional',
} as const
