/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Pika Complete API
 * Complete API documentation including public, admin, and internal endpoints
 * OpenAPI spec version: 1.0.0
 */

/**
 * Supported storage provider
 */
export type GetAdminFileList200DataItemProvider =
  (typeof GetAdminFileList200DataItemProvider)[keyof typeof GetAdminFileList200DataItemProvider]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetAdminFileList200DataItemProvider = {
  aws_s3: 'aws_s3',
  local: 'local',
  minio: 'minio',
} as const
