/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * The VoucherBook Complete API
 * Complete API documentation including public, admin, and internal endpoints
 * OpenAPI spec version: 1.0.0
 */
import type { GetAdminSupportTicketList200DataItemType } from './getAdminSupportTicketList200DataItemType'
import type { GetAdminSupportTicketList200DataItemStatus } from './getAdminSupportTicketList200DataItemStatus'
import type { GetAdminSupportTicketList200DataItemPriority } from './getAdminSupportTicketList200DataItemPriority'

export type GetAdminSupportTicketList200DataItem = {
  /** Universally Unique Identifier */
  id: string
  ticketNumber?: string
  userId: string
  userName: string
  userEmail: string
  title: string
  description: string
  /** Support ticket category/type */
  type: GetAdminSupportTicketList200DataItemType
  /** Support ticket status */
  status: GetAdminSupportTicketList200DataItemStatus
  /** Support ticket priority level */
  priority: GetAdminSupportTicketList200DataItemPriority
  /** ISO 8601 datetime with timezone */
  resolvedAt?: string
  assignedTo?: string
  assignedToName?: string
  files?: string[]
  /** When the record was created */
  createdAt: string
  /** When the record was last updated */
  updatedAt: string
}
