/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Pika Complete API
 * Complete API documentation including public, admin, and internal endpoints
 * OpenAPI spec version: 1.0.0
 */
import type { GetAdminVoucherTranslations200TranslationsTitle } from './getAdminVoucherTranslations200TranslationsTitle'
import type { GetAdminVoucherTranslations200TranslationsDescription } from './getAdminVoucherTranslations200TranslationsDescription'
import type { GetAdminVoucherTranslations200TranslationsTerms } from './getAdminVoucherTranslations200TranslationsTerms'

export type GetAdminVoucherTranslations200Translations = {
  title: GetAdminVoucherTranslations200TranslationsTitle
  description: GetAdminVoucherTranslations200TranslationsDescription
  terms: GetAdminVoucherTranslations200TranslationsTerms
}
