/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * The VoucherBook Complete API
 * Complete API documentation including public, admin, and internal endpoints
 * OpenAPI spec version: 1.0.0
 */

export type GetAdminTransactionList200DataItemDisputeStatus =
  (typeof GetAdminTransactionList200DataItemDisputeStatus)[keyof typeof GetAdminTransactionList200DataItemDisputeStatus]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetAdminTransactionList200DataItemDisputeStatus = {
  warning: 'warning',
  needsResponse: 'needsResponse',
  underReview: 'underReview',
  won: 'won',
  lost: 'lost',
} as const
