/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Pika Complete API
 * Complete API documentation including public, admin, and internal endpoints
 * OpenAPI spec version: 1.0.0
 */

export type GetAdminBusinessVoucherStatsGroupBy =
  (typeof GetAdminBusinessVoucherStatsGroupBy)[keyof typeof GetAdminBusinessVoucherStatsGroupBy]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetAdminBusinessVoucherStatsGroupBy = {
  day: 'day',
  week: 'week',
  month: 'month',
} as const
