/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * The VoucherBook Complete API
 * Complete API documentation including public, admin, and internal endpoints
 * OpenAPI spec version: 1.0.0
 */

export type GetAdminTransactionListType =
  (typeof GetAdminTransactionListType)[keyof typeof GetAdminTransactionListType]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetAdminTransactionListType = {
  payment: 'payment',
  refund: 'refund',
  transfer: 'transfer',
  payout: 'payout',
  adjustment: 'adjustment',
} as const
