/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Pika Complete API
 * Complete API documentation including public, admin, and internal endpoints
 * OpenAPI spec version: 1.0.0
 */

/**
 * User role in the system
 */
export type GetAdminUserById200Role =
  (typeof GetAdminUserById200Role)[keyof typeof GetAdminUserById200Role]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetAdminUserById200Role = {
  admin: 'admin',
  customer: 'customer',
  business: 'business',
} as const
