/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Pika Complete API
 * Complete API documentation including public, admin, and internal endpoints
 * OpenAPI spec version: 1.0.0
 */

export type GetAdminTransactionList200DataItemPaymentMethod =
  (typeof GetAdminTransactionList200DataItemPaymentMethod)[keyof typeof GetAdminTransactionList200DataItemPaymentMethod]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetAdminTransactionList200DataItemPaymentMethod = {
  card: 'card',
  bankTransfer: 'bankTransfer',
  wallet: 'wallet',
  cash: 'cash',
} as const
