/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Pika Complete API
 * Complete API documentation including public, admin, and internal endpoints
 * OpenAPI spec version: 1.0.0
 */
import type { GetAdminVoucherList200DataItemScansItemUserId } from './getAdminVoucherList200DataItemScansItemUserId'
import type { VoucherScanType } from './voucherScanType'
import type { VoucherScanSource } from './voucherScanSource'
import type { GetAdminVoucherList200DataItemScansItemLocation } from './getAdminVoucherList200DataItemScansItemLocation'
import type { GetAdminVoucherList200DataItemScansItemDeviceInfo } from './getAdminVoucherList200DataItemScansItemDeviceInfo'

export type GetAdminVoucherList200DataItemScansItem = {
  /** Universally Unique Identifier */
  id: string
  /** Universally Unique Identifier */
  userId: GetAdminVoucherList200DataItemScansItemUserId
  scanType: VoucherScanType
  scanSource: VoucherScanSource
  location: GetAdminVoucherList200DataItemScansItemLocation
  deviceInfo: GetAdminVoucherList200DataItemScansItemDeviceInfo
  /** ISO 8601 datetime with timezone */
  scannedAt: string
  /** ISO 8601 datetime with timezone */
  createdAt: string
}
