/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * The VoucherBook Complete API
 * Complete API documentation including public, admin, and internal endpoints
 * OpenAPI spec version: 1.0.0
 */
import type { GetAdminSupportTicketListStatus } from './getAdminSupportTicketListStatus'
import type { GetAdminSupportTicketListPriority } from './getAdminSupportTicketListPriority'
import type { GetAdminSupportTicketListType } from './getAdminSupportTicketListType'
import type { GetAdminSupportTicketListSortBy } from './getAdminSupportTicketListSortBy'
import type { GetAdminSupportTicketListSortOrder } from './getAdminSupportTicketListSortOrder'

export type GetAdminSupportTicketListParams = {
  /**
   * Search in title, description
   */
  search?: string
  ticketNumber?: string
  userId?: string
  assignedTo?: string
  /**
   * Support ticket status
   */
  status?: GetAdminSupportTicketListStatus
  /**
   * Support ticket priority level
   */
  priority?: GetAdminSupportTicketListPriority
  /**
   * Support ticket category/type
   */
  type?: GetAdminSupportTicketListType
  /**
   */
  page?: number
  /**
   * @maximum 100
   */
  limit?: number
  /**
   * Field to sort admin tickets by
   */
  sortBy?: GetAdminSupportTicketListSortBy
  /**
   * Sort order - ascending (asc) or descending (desc)
   */
  sortOrder?: GetAdminSupportTicketListSortOrder
  /**
   * Comma-separated relations: user,assignedUser
   */
  include?: string
}
