/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Pika Complete API
 * Complete API documentation including public, admin, and internal endpoints
 * OpenAPI spec version: 1.0.0
 */

export type GetAdminBusinessListSortBy =
  (typeof GetAdminBusinessListSortBy)[keyof typeof GetAdminBusinessListSortBy]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetAdminBusinessListSortBy = {
  businessName: 'businessName',
  avgRating: 'avgRating',
  verified: 'verified',
  active: 'active',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
} as const
