/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Pika Complete API
 * Complete API documentation including public, admin, and internal endpoints
 * OpenAPI spec version: 1.0.0
 */

export type GetAdminVoucherById200LocationAnyOfType =
  (typeof GetAdminVoucherById200LocationAnyOfType)[keyof typeof GetAdminVoucherById200LocationAnyOfType]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetAdminVoucherById200LocationAnyOfType = {
  Point: 'Point',
} as const
