/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * The VoucherBook Complete API
 * Complete API documentation including public, admin, and internal endpoints
 * OpenAPI spec version: 1.0.0
 */
import type { GetAdminVoucherBookListSortBy } from './getAdminVoucherBookListSortBy'
import type { GetAdminVoucherBookListSortOrder } from './getAdminVoucherBookListSortOrder'
import type { GetAdminVoucherBookListBookType } from './getAdminVoucherBookListBookType'
import type { GetAdminVoucherBookListStatus } from './getAdminVoucherBookListStatus'

export type GetAdminVoucherBookListParams = {
  /**
   * Page number
   */
  page?: number
  /**
   * Items per page
   * @maximum 100
   */
  limit?: number
  /**
   * Field to sort voucher books by
   */
  sortBy?: GetAdminVoucherBookListSortBy
  /**
   * Sort order
   */
  sortOrder?: GetAdminVoucherBookListSortOrder
  /**
   * Search query
   */
  search?: string
  /**
   * Voucher book type
   */
  bookType?: GetAdminVoucherBookListBookType
  /**
   * Voucher book status
   */
  status?: GetAdminVoucherBookListStatus
  /**
   * Filter by year
   * @minimum 2020
   * @maximum 2100
   */
  year?: number
  /**
   * Filter by month
   * @minimum 1
   * @maximum 12
   */
  month?: number
  /**
   * Filter by creator
   */
  createdBy?: string
  /**
   * Filter by last updater
   */
  updatedBy?: string
  /**
   * Filter books with/without content
   */
  hasContent?: boolean
  /**
   * Filter books with/without generated PDF
   */
  hasPdf?: boolean
}
