/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Pika Complete API
 * Complete API documentation including public, admin, and internal endpoints
 * OpenAPI spec version: 1.0.0
 */

export type GetAdminTransactionList200DataItemStatus =
  (typeof GetAdminTransactionList200DataItemStatus)[keyof typeof GetAdminTransactionList200DataItemStatus]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetAdminTransactionList200DataItemStatus = {
  pending: 'pending',
  processing: 'processing',
  completed: 'completed',
  failed: 'failed',
  cancelled: 'cancelled',
} as const
