/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Pika Complete API
 * Complete API documentation including public, admin, and internal endpoints
 * OpenAPI spec version: 1.0.0
 */
import type { GetAdminTransactionListSortOrder } from './getAdminTransactionListSortOrder'
import type { GetAdminTransactionListType } from './getAdminTransactionListType'
import type { GetAdminTransactionListStatus } from './getAdminTransactionListStatus'
import type { GetAdminTransactionListPaymentMethod } from './getAdminTransactionListPaymentMethod'

export type GetAdminTransactionListParams = {
  /**
   * Page number
   */
  page?: number
  /**
   * Items per page
   * @maximum 100
   */
  limit?: number
  /**
   * Field to sort by
   */
  sortBy?: string
  /**
   * Sort order
   */
  sortOrder?: GetAdminTransactionListSortOrder
  /**
   * Search query
   */
  search?: string
  /**
   * Start date (ISO 8601)
   */
  fromDate?: string
  /**
   * End date (ISO 8601)
   */
  toDate?: string
  type?: GetAdminTransactionListType
  status?: GetAdminTransactionListStatus
  paymentMethod?: GetAdminTransactionListPaymentMethod
  userId?: string
  /**
   * Universally Unique Identifier
   */
  businessId?: string
  stripePaymentIntentId?: string
  /**
   * @minimum 0
   */
  minAmount?: number
  /**
   * @minimum 0
   */
  maxAmount?: number
  /**
   * @minLength 3
   * @maxLength 3
   */
  currency?: string
  hasDispute?: boolean
}
