/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Pika Complete API
 * Complete API documentation including public, admin, and internal endpoints
 * OpenAPI spec version: 1.0.0
 */
import type { GetAdminCategoryById404DetailsItem } from './getAdminCategoryById404DetailsItem'

/**
 * Standard error response
 */
export type GetAdminCategoryById404 = {
  /**
   * @minimum 100
   * @maximum 599
   */
  statusCode: number
  error: string
  message: string
  details?: GetAdminCategoryById404DetailsItem[]
  /** Request correlation ID */
  correlationId?: string
  /** ISO 8601 datetime with timezone */
  timestamp?: string
}
