/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Pika Complete API
 * Complete API documentation including public, admin, and internal endpoints
 * OpenAPI spec version: 1.0.0
 */
import type { GetBusinessesByCategoryRequestSortOrder } from './getBusinessesByCategoryRequestSortOrder'

/**
 * Query parameters for getting businesses in a specific category
 */
export interface GetBusinessesByCategoryRequest {
  /**
   * Page number
   */
  page?: number
  /**
   * Items per page
   * @maximum 100
   */
  limit?: number
  /** Field to sort by */
  sortBy?: string
  /** Sort order */
  sortOrder?: GetBusinessesByCategoryRequestSortOrder
  /** Search query */
  search?: string
  onlyActive?: boolean
  onlyVerified?: boolean
  /** Comma-separated relations: user,category */
  include?: string
}
