/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Pika Complete API
 * Complete API documentation including public, admin, and internal endpoints
 * OpenAPI spec version: 1.0.0
 */

/**
 * Business owner profile when ?include=user
 */
export type GetBusinessList200DataItemUser = {
  id: string
  /** @maxLength 50 */
  firstName: string
  /** @maxLength 50 */
  lastName: string
  /** @maxLength 100 */
  displayName?: string
  avatarUrl?: string
  /** @maxLength 500 */
  bio?: string
  /** ISO 8601 datetime with timezone */
  createdAt: string
}
