/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Pika Complete API
 * Complete API documentation including public, admin, and internal endpoints
 * OpenAPI spec version: 1.0.0
 */
import type { GetBusinessRegistrationProgress200Step1Data } from './getBusinessRegistrationProgress200Step1Data'
import type { GetBusinessRegistrationProgress200Step2Data } from './getBusinessRegistrationProgress200Step2Data'
import type { GetBusinessRegistrationProgress200Step3Data } from './getBusinessRegistrationProgress200Step3Data'
import type { GetBusinessRegistrationProgress200RegistrationStatus } from './getBusinessRegistrationProgress200RegistrationStatus'

export type GetBusinessRegistrationProgress200 = {
  /** Registration ID */
  id: string
  /** User ID */
  userId: string
  /** Current step number */
  currentStep: number
  /** List of completed step numbers */
  stepsCompleted: number[]
  step1Data?: GetBusinessRegistrationProgress200Step1Data
  step2Data?: GetBusinessRegistrationProgress200Step2Data
  step3Data?: GetBusinessRegistrationProgress200Step3Data
  /** Current registration status */
  registrationStatus: GetBusinessRegistrationProgress200RegistrationStatus
  /** Business ID if created */
  businessId?: string
  /** When the record was created */
  createdAt: string
  /** When the record was last updated */
  updatedAt: string
}
