/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * The VoucherBook Complete API
 * Complete API documentation including public, admin, and internal endpoints
 * OpenAPI spec version: 1.0.0
 */

export type GetBusinessListSortBy =
  (typeof GetBusinessListSortBy)[keyof typeof GetBusinessListSortBy]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetBusinessListSortBy = {
  businessName: 'businessName',
  avgRating: 'avgRating',
  verified: 'verified',
  active: 'active',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
} as const
