/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * The VoucherBook Complete API
 * Complete API documentation including public, admin, and internal endpoints
 * OpenAPI spec version: 1.0.0
 */

/**
 * Current registration status
 */
export type GetBusinessRegistrationStatus200RegistrationStatus =
  (typeof GetBusinessRegistrationStatus200RegistrationStatus)[keyof typeof GetBusinessRegistrationStatus200RegistrationStatus]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetBusinessRegistrationStatus200RegistrationStatus = {
  in_progress: 'in_progress',
  submitted: 'submitted',
  approved: 'approved',
  rejected: 'rejected',
} as const
