/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Pika Complete API
 * Complete API documentation including public, admin, and internal endpoints
 * OpenAPI spec version: 1.0.0
 */
import type { GetBusinessesByUserResponseBusinessesItem } from './getBusinessesByUserResponseBusinessesItem'

/**
 * User businesses data
 */
export interface GetBusinessesByUserResponse {
  businesses: GetBusinessesByUserResponseBusinessesItem[]
  /** @minimum 0 */
  totalCount: number
}
