/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * The VoucherBook Complete API
 * Complete API documentation including public, admin, and internal endpoints
 * OpenAPI spec version: 1.0.0
 */
import type { VoucherCodeType } from './voucherCodeType'
import type { GetFavoriteVouchersResponseDataItemVoucherCodesItemMetadata } from './getFavoriteVouchersResponseDataItemVoucherCodesItemMetadata'

export type GetFavoriteVouchersResponseDataItemVoucherCodesItem = {
  /** Universally Unique Identifier */
  id: string
  code: string
  type: VoucherCodeType
  isActive: boolean
  metadata?: GetFavoriteVouchersResponseDataItemVoucherCodesItemMetadata
}
