/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Pika Complete API
 * Complete API documentation including public, admin, and internal endpoints
 * OpenAPI spec version: 1.0.0
 */
import type { GetFileHistoryQuerySortBy } from './getFileHistoryQuerySortBy'
import type { GetFileHistoryQuerySortOrder } from './getFileHistoryQuerySortOrder'

export interface GetFileHistoryQuery {
  status?: string
  folder?: string
  contentType?: string
  provider?: string
  /** ISO 8601 datetime with timezone */
  fromDate?: string
  /** ISO 8601 datetime with timezone */
  toDate?: string
  /** */
  page?: number
  /**
   * @maximum 100
   */
  limit?: number
  /** Field to sort files by */
  sortBy?: GetFileHistoryQuerySortBy
  sortOrder?: GetFileHistoryQuerySortOrder
}
