/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Pika Complete API
 * Complete API documentation including public, admin, and internal endpoints
 * OpenAPI spec version: 1.0.0
 */
import type { GetFileHistory200DataItemFileType } from './getFileHistory200DataItemFileType'
import type { GetFileHistory200DataItemStatus } from './getFileHistory200DataItemStatus'
import type { GetFileHistory200DataItemProvider } from './getFileHistory200DataItemProvider'
import type { GetFileHistory200DataItemMetadata } from './getFileHistory200DataItemMetadata'

export type GetFileHistory200DataItem = {
  /** Universally Unique Identifier */
  id: string
  userId: string
  /** Storage key/path */
  fileKey: string
  fileName: string
  /**
   * Size in bytes
   */
  fileSize: number
  mimeType: string
  /** File type category */
  fileType: GetFileHistory200DataItemFileType
  /** File processing status */
  status: GetFileHistory200DataItemStatus
  /** Supported storage provider */
  provider: GetFileHistory200DataItemProvider
  bucketName?: string
  region?: string
  /** ISO 8601 datetime with timezone */
  uploadedAt?: string
  /** ISO 8601 datetime with timezone */
  deletedAt?: string
  metadata?: GetFileHistory200DataItemMetadata
  error?: string
  /** When the record was created */
  createdAt: string
  /** When the record was last updated */
  updatedAt: string
}
