/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * The VoucherBook Complete API
 * Complete API documentation including public, admin, and internal endpoints
 * OpenAPI spec version: 1.0.0
 */
import type { GetFavoriteVouchersResponseDataItemCreatedAt } from './getFavoriteVouchersResponseDataItemCreatedAt'
import type { GetFavoriteVouchersResponseDataItemVoucher } from './getFavoriteVouchersResponseDataItemVoucher'

export type GetFavoriteVouchersResponseDataItem = {
  /** Favorite record ID */
  id: string
  /** Voucher ID */
  voucherId: string
  /** When the voucher was favorited */
  createdAt: GetFavoriteVouchersResponseDataItemCreatedAt
  /** Full voucher details when ?include=voucher */
  voucher?: GetFavoriteVouchersResponseDataItemVoucher
}
