/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Pika Complete API
 * Complete API documentation including public, admin, and internal endpoints
 * OpenAPI spec version: 1.0.0
 */

/**
 * Supported storage provider
 */
export type GetFileHistory200DataItemProvider =
  (typeof GetFileHistory200DataItemProvider)[keyof typeof GetFileHistory200DataItemProvider]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetFileHistory200DataItemProvider = {
  awsS3: 'awsS3',
  local: 'local',
  minio: 'minio',
} as const
