/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Pika Complete API
 * Complete API documentation including public, admin, and internal endpoints
 * OpenAPI spec version: 1.0.0
 */
import type { GetFavoriteBusinessesQuerySortBy } from './getFavoriteBusinessesQuerySortBy'
import type { GetFavoriteBusinessesQuerySortOrder } from './getFavoriteBusinessesQuerySortOrder'

/**
 * Query parameters for listing favorite businesses
 */
export interface GetFavoriteBusinessesQuery {
  /**
   * Page number
   */
  page?: number
  /**
   * Items per page
   * @maximum 100
   */
  limit?: number
  /** Field to sort by */
  sortBy?: GetFavoriteBusinessesQuerySortBy
  /** Sort order */
  sortOrder?: GetFavoriteBusinessesQuerySortOrder
  /** Search query */
  search?: string
  /** Include related data: business,category,businessDetails */
  include?: string
}
