/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * The VoucherBook Complete API
 * Complete API documentation including public, admin, and internal endpoints
 * OpenAPI spec version: 1.0.0
 */
import type { GetInternalBusinessesByCategorySortOrder } from './getInternalBusinessesByCategorySortOrder'

export type GetInternalBusinessesByCategoryParams = {
  /**
   * Page number
   */
  page?: number
  /**
   * Items per page
   * @maximum 100
   */
  limit?: number
  /**
   * Field to sort by
   */
  sortBy?: string
  /**
   * Sort order
   */
  sortOrder?: GetInternalBusinessesByCategorySortOrder
  /**
   * Search query
   */
  search?: string
  onlyActive?: boolean
  onlyVerified?: boolean
  /**
   * Comma-separated relations: user,category,businessDetails
   */
  include?: string
}
