/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * The VoucherBook Complete API
 * Complete API documentation including public, admin, and internal endpoints
 * OpenAPI spec version: 1.0.0
 */

/**
 * User role in the system
 */
export type GetInternalUserById200Role =
  (typeof GetInternalUserById200Role)[keyof typeof GetInternalUserById200Role]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetInternalUserById200Role = {
  admin: 'admin',
  customer: 'customer',
  business: 'business',
} as const
