/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * The VoucherBook Complete API
 * Complete API documentation including public, admin, and internal endpoints
 * OpenAPI spec version: 1.0.0
 */
import type { GetInternalUserFilesBodyFileType } from './getInternalUserFilesBodyFileType'
import type { GetInternalUserFilesBodyStatus } from './getInternalUserFilesBodyStatus'

/**
 * Get files for a specific user
 */
export type GetInternalUserFilesBody = {
  userId: string
  /** File type category */
  fileType?: GetInternalUserFilesBodyFileType
  /** File processing status */
  status?: GetInternalUserFilesBodyStatus
  /**
   * @maximum 1000
   */
  limit?: number
  /** @minimum 0 */
  offset?: number
}
