/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Pika Complete API
 * Complete API documentation including public, admin, and internal endpoints
 * OpenAPI spec version: 1.0.0
 */
import type { GetInternalServiceEndpoints200InstancesItem } from './getInternalServiceEndpoints200InstancesItem'
import type { GetInternalServiceEndpoints200LoadBalancingStrategy } from './getInternalServiceEndpoints200LoadBalancingStrategy'

/**
 * Available endpoints for a service
 */
export type GetInternalServiceEndpoints200 = {
  serviceName: string
  instances: GetInternalServiceEndpoints200InstancesItem[]
  loadBalancingStrategy?: GetInternalServiceEndpoints200LoadBalancingStrategy
}
