/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * The VoucherBook Complete API
 * Complete API documentation including public, admin, and internal endpoints
 * OpenAPI spec version: 1.0.0
 */

/**
 * File type category
 */
export type GetInternalUserFiles200ItemFileType =
  (typeof GetInternalUserFiles200ItemFileType)[keyof typeof GetInternalUserFiles200ItemFileType]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetInternalUserFiles200ItemFileType = {
  image: 'image',
  video: 'video',
  document: 'document',
  audio: 'audio',
  other: 'other',
} as const
