/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Pika Complete API
 * Complete API documentation including public, admin, and internal endpoints
 * OpenAPI spec version: 1.0.0
 */
import type { GetInternalServiceEndpoints200InstancesItemEndpointsItemProtocol } from './getInternalServiceEndpoints200InstancesItemEndpointsItemProtocol'

export type GetInternalServiceEndpoints200InstancesItemEndpointsItem = {
  protocol: GetInternalServiceEndpoints200InstancesItemEndpointsItemProtocol
  host: string
  /** */
  port: number
  path?: string
  healthCheckPath?: string
}
