/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * The VoucherBook Complete API
 * Complete API documentation including public, admin, and internal endpoints
 * OpenAPI spec version: 1.0.0
 */

/**
 * System health status
 */
export type GetInternalStorageHealth200ProvidersStatusLocal =
  (typeof GetInternalStorageHealth200ProvidersStatusLocal)[keyof typeof GetInternalStorageHealth200ProvidersStatusLocal]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetInternalStorageHealth200ProvidersStatusLocal = {
  healthy: 'healthy',
  degraded: 'degraded',
  unhealthy: 'unhealthy',
} as const
