/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Pika Complete API
 * Complete API documentation including public, admin, and internal endpoints
 * OpenAPI spec version: 1.0.0
 */

export type GetInternalServiceEndpoints200LoadBalancingStrategy =
  (typeof GetInternalServiceEndpoints200LoadBalancingStrategy)[keyof typeof GetInternalServiceEndpoints200LoadBalancingStrategy]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetInternalServiceEndpoints200LoadBalancingStrategy = {
  ROUND_ROBIN: 'ROUND_ROBIN',
  LEAST_CONNECTIONS: 'LEAST_CONNECTIONS',
  WEIGHTED: 'WEIGHTED',
} as const
