/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Pika Complete API
 * Complete API documentation including public, admin, and internal endpoints
 * OpenAPI spec version: 1.0.0
 */
import type { GetInternalFileById200FileType } from './getInternalFileById200FileType'
import type { GetInternalFileById200Status } from './getInternalFileById200Status'
import type { GetInternalFileById200Provider } from './getInternalFileById200Provider'
import type { GetInternalFileById200Metadata } from './getInternalFileById200Metadata'

/**
 * Internal file response
 */
export type GetInternalFileById200 = {
  /** Universally Unique Identifier */
  id: string
  userId: string
  fileKey: string
  fileName: string
  /** */
  fileSize: number
  mimeType: string
  /** File type category */
  fileType: GetInternalFileById200FileType
  /** File processing status */
  status: GetInternalFileById200Status
  /** Supported storage provider */
  provider: GetInternalFileById200Provider
  bucketName?: string
  region?: string
  isPublic: boolean
  metadata?: GetInternalFileById200Metadata
  /** ISO 8601 datetime with timezone */
  uploadedAt?: string
  /** ISO 8601 datetime with timezone */
  createdAt: string
  /** ISO 8601 datetime with timezone */
  updatedAt: string
}
