/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * The VoucherBook Complete API
 * Complete API documentation including public, admin, and internal endpoints
 * OpenAPI spec version: 1.0.0
 */

/**
 * Auth user details
 */
export type GetInternalUserByEmail200 = {
  id: string
  /** @minLength 1 */
  email: string
  emailVerified: boolean
  roles: string[]
  active: boolean
  /** ISO 8601 datetime with timezone */
  lastLoginAt?: string
  /** ISO 8601 datetime with timezone */
  createdAt: string
}
