/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Pika Complete API
 * Complete API documentation including public, admin, and internal endpoints
 * OpenAPI spec version: 1.0.0
 */
import type { GetInternalServiceRegistry200ServicesItemServiceType } from './getInternalServiceRegistry200ServicesItemServiceType'
import type { GetInternalServiceRegistry200ServicesItemEndpointsItem } from './getInternalServiceRegistry200ServicesItemEndpointsItem'
import type { GetInternalServiceRegistry200ServicesItemEnvironment } from './getInternalServiceRegistry200ServicesItemEnvironment'
import type { GetInternalServiceRegistry200ServicesItemStatus } from './getInternalServiceRegistry200ServicesItemStatus'
import type { GetInternalServiceRegistry200ServicesItemMetadata } from './getInternalServiceRegistry200ServicesItemMetadata'
import type { GetInternalServiceRegistry200ServicesItemMetrics } from './getInternalServiceRegistry200ServicesItemMetrics'

/**
 * Service instance in the registry
 */
export type GetInternalServiceRegistry200ServicesItem = {
  /** Universally Unique Identifier */
  id: string
  /**
   * @minLength 1
   * @maxLength 100
   */
  serviceName: string
  serviceType: GetInternalServiceRegistry200ServicesItemServiceType
  /** @pattern ^\d+\.\d+\.\d+$ */
  version: string
  /** @minLength 1 */
  instanceId: string
  /** @minItems 1 */
  endpoints: GetInternalServiceRegistry200ServicesItemEndpointsItem[]
  environment: GetInternalServiceRegistry200ServicesItemEnvironment
  region?: string
  availabilityZone?: string
  status: GetInternalServiceRegistry200ServicesItemStatus
  /** ISO 8601 datetime with timezone */
  lastHealthCheck?: string
  healthCheckUrl?: string
  metadata?: GetInternalServiceRegistry200ServicesItemMetadata
  tags?: string[]
  metrics?: GetInternalServiceRegistry200ServicesItemMetrics
  registeredBy?: string
  /** ISO 8601 datetime with timezone */
  lastSeen: string
  /** */
  ttl?: number
  /** When the record was created */
  createdAt: string
  /** When the record was last updated */
  updatedAt: string
}
