/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Pika Complete API
 * Complete API documentation including public, admin, and internal endpoints
 * OpenAPI spec version: 1.0.0
 */

export type GetInternalServiceRegistry200ServicesItemStatus =
  (typeof GetInternalServiceRegistry200ServicesItemStatus)[keyof typeof GetInternalServiceRegistry200ServicesItemStatus]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetInternalServiceRegistry200ServicesItemStatus = {
  starting: 'starting',
  healthy: 'healthy',
  degraded: 'degraded',
  unhealthy: 'unhealthy',
  stopped: 'stopped',
} as const
