/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * The VoucherBook Complete API
 * Complete API documentation including public, admin, and internal endpoints
 * OpenAPI spec version: 1.0.0
 */
import type { GetLinkedAccounts200LinkedAccountsItem } from './getLinkedAccounts200LinkedAccountsItem'

/**
 * List of linked social accounts
 */
export type GetLinkedAccounts200 = {
  /** List of linked social accounts with details */
  linkedAccounts: GetLinkedAccounts200LinkedAccountsItem[]
}
