/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Pika Complete API
 * Complete API documentation including public, admin, and internal endpoints
 * OpenAPI spec version: 1.0.0
 */

export type GetPromoCodesStatus =
  (typeof GetPromoCodesStatus)[keyof typeof GetPromoCodesStatus]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetPromoCodesStatus = {
  active: 'active',
  expired: 'expired',
  depleted: 'depleted',
  disabled: 'disabled',
} as const
