/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * The VoucherBook Complete API
 * Complete API documentation including public, admin, and internal endpoints
 * OpenAPI spec version: 1.0.0
 */
import type { GetSubscriptionsPlansSortOrder } from './getSubscriptionsPlansSortOrder'
import type { GetSubscriptionsPlansBillingInterval } from './getSubscriptionsPlansBillingInterval'

export type GetSubscriptionsPlansParams = {
  /**
   * Page number
   */
  page?: number
  /**
   * Items per page
   * @maximum 100
   */
  limit?: number
  /**
   * Field to sort by
   */
  sortBy?: string
  /**
   * Sort order
   */
  sortOrder?: GetSubscriptionsPlansSortOrder
  /**
   * Search query
   */
  search?: string
  billingInterval?: GetSubscriptionsPlansBillingInterval
  isActive?: boolean
  isPublic?: boolean
  /**
   * @minimum 0
   */
  minPrice?: number
  /**
   * @minimum 0
   */
  maxPrice?: number
  createdBy?: string
}
