/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Pika Complete API
 * Complete API documentation including public, admin, and internal endpoints
 * OpenAPI spec version: 1.0.0
 */

export type GetSubscriptionsPlansBillingInterval =
  (typeof GetSubscriptionsPlansBillingInterval)[keyof typeof GetSubscriptionsPlansBillingInterval]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetSubscriptionsPlansBillingInterval = {
  day: 'day',
  week: 'week',
  month: 'month',
  year: 'year',
} as const
