/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Pika Complete API
 * Complete API documentation including public, admin, and internal endpoints
 * OpenAPI spec version: 1.0.0
 */

export type GetSubscriptionsPlansSortOrder =
  (typeof GetSubscriptionsPlansSortOrder)[keyof typeof GetSubscriptionsPlansSortOrder]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetSubscriptionsPlansSortOrder = {
  asc: 'asc',
  desc: 'desc',
} as const
