/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Pika Complete API
 * Complete API documentation including public, admin, and internal endpoints
 * OpenAPI spec version: 1.0.0
 */
import type { GetSubscriptions200DataItem } from './getSubscriptions200DataItem'
import type { GetSubscriptions200Pagination } from './getSubscriptions200Pagination'

export type GetSubscriptions200 = {
  data: GetSubscriptions200DataItem[]
  pagination: GetSubscriptions200Pagination
}
