/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Pika Complete API
 * Complete API documentation including public, admin, and internal endpoints
 * OpenAPI spec version: 1.0.0
 */

/**
 * Pagination information
 */
export type GetUserVouchers200Pagination = {
  /**
   * Current page number
   */
  page: number
  /**
   * Items per page
   * @maximum 100
   */
  limit: number
  /**
   * Total number of items
   * @minimum 0
   */
  total: number
  /**
   * Total number of pages
   * @minimum 0
   */
  totalPages: number
  /** Whether there is a next page */
  hasNext: boolean
  /** Whether there is a previous page */
  hasPrev: boolean
}
