/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Pika Complete API
 * Complete API documentation including public, admin, and internal endpoints
 * OpenAPI spec version: 1.0.0
 */
import type { GetUserSupportProblems200DataItemStatus } from './getUserSupportProblems200DataItemStatus'
import type { GetUserSupportProblems200DataItemPriority } from './getUserSupportProblems200DataItemPriority'
import type { GetUserSupportProblems200DataItemType } from './getUserSupportProblems200DataItemType'

/**
 * Support problem
 */
export type GetUserSupportProblems200DataItem = {
  /** Universally Unique Identifier */
  id: string
  ticketNumber?: string
  userId: string
  title: string
  description: string
  /** Support ticket status */
  status: GetUserSupportProblems200DataItemStatus
  /** Support ticket priority level */
  priority: GetUserSupportProblems200DataItemPriority
  /** Support ticket category/type */
  type: GetUserSupportProblems200DataItemType
  /** ISO 8601 datetime with timezone */
  resolvedAt?: string
  assignedTo?: string
  files?: string[]
  /** When the record was created */
  createdAt: string
  /** When the record was last updated */
  updatedAt: string
}
