/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * The VoucherBook Complete API
 * Complete API documentation including public, admin, and internal endpoints
 * OpenAPI spec version: 1.0.0
 */
import type { GetUserSettings200SettingsPrivacyProfileVisibility } from './getUserSettings200SettingsPrivacyProfileVisibility'

export type GetUserSettings200SettingsPrivacyProfile = {
  visibility: GetUserSettings200SettingsPrivacyProfileVisibility
  showEmail: boolean
  showPhone: boolean
  showBirthDate: boolean
}
