/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * The VoucherBook Complete API
 * Complete API documentation including public, admin, and internal endpoints
 * OpenAPI spec version: 1.0.0
 */

/**
 * User account status
 */
export type GetUserProfile200Status =
  (typeof GetUserProfile200Status)[keyof typeof GetUserProfile200Status]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetUserProfile200Status = {
  active: 'active',
  suspended: 'suspended',
  banned: 'banned',
  unconfirmed: 'unconfirmed',
} as const
