/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * The VoucherBook Complete API
 * Complete API documentation including public, admin, and internal endpoints
 * OpenAPI spec version: 1.0.0
 */

/**
 * Get user auth data by email for authentication
 */
export interface GetUserAuthDataByEmailRequest {
  /** @minLength 1 */
  email: string
}
