/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * The VoucherBook Complete API
 * Complete API documentation including public, admin, and internal endpoints
 * OpenAPI spec version: 1.0.0
 */
import type { GetUserSettings200Settings } from './getUserSettings200Settings'

/**
 * Current user settings
 */
export type GetUserSettings200 = {
  settings: GetUserSettings200Settings
}
