/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Pika Complete API
 * Complete API documentation including public, admin, and internal endpoints
 * OpenAPI spec version: 1.0.0
 */

/**
 * File processing status
 */
export type GetUserFilesRequestStatus =
  (typeof GetUserFilesRequestStatus)[keyof typeof GetUserFilesRequestStatus]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetUserFilesRequestStatus = {
  pending: 'pending',
  uploaded: 'uploaded',
  processing: 'processing',
  processed: 'processed',
  failed: 'failed',
  deleted: 'deleted',
} as const
