/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * The VoucherBook Complete API
 * Complete API documentation including public, admin, and internal endpoints
 * OpenAPI spec version: 1.0.0
 */
import type { GetUserSettingsResponseSettingsNotificationsEmail } from './getUserSettingsResponseSettingsNotificationsEmail'
import type { GetUserSettingsResponseSettingsNotificationsPush } from './getUserSettingsResponseSettingsNotificationsPush'
import type { GetUserSettingsResponseSettingsNotificationsSms } from './getUserSettingsResponseSettingsNotificationsSms'
import type { GetUserSettingsResponseSettingsNotificationsInApp } from './getUserSettingsResponseSettingsNotificationsInApp'

export type GetUserSettingsResponseSettingsNotifications = {
  email: GetUserSettingsResponseSettingsNotificationsEmail
  push: GetUserSettingsResponseSettingsNotificationsPush
  sms: GetUserSettingsResponseSettingsNotificationsSms
  inApp: GetUserSettingsResponseSettingsNotificationsInApp
}
