/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * The VoucherBook Complete API
 * Complete API documentation including public, admin, and internal endpoints
 * OpenAPI spec version: 1.0.0
 */

export type GetUserSettings200SettingsDisplayTheme =
  (typeof GetUserSettings200SettingsDisplayTheme)[keyof typeof GetUserSettings200SettingsDisplayTheme]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetUserSettings200SettingsDisplayTheme = {
  light: 'light',
  dark: 'dark',
  system: 'system',
} as const
