/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * The VoucherBook Complete API
 * Complete API documentation including public, admin, and internal endpoints
 * OpenAPI spec version: 1.0.0
 */
import type { GetUserSettingsResponseSettingsBusinessDashboard } from './getUserSettingsResponseSettingsBusinessDashboard'
import type { GetUserSettingsResponseSettingsBusinessVouchers } from './getUserSettingsResponseSettingsBusinessVouchers'
import type { GetUserSettingsResponseSettingsBusinessNotifications } from './getUserSettingsResponseSettingsBusinessNotifications'

export type GetUserSettingsResponseSettingsBusiness = {
  dashboard: GetUserSettingsResponseSettingsBusinessDashboard
  vouchers: GetUserSettingsResponseSettingsBusinessVouchers
  notifications: GetUserSettingsResponseSettingsBusinessNotifications
}
