/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Pika Complete API
 * Complete API documentation including public, admin, and internal endpoints
 * OpenAPI spec version: 1.0.0
 */
import type { GetVoucherBookList200DataItem } from './getVoucherBookList200DataItem'
import type { PaginationMetadata } from './paginationMetadata'

/**
 * Paginated response
 */
export type GetVoucherBookList200 = {
  /** Page items */
  data: GetVoucherBookList200DataItem[]
  pagination: PaginationMetadata
}
