/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Pika Complete API
 * Complete API documentation including public, admin, and internal endpoints
 * OpenAPI spec version: 1.0.0
 */
import type { GetVouchersByIdsResponseDataItemScansItemUserId } from './getVouchersByIdsResponseDataItemScansItemUserId'
import type { VoucherScanType } from './voucherScanType'
import type { VoucherScanSource } from './voucherScanSource'
import type { GetVouchersByIdsResponseDataItemScansItemLocation } from './getVouchersByIdsResponseDataItemScansItemLocation'
import type { GetVouchersByIdsResponseDataItemScansItemDeviceInfo } from './getVouchersByIdsResponseDataItemScansItemDeviceInfo'

export type GetVouchersByIdsResponseDataItemScansItem = {
  /** Universally Unique Identifier */
  id: string
  /** Universally Unique Identifier */
  userId: GetVouchersByIdsResponseDataItemScansItemUserId
  scanType: VoucherScanType
  scanSource: VoucherScanSource
  location: GetVouchersByIdsResponseDataItemScansItemLocation
  deviceInfo: GetVouchersByIdsResponseDataItemScansItemDeviceInfo
  /** ISO 8601 datetime with timezone */
  scannedAt: string
  /** ISO 8601 datetime with timezone */
  createdAt: string
}
