/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Pika Complete API
 * Complete API documentation including public, admin, and internal endpoints
 * OpenAPI spec version: 1.0.0
 */
import type { GetVoucherBookList200DataItemEdition } from './getVoucherBookList200DataItemEdition'
import type { GetVoucherBookList200DataItemBookType } from './getVoucherBookList200DataItemBookType'
import type { GetVoucherBookList200DataItemStatus } from './getVoucherBookList200DataItemStatus'
import type { GetVoucherBookList200DataItemPublishedAt } from './getVoucherBookList200DataItemPublishedAt'
import type { GetVoucherBookList200DataItemCoverImageUrl } from './getVoucherBookList200DataItemCoverImageUrl'
import type { GetVoucherBookList200DataItemBackImageUrl } from './getVoucherBookList200DataItemBackImageUrl'
import type { GetVoucherBookList200DataItemPdfUrl } from './getVoucherBookList200DataItemPdfUrl'

/**
 * Public voucher book information (read-only)
 */
export type GetVoucherBookList200DataItem = {
  /** Universally Unique Identifier */
  id: string
  /**
   * Voucher book title
   * @maxLength 255
   */
  title: string
  /**
   * Book edition (e.g., "January 2024")
   * @maxLength 100
   */
  edition?: GetVoucherBookList200DataItemEdition
  /** Voucher book type */
  bookType: GetVoucherBookList200DataItemBookType
  /**
   * Month for monthly books (1-12)
   * @minimum 1
   * @maximum 12
   */
  month?: number
  /**
   * Year of publication
   * @minimum 2020
   * @maximum 2100
   */
  year: number
  /** Only published books visible to public */
  status: GetVoucherBookList200DataItemStatus
  /**
   * Total number of pages
   * @minimum 1
   * @maximum 100
   */
  totalPages: number
  /** When the book was published */
  publishedAt?: GetVoucherBookList200DataItemPublishedAt
  /** URL of the cover image */
  coverImageUrl?: GetVoucherBookList200DataItemCoverImageUrl
  /** URL of the back cover image */
  backImageUrl?: GetVoucherBookList200DataItemBackImageUrl
  /** URL of the generated PDF */
  pdfUrl?: GetVoucherBookList200DataItemPdfUrl
  /** When the record was created */
  createdAt: string
  /** When the record was last updated */
  updatedAt: string
}
