/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * The VoucherBook Complete API
 * Complete API documentation including public, admin, and internal endpoints
 * OpenAPI spec version: 1.0.0
 */

/**
 * Book edition (e.g., "January 2024")
 * @maxLength 100
 */
export type GetVoucherBookList200DataItemEdition = string | null
