/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * The VoucherBook Complete API
 * Complete API documentation including public, admin, and internal endpoints
 * OpenAPI spec version: 1.0.0
 */

export type GetVoucherBookListSortOrder =
  (typeof GetVoucherBookListSortOrder)[keyof typeof GetVoucherBookListSortOrder]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetVoucherBookListSortOrder = {
  asc: 'asc',
  desc: 'desc',
} as const
