/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * The VoucherBook Complete API
 * Complete API documentation including public, admin, and internal endpoints
 * OpenAPI spec version: 1.0.0
 */

/**
 * Batch fetch vouchers by IDs
 */
export interface GetVouchersByIdsRequest {
  /**
   * List of voucher IDs to fetch
   * @minItems 1
   * @maxItems 100
   */
  voucherIds: string[]
  /** Comma-separated relations: business,category,codes */
  include?: string
}
