/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Pika Complete API
 * Complete API documentation including public, admin, and internal endpoints
 * OpenAPI spec version: 1.0.0
 */
import type { GetVouchersAnalytics200Period } from './getVouchersAnalytics200Period'
import type { GetVouchersAnalytics200ScansBySource } from './getVouchersAnalytics200ScansBySource'
import type { GetVouchersAnalytics200ScansByType } from './getVouchersAnalytics200ScansByType'
import type { GetVouchersAnalytics200DailyStatsItem } from './getVouchersAnalytics200DailyStatsItem'

export type GetVouchersAnalytics200 = {
  /** Universally Unique Identifier */
  voucherId: string
  period: GetVouchersAnalytics200Period
  /** @minimum 0 */
  totalScans: number
  /** @minimum 0 */
  totalClaims: number
  /** @minimum 0 */
  totalRedemptions: number
  /** @minimum 0 */
  uniqueUsers: number
  /**
   * @minimum 0
   * @maximum 1
   */
  redemptionRate: number
  scansBySource: GetVouchersAnalytics200ScansBySource
  scansByType: GetVouchersAnalytics200ScansByType
  dailyStats: GetVouchersAnalytics200DailyStatsItem[]
}
