/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Pika Complete API
 * Complete API documentation including public, admin, and internal endpoints
 * OpenAPI spec version: 1.0.0
 */

/**
 * Voucher book type
 */
export type GetVoucherBookById200DataBookType =
  (typeof GetVoucherBookById200DataBookType)[keyof typeof GetVoucherBookById200DataBookType]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetVoucherBookById200DataBookType = {
  monthly: 'monthly',
  specialEdition: 'specialEdition',
  regional: 'regional',
  seasonal: 'seasonal',
  promotional: 'promotional',
} as const
