/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Pika Complete API
 * Complete API documentation including public, admin, and internal endpoints
 * OpenAPI spec version: 1.0.0
 */

export type GetVoucherBookListBookType =
  (typeof GetVoucherBookListBookType)[keyof typeof GetVoucherBookListBookType]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetVoucherBookListBookType = {
  monthly: 'monthly',
  special_edition: 'special_edition',
  regional: 'regional',
  seasonal: 'seasonal',
  promotional: 'promotional',
} as const
