/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Pika Complete API
 * Complete API documentation including public, admin, and internal endpoints
 * OpenAPI spec version: 1.0.0
 */
import type { HandleStripeWebhookBodyOneOf } from './handleStripeWebhookBodyOneOf'
import type { HandleStripeWebhookBodyOneOfOnethree } from './handleStripeWebhookBodyOneOfOnethree'
import type { HandleStripeWebhookBodyOneOfTwofive } from './handleStripeWebhookBodyOneOfTwofive'
import type { HandleStripeWebhookBodyOneOfThreeseven } from './handleStripeWebhookBodyOneOfThreeseven'
import type { HandleStripeWebhookBodyOneOfFoureight } from './handleStripeWebhookBodyOneOfFoureight'
import type { HandleStripeWebhookBodyOneOfFivenine } from './handleStripeWebhookBodyOneOfFivenine'
import type { HandleStripeWebhookBodyOneOfSevenzero } from './handleStripeWebhookBodyOneOfSevenzero'
import type { HandleStripeWebhookBodyOneOfEighttwo } from './handleStripeWebhookBodyOneOfEighttwo'
import type { HandleStripeWebhookBodyOneOfNinefour } from './handleStripeWebhookBodyOneOfNinefour'
import type { HandleStripeWebhookBodyOneOfOneonezero } from './handleStripeWebhookBodyOneOfOneonezero'

export type HandleStripeWebhookBody =
  | HandleStripeWebhookBodyOneOf
  | HandleStripeWebhookBodyOneOfOnethree
  | HandleStripeWebhookBodyOneOfTwofive
  | HandleStripeWebhookBodyOneOfThreeseven
  | HandleStripeWebhookBodyOneOfFoureight
  | HandleStripeWebhookBodyOneOfFivenine
  | HandleStripeWebhookBodyOneOfSevenzero
  | HandleStripeWebhookBodyOneOfEighttwo
  | HandleStripeWebhookBodyOneOfNinefour
  | HandleStripeWebhookBodyOneOfOneonezero
