/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Pika Complete API
 * Complete API documentation including public, admin, and internal endpoints
 * OpenAPI spec version: 1.0.0
 */
import type { HandleStripeWebhookBodyOneOfThreesevenDataObjectDataObjectType } from './handleStripeWebhookBodyOneOfThreesevenDataObjectDataObjectType'
import type { HandleStripeWebhookBodyOneOfThreesevenDataObjectDataStatus } from './handleStripeWebhookBodyOneOfThreesevenDataObjectDataStatus'
import type { HandleStripeWebhookBodyOneOfThreesevenDataObjectDataMetadata } from './handleStripeWebhookBodyOneOfThreesevenDataObjectDataMetadata'

export type HandleStripeWebhookBodyOneOfThreesevenDataObjectData = {
  id: string
  objectType: HandleStripeWebhookBodyOneOfThreesevenDataObjectDataObjectType
  customer: string
  status: HandleStripeWebhookBodyOneOfThreesevenDataObjectDataStatus
  current_period_start: number
  current_period_end: number
  metadata?: HandleStripeWebhookBodyOneOfThreesevenDataObjectDataMetadata
}
