/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * The VoucherBook Complete API
 * Complete API documentation including public, admin, and internal endpoints
 * OpenAPI spec version: 1.0.0
 */

/**
 * @minLength 3
 * @maxLength 3
 */
export type HandleStripeWebhookBodyOneOfOneonezeroDataObjectDataCurrency =
  | string
  | null
