/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Pika Complete API
 * Complete API documentation including public, admin, and internal endpoints
 * OpenAPI spec version: 1.0.0
 */

export type HandleStripeWebhookBodyOneOfFoureightDataObjectDataStatus =
  (typeof HandleStripeWebhookBodyOneOfFoureightDataObjectDataStatus)[keyof typeof HandleStripeWebhookBodyOneOfFoureightDataObjectDataStatus]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const HandleStripeWebhookBodyOneOfFoureightDataObjectDataStatus = {
  active: 'active',
  past_due: 'past_due',
  unpaid: 'unpaid',
  canceled: 'canceled',
  incomplete: 'incomplete',
  incomplete_expired: 'incomplete_expired',
  trialing: 'trialing',
} as const
