/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * The VoucherBook Complete API
 * Complete API documentation including public, admin, and internal endpoints
 * OpenAPI spec version: 1.0.0
 */

export type HandleStripeWebhook400ErrorCode =
  (typeof HandleStripeWebhook400ErrorCode)[keyof typeof HandleStripeWebhook400ErrorCode]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const HandleStripeWebhook400ErrorCode = {
  invalidSignature: 'invalidSignature',
  processingError: 'processingError',
  unknownEventType: 'unknownEventType',
} as const
