/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Pika Complete API
 * Complete API documentation including public, admin, and internal endpoints
 * OpenAPI spec version: 1.0.0
 */

export type HandleStripeWebhookBodyOneOfSevenzeroType =
  (typeof HandleStripeWebhookBodyOneOfSevenzeroType)[keyof typeof HandleStripeWebhookBodyOneOfSevenzeroType]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const HandleStripeWebhookBodyOneOfSevenzeroType = {
  invoicepayment_succeeded: 'invoice.payment_succeeded',
} as const
