/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Pika Complete API
 * Complete API documentation including public, admin, and internal endpoints
 * OpenAPI spec version: 1.0.0
 */

export type HandleStripeWebhookBodyOneOfThreesevenDataObjectDataStatus =
  (typeof HandleStripeWebhookBodyOneOfThreesevenDataObjectDataStatus)[keyof typeof HandleStripeWebhookBodyOneOfThreesevenDataObjectDataStatus]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const HandleStripeWebhookBodyOneOfThreesevenDataObjectDataStatus = {
  incomplete: 'incomplete',
  incomplete_expired: 'incomplete_expired',
  trialing: 'trialing',
  active: 'active',
  past_due: 'past_due',
  canceled: 'canceled',
  unpaid: 'unpaid',
  paused: 'paused',
} as const
