/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * The VoucherBook Complete API
 * Complete API documentation including public, admin, and internal endpoints
 * OpenAPI spec version: 1.0.0
 */
import type { HandleStripeWebhookBodyOneOfThreesevenType } from './handleStripeWebhookBodyOneOfThreesevenType'
import type { HandleStripeWebhookBodyOneOfThreesevenData } from './handleStripeWebhookBodyOneOfThreesevenData'
import type { HandleStripeWebhookBodyOneOfThreesevenRequest } from './handleStripeWebhookBodyOneOfThreesevenRequest'

export type HandleStripeWebhookBodyOneOfThreeseven = {
  id: string
  type: HandleStripeWebhookBodyOneOfThreesevenType
  data: HandleStripeWebhookBodyOneOfThreesevenData
  created: number
  livemode: boolean
  pending_webhooks: number
  request: HandleStripeWebhookBodyOneOfThreesevenRequest
}
