/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * The VoucherBook Complete API
 * Complete API documentation including public, admin, and internal endpoints
 * OpenAPI spec version: 1.0.0
 */
import type { HandleStripeWebhookBodyOneOfSevenzeroType } from './handleStripeWebhookBodyOneOfSevenzeroType'
import type { HandleStripeWebhookBodyOneOfSevenzeroData } from './handleStripeWebhookBodyOneOfSevenzeroData'
import type { HandleStripeWebhookBodyOneOfSevenzeroRequest } from './handleStripeWebhookBodyOneOfSevenzeroRequest'

export type HandleStripeWebhookBodyOneOfSevenzero = {
  id: string
  type: HandleStripeWebhookBodyOneOfSevenzeroType
  data: HandleStripeWebhookBodyOneOfSevenzeroData
  created: number
  livemode: boolean
  pending_webhooks: number
  request: HandleStripeWebhookBodyOneOfSevenzeroRequest
}
