/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * The VoucherBook Complete API
 * Complete API documentation including public, admin, and internal endpoints
 * OpenAPI spec version: 1.0.0
 */

export type HandleStripeWebhookBodyOneOfDataObjectDataObjectType =
  (typeof HandleStripeWebhookBodyOneOfDataObjectDataObjectType)[keyof typeof HandleStripeWebhookBodyOneOfDataObjectDataObjectType]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const HandleStripeWebhookBodyOneOfDataObjectDataObjectType = {
  payment_intent: 'payment_intent',
} as const
