/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * The VoucherBook Complete API
 * Complete API documentation including public, admin, and internal endpoints
 * OpenAPI spec version: 1.0.0
 */
import type { HandleStripeWebhookBodyOneOfEighttwoType } from './handleStripeWebhookBodyOneOfEighttwoType'
import type { HandleStripeWebhookBodyOneOfEighttwoData } from './handleStripeWebhookBodyOneOfEighttwoData'
import type { HandleStripeWebhookBodyOneOfEighttwoRequest } from './handleStripeWebhookBodyOneOfEighttwoRequest'

export type HandleStripeWebhookBodyOneOfEighttwo = {
  id: string
  type: HandleStripeWebhookBodyOneOfEighttwoType
  data: HandleStripeWebhookBodyOneOfEighttwoData
  created: number
  livemode: boolean
  pending_webhooks: number
  request: HandleStripeWebhookBodyOneOfEighttwoRequest
}
