/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Pika Complete API
 * Complete API documentation including public, admin, and internal endpoints
 * OpenAPI spec version: 1.0.0
 */
import type { HandleStripeWebhookBodyOneOfThreesevenRequestAnyOfId } from './handleStripeWebhookBodyOneOfThreesevenRequestAnyOfId'
import type { HandleStripeWebhookBodyOneOfThreesevenRequestAnyOfIdempotencyKey } from './handleStripeWebhookBodyOneOfThreesevenRequestAnyOfIdempotencyKey'

export type HandleStripeWebhookBodyOneOfThreesevenRequestAnyOf = {
  id: HandleStripeWebhookBodyOneOfThreesevenRequestAnyOfId
  idempotency_key: HandleStripeWebhookBodyOneOfThreesevenRequestAnyOfIdempotencyKey
}
