/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Pika Complete API
 * Complete API documentation including public, admin, and internal endpoints
 * OpenAPI spec version: 1.0.0
 */
import type { HandleStripeWebhook500Error } from './handleStripeWebhook500Error'

/**
 * Webhook error response
 */
export type HandleStripeWebhook500 = {
  error: HandleStripeWebhook500Error
}
