/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * The VoucherBook Complete API
 * Complete API documentation including public, admin, and internal endpoints
 * OpenAPI spec version: 1.0.0
 */
import type { HandleStripeWebhookBodyOneOfNinefourDataObjectDataObjectType } from './handleStripeWebhookBodyOneOfNinefourDataObjectDataObjectType'
import type { HandleStripeWebhookBodyOneOfNinefourDataObjectDataCustomer } from './handleStripeWebhookBodyOneOfNinefourDataObjectDataCustomer'
import type { HandleStripeWebhookBodyOneOfNinefourDataObjectDataPaymentIntent } from './handleStripeWebhookBodyOneOfNinefourDataObjectDataPaymentIntent'
import type { HandleStripeWebhookBodyOneOfNinefourDataObjectDataSubscription } from './handleStripeWebhookBodyOneOfNinefourDataObjectDataSubscription'
import type { HandleStripeWebhookBodyOneOfNinefourDataObjectDataAmountTotal } from './handleStripeWebhookBodyOneOfNinefourDataObjectDataAmountTotal'
import type { HandleStripeWebhookBodyOneOfNinefourDataObjectDataCurrency } from './handleStripeWebhookBodyOneOfNinefourDataObjectDataCurrency'
import type { HandleStripeWebhookBodyOneOfNinefourDataObjectDataMetadata } from './handleStripeWebhookBodyOneOfNinefourDataObjectDataMetadata'
import type { HandleStripeWebhookBodyOneOfNinefourDataObjectDataPaymentStatus } from './handleStripeWebhookBodyOneOfNinefourDataObjectDataPaymentStatus'

export type HandleStripeWebhookBodyOneOfNinefourDataObjectData = {
  id: string
  objectType: HandleStripeWebhookBodyOneOfNinefourDataObjectDataObjectType
  customer: HandleStripeWebhookBodyOneOfNinefourDataObjectDataCustomer
  payment_intent: HandleStripeWebhookBodyOneOfNinefourDataObjectDataPaymentIntent
  subscription: HandleStripeWebhookBodyOneOfNinefourDataObjectDataSubscription
  amount_total: HandleStripeWebhookBodyOneOfNinefourDataObjectDataAmountTotal
  /**
   * @minLength 3
   * @maxLength 3
   */
  currency: HandleStripeWebhookBodyOneOfNinefourDataObjectDataCurrency
  metadata?: HandleStripeWebhookBodyOneOfNinefourDataObjectDataMetadata
  payment_status: HandleStripeWebhookBodyOneOfNinefourDataObjectDataPaymentStatus
}
