/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Pika Complete API
 * Complete API documentation including public, admin, and internal endpoints
 * OpenAPI spec version: 1.0.0
 */

/**
 * Initiate password reset
 */
export interface InitiatePasswordResetRequest {
  /** @minLength 1 */
  email: string
  callbackUrl?: string
}
