/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * The VoucherBook Complete API
 * Complete API documentation including public, admin, and internal endpoints
 * OpenAPI spec version: 1.0.0
 */
import type { InternalBulkDeleteResponseFailedItem } from './internalBulkDeleteResponseFailedItem'

/**
 * Internal bulk delete response
 */
export interface InternalBulkDeleteResponse {
  deleted: string[]
  failed: InternalBulkDeleteResponseFailedItem[]
  /** @minimum 0 */
  totalDeleted: number
  /** @minimum 0 */
  totalFailed: number
}
