/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * The VoucherBook Complete API
 * Complete API documentation including public, admin, and internal endpoints
 * OpenAPI spec version: 1.0.0
 */
import type { InternalCreateFileRequestFileType } from './internalCreateFileRequestFileType'
import type { InternalCreateFileRequestProvider } from './internalCreateFileRequestProvider'
import type { InternalCreateFileRequestMetadata } from './internalCreateFileRequestMetadata'

/**
 * Internal file creation request
 */
export interface InternalCreateFileRequest {
  userId: string
  fileKey: string
  fileName: string
  /** */
  fileSize: number
  mimeType: string
  /** File type category */
  fileType: InternalCreateFileRequestFileType
  /** Supported storage provider */
  provider: InternalCreateFileRequestProvider
  bucketName?: string
  region?: string
  isPublic?: boolean
  metadata?: InternalCreateFileRequestMetadata
}
