/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Pika Complete API
 * Complete API documentation including public, admin, and internal endpoints
 * OpenAPI spec version: 1.0.0
 */

/**
 * File type category
 */
export type InternalFileResponseFileType =
  (typeof InternalFileResponseFileType)[keyof typeof InternalFileResponseFileType]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const InternalFileResponseFileType = {
  image: 'image',
  video: 'video',
  document: 'document',
  audio: 'audio',
  other: 'other',
} as const
