/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Pika Complete API
 * Complete API documentation including public, admin, and internal endpoints
 * OpenAPI spec version: 1.0.0
 */
import type { IntrospectRequestTokenTypeHint } from './introspectRequestTokenTypeHint'

/**
 * Token introspection request
 */
export interface IntrospectRequest {
  /**
   * Token to validate
   * @minLength 1
   */
  token: string
  /** Type of authentication token */
  tokenTypeHint?: IntrospectRequestTokenTypeHint
}
