/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * The VoucherBook Complete API
 * Complete API documentation including public, admin, and internal endpoints
 * OpenAPI spec version: 1.0.0
 */
import type { LinkAccountResponseLinkedAccountsItem } from './linkAccountResponseLinkedAccountsItem'

/**
 * Response after account linking attempt
 */
export interface LinkAccountResponse {
  /** Whether linking was successful */
  success: boolean
  /** Success or error message */
  message: string
  /** Updated list of linked accounts */
  linkedAccounts: LinkAccountResponseLinkedAccountsItem[]
}
