/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Pika Complete API
 * Complete API documentation including public, admin, and internal endpoints
 * OpenAPI spec version: 1.0.0
 */

/**
 * Social provider to link
 */
export type LinkAccountRequestProvider =
  (typeof LinkAccountRequestProvider)[keyof typeof LinkAccountRequestProvider]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const LinkAccountRequestProvider = {
  google: 'google',
  facebook: 'facebook',
  apple: 'apple',
} as const
