/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Pika Complete API
 * Complete API documentation including public, admin, and internal endpoints
 * OpenAPI spec version: 1.0.0
 */

export type MigrateInternalFile200MigrationStatus =
  (typeof MigrateInternalFile200MigrationStatus)[keyof typeof MigrateInternalFile200MigrationStatus]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const MigrateInternalFile200MigrationStatus = {
  success: 'success',
  failed: 'failed',
  partial: 'partial',
} as const
