/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * The VoucherBook Complete API
 * Complete API documentation including public, admin, and internal endpoints
 * OpenAPI spec version: 1.0.0
 */
import type { MigrateFileRequestTargetProvider } from './migrateFileRequestTargetProvider'

/**
 * Migrate file between storage providers
 */
export interface MigrateFileRequest {
  /** Universally Unique Identifier */
  fileId: string
  /** Supported storage provider */
  targetProvider: MigrateFileRequestTargetProvider
  targetBucket?: string
  targetRegion?: string
  deleteOriginal?: boolean
}
