/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Pika Complete API
 * Complete API documentation including public, admin, and internal endpoints
 * OpenAPI spec version: 1.0.0
 */

/**
 * Move category to different parent or change sort order
 */
export type MoveAdminCategoryBody = {
  /** New parent category ID (null for root level) */
  parentId?: string
  /** New sort order within parent */
  sortOrder?: number
}
