/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Pika Complete API
 * Complete API documentation including public, admin, and internal endpoints
 * OpenAPI spec version: 1.0.0
 */

export type NotificationPriority =
  (typeof NotificationPriority)[keyof typeof NotificationPriority]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const NotificationPriority = {
  low: 'low',
  normal: 'normal',
  high: 'high',
  urgent: 'urgent',
} as const
