/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * The VoucherBook Complete API
 * Complete API documentation including public, admin, and internal endpoints
 * OpenAPI spec version: 1.0.0
 */
import type { PatchUserSettings200SettingsBusinessDashboard } from './patchUserSettings200SettingsBusinessDashboard'
import type { PatchUserSettings200SettingsBusinessVouchers } from './patchUserSettings200SettingsBusinessVouchers'
import type { PatchUserSettings200SettingsBusinessNotifications } from './patchUserSettings200SettingsBusinessNotifications'

export type PatchUserSettings200SettingsBusiness = {
  dashboard: PatchUserSettings200SettingsBusinessDashboard
  vouchers: PatchUserSettings200SettingsBusinessVouchers
  notifications: PatchUserSettings200SettingsBusinessNotifications
}
