/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * The VoucherBook Complete API
 * Complete API documentation including public, admin, and internal endpoints
 * OpenAPI spec version: 1.0.0
 */
import type { PatchBusinessVerificationResponseCategoryId } from './patchBusinessVerificationResponseCategoryId'
import type { PatchBusinessVerificationResponseApprovedBy } from './patchBusinessVerificationResponseApprovedBy'
import type { PatchBusinessVerificationResponseApprovedAt } from './patchBusinessVerificationResponseApprovedAt'
import type { PatchBusinessVerificationResponseLogoUrl } from './patchBusinessVerificationResponseLogoUrl'
import type { PatchBusinessVerificationResponseDeletedAt } from './patchBusinessVerificationResponseDeletedAt'
import type { PatchBusinessVerificationResponseUser } from './patchBusinessVerificationResponseUser'
import type { PatchBusinessVerificationResponseCategory } from './patchBusinessVerificationResponseCategory'
import type { PatchBusinessVerificationResponseBusinessRegistration } from './patchBusinessVerificationResponseBusinessRegistration'

export interface PatchBusinessVerificationResponse {
  /** Universally Unique Identifier */
  id: string
  /** User who owns this business */
  userId: string
  /**
   * Business name (resolved translation)
   * @maxLength 255
   */
  businessName: string
  /**
   * Business description (resolved translation)
   * @maxLength 255
   */
  businessDescription?: string
  /** Category this business belongs to */
  categoryId: PatchBusinessVerificationResponseCategoryId
  /** Whether business is verified */
  verified?: boolean
  /** Whether business is active */
  active?: boolean
  /** Whether business is approved by admin */
  approved?: boolean
  /** Admin who approved the business */
  approvedBy?: PatchBusinessVerificationResponseApprovedBy
  /** When the business was approved */
  approvedAt?: PatchBusinessVerificationResponseApprovedAt
  /**
   * Average rating of the business
   * @minimum 0
   * @maximum 5
   */
  avgRating?: number
  /** URL of the business logo */
  logoUrl?: PatchBusinessVerificationResponseLogoUrl
  /** Soft deletion timestamp */
  deletedAt: PatchBusinessVerificationResponseDeletedAt
  /** Business owner details when ?include=user */
  user?: PatchBusinessVerificationResponseUser
  /** Category information when ?include=category */
  category?: PatchBusinessVerificationResponseCategory
  /** Business registration info when ?include=businessRegistration */
  businessRegistration?: PatchBusinessVerificationResponseBusinessRegistration
  /** When the record was created */
  createdAt: string
  /** When the record was last updated */
  updatedAt: string
}
