/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Pika Complete API
 * Complete API documentation including public, admin, and internal endpoints
 * OpenAPI spec version: 1.0.0
 */
import type { PatchUserSettingsResponseSettingsBusinessDashboardDefaultView } from './patchUserSettingsResponseSettingsBusinessDashboardDefaultView'

export type PatchUserSettingsResponseSettingsBusinessDashboard = {
  defaultView: PatchUserSettingsResponseSettingsBusinessDashboardDefaultView
  autoRefresh: boolean
  /**
   * @minimum 1
   * @maximum 60
   */
  refreshInterval: number
}
