/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * The VoucherBook Complete API
 * Complete API documentation including public, admin, and internal endpoints
 * OpenAPI spec version: 1.0.0
 */
import type { PatchUserSettingsRequestBusinessDashboard } from './patchUserSettingsRequestBusinessDashboard'
import type { PatchUserSettingsRequestBusinessVouchers } from './patchUserSettingsRequestBusinessVouchers'
import type { PatchUserSettingsRequestBusinessNotifications } from './patchUserSettingsRequestBusinessNotifications'

export type PatchUserSettingsRequestBusiness = {
  dashboard?: PatchUserSettingsRequestBusinessDashboard
  vouchers?: PatchUserSettingsRequestBusinessVouchers
  notifications?: PatchUserSettingsRequestBusinessNotifications
}
