/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Pika Complete API
 * Complete API documentation including public, admin, and internal endpoints
 * OpenAPI spec version: 1.0.0
 */

export type PatchSubscriptionsPlansId200Currency =
  (typeof PatchSubscriptionsPlansId200Currency)[keyof typeof PatchSubscriptionsPlansId200Currency]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PatchSubscriptionsPlansId200Currency = {
  usd: 'usd',
  eur: 'eur',
  gbp: 'gbp',
} as const
