/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Pika Complete API
 * Complete API documentation including public, admin, and internal endpoints
 * OpenAPI spec version: 1.0.0
 */
import type { PatchUserSettings200SettingsVersion } from './patchUserSettings200SettingsVersion'
import type { PatchUserSettings200SettingsDisplay } from './patchUserSettings200SettingsDisplay'
import type { PatchUserSettings200SettingsNotifications } from './patchUserSettings200SettingsNotifications'
import type { PatchUserSettings200SettingsPrivacy } from './patchUserSettings200SettingsPrivacy'
import type { PatchUserSettings200SettingsBusiness } from './patchUserSettings200SettingsBusiness'
import type { PatchUserSettings200SettingsAccessibility } from './patchUserSettings200SettingsAccessibility'
import type { PatchUserSettings200SettingsUpdatedAt } from './patchUserSettings200SettingsUpdatedAt'

export type PatchUserSettings200Settings = {
  version: PatchUserSettings200SettingsVersion
  display: PatchUserSettings200SettingsDisplay
  notifications: PatchUserSettings200SettingsNotifications
  privacy: PatchUserSettings200SettingsPrivacy
  business?: PatchUserSettings200SettingsBusiness
  accessibility: PatchUserSettings200SettingsAccessibility
  updatedAt: PatchUserSettings200SettingsUpdatedAt
}
