/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * The VoucherBook Complete API
 * Complete API documentation including public, admin, and internal endpoints
 * OpenAPI spec version: 1.0.0
 */
import type { VoucherState } from './voucherState'
import type { PatchVouchersBulkUpdateBodyUpdatesMaxRedemptions } from './patchVouchersBulkUpdateBodyUpdatesMaxRedemptions'

export type PatchVouchersBulkUpdateBodyUpdates = {
  state?: VoucherState
  /** ISO 8601 datetime with timezone */
  expiresAt?: string
  /** */
  maxRedemptions?: PatchVouchersBulkUpdateBodyUpdatesMaxRedemptions
  /** */
  maxRedemptionsPerUser?: number
}
