/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Pika Complete API
 * Complete API documentation including public, admin, and internal endpoints
 * OpenAPI spec version: 1.0.0
 */

/**
 * Type of payment method
 */
export type PaymentMethodType =
  (typeof PaymentMethodType)[keyof typeof PaymentMethodType]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PaymentMethodType = {
  CARD: 'CARD',
  BANK_ACCOUNT: 'BANK_ACCOUNT',
  PAYPAL: 'PAYPAL',
  APPLE_PAY: 'APPLE_PAY',
  GOOGLE_PAY: 'GOOGLE_PAY',
  WALLET: 'WALLET',
} as const
