/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * The VoucherBook Complete API
 * Complete API documentation including public, admin, and internal endpoints
 * OpenAPI spec version: 1.0.0
 */
import type { CardBrand } from './cardBrand'
import type { PaymentMethodCardFunding } from './paymentMethodCardFunding'

export type PaymentMethodCard = {
  brand: CardBrand
  /**
   * @minLength 4
   * @maxLength 4
   */
  last4: string
  /**
   * @minimum 1
   * @maximum 12
   */
  expMonth: number
  /** @minimum 2025 */
  expYear: number
  holderName?: string
  /**
   * @minLength 2
   * @maxLength 2
   */
  country?: string
  funding?: PaymentMethodCardFunding
}
