/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Pika Complete API
 * Complete API documentation including public, admin, and internal endpoints
 * OpenAPI spec version: 1.0.0
 */

export type PaymentMethodCardBrand =
  (typeof PaymentMethodCardBrand)[keyof typeof PaymentMethodCardBrand]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PaymentMethodCardBrand = {
  VISA: 'VISA',
  MASTERCARD: 'MASTERCARD',
  AMEX: 'AMEX',
  DISCOVER: 'DISCOVER',
  DINERS: 'DINERS',
  JCB: 'JCB',
  UNIONPAY: 'UNIONPAY',
  UNKNOWN: 'UNKNOWN',
} as const
