/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Pika Complete API
 * Complete API documentation including public, admin, and internal endpoints
 * OpenAPI spec version: 1.0.0
 */

export type PaymentMethodWalletType =
  (typeof PaymentMethodWalletType)[keyof typeof PaymentMethodWalletType]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PaymentMethodWalletType = {
  APPLE_PAY: 'APPLE_PAY',
  GOOGLE_PAY: 'GOOGLE_PAY',
  SAMSUNG_PAY: 'SAMSUNG_PAY',
} as const
