/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * The VoucherBook Complete API
 * Complete API documentation including public, admin, and internal endpoints
 * OpenAPI spec version: 1.0.0
 */
import type { PaymentStatsResponsePeriod } from './paymentStatsResponsePeriod'
import type { PaymentStatsResponseRevenueByType } from './paymentStatsResponseRevenueByType'
import type { PaymentStatsResponseRevenueByPaymentMethod } from './paymentStatsResponseRevenueByPaymentMethod'
import type { PaymentStatsResponseTopBusinessesItem } from './paymentStatsResponseTopBusinessesItem'
import type { PaymentStatsResponseTopUsersItem } from './paymentStatsResponseTopUsersItem'

export interface PaymentStatsResponse {
  period: PaymentStatsResponsePeriod
  /** @minimum 0 */
  totalRevenue: number
  /** @minimum 0 */
  totalRefunds: number
  /** @minimum 0 */
  totalFees: number
  /** @minimum 0 */
  netRevenue: number
  /** Revenue by transaction type (all keys optional) */
  revenueByType: PaymentStatsResponseRevenueByType
  /** Revenue by payment method (all keys optional) */
  revenueByPaymentMethod: PaymentStatsResponseRevenueByPaymentMethod
  /** @minimum 0 */
  transactionCount: number
  /** @minimum 0 */
  successfulCount: number
  /** @minimum 0 */
  failedCount: number
  /** @minimum 0 */
  disputeCount: number
  /** @minimum 0 */
  averageTransactionAmount: number
  topBusinesses?: PaymentStatsResponseTopBusinessesItem[]
  topUsers?: PaymentStatsResponseTopUsersItem[]
}
