/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Pika Complete API
 * Complete API documentation including public, admin, and internal endpoints
 * OpenAPI spec version: 1.0.0
 */
import type { PayoutListResponseDataItem } from './payoutListResponseDataItem'
import type { PaginationMetadata } from './paginationMetadata'

/**
 * Paginated response
 */
export interface PayoutListResponse {
  /** Page items */
  data: PayoutListResponseDataItem[]
  pagination: PaginationMetadata
}
