/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Pika Complete API
 * Complete API documentation including public, admin, and internal endpoints
 * OpenAPI spec version: 1.0.0
 */

export type PostPromoCodesBodyType =
  (typeof PostPromoCodesBodyType)[keyof typeof PostPromoCodesBodyType]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PostPromoCodesBodyType = {
  fixedAmount: 'fixedAmount',
  percentage: 'percentage',
} as const
