/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Pika Complete API
 * Complete API documentation including public, admin, and internal endpoints
 * OpenAPI spec version: 1.0.0
 */
import type { PostPromoCodes201Type } from './postPromoCodes201Type'

export type PostPromoCodes201 = {
  /** Universally Unique Identifier */
  id: string
  code: string
  type: PostPromoCodes201Type
  /** */
  value: number
  description?: string
  /** */
  maxUses?: number
  /** @minimum 0 */
  usedCount?: number
  /** */
  maxUsesPerUser?: number
  /** ISO 8601 datetime with timezone */
  validFrom: string
  /** ISO 8601 datetime with timezone */
  validUntil?: string
  /** @minimum 0 */
  minPurchaseAmount?: number
  applicableToBusinesses?: string[]
  applicableToUserTiers?: string[]
  firstTimeOnly?: boolean
  isActive?: boolean
  /** @minimum 0 */
  totalDiscountGiven?: number
  createdBy: string
  adminNotes?: string
  /** When the record was created */
  createdAt: string
  /** When the record was last updated */
  updatedAt: string
}
