/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * The VoucherBook Complete API
 * Complete API documentation including public, admin, and internal endpoints
 * OpenAPI spec version: 1.0.0
 */

export type PostSubscriptionsPlans201BillingInterval =
  (typeof PostSubscriptionsPlans201BillingInterval)[keyof typeof PostSubscriptionsPlans201BillingInterval]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PostSubscriptionsPlans201BillingInterval = {
  day: 'day',
  week: 'week',
  month: 'month',
  year: 'year',
} as const
