/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Pika Complete API
 * Complete API documentation including public, admin, and internal endpoints
 * OpenAPI spec version: 1.0.0
 */
import type { PostPromoCodesBodyType } from './postPromoCodesBodyType'

export type PostPromoCodesBody = {
  /**
   * @minLength 3
   * @maxLength 20
   */
  code: string
  type: PostPromoCodesBodyType
  /** */
  value: number
  /** @maxLength 500 */
  description?: string
  /** */
  maxUses?: number
  /** */
  maxUsesPerUser?: number
  /** ISO 8601 datetime with timezone */
  validFrom: string
  /** ISO 8601 datetime with timezone */
  validUntil?: string
  /** @minimum 0 */
  minPurchaseAmount?: number
  applicableToBusinesses?: string[]
  applicableToUserTiers?: string[]
  firstTimeOnly?: boolean
  adminNotes?: string
}
