/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Pika Complete API
 * Complete API documentation including public, admin, and internal endpoints
 * OpenAPI spec version: 1.0.0
 */
import type { PostSubscriptionsPlansBodyCurrency } from './postSubscriptionsPlansBodyCurrency'
import type { PostSubscriptionsPlansBodyBillingInterval } from './postSubscriptionsPlansBodyBillingInterval'

/**
 * Create a new subscription plan
 */
export type PostSubscriptionsPlansBody = {
  /**
   * @minLength 1
   * @maxLength 100
   */
  name: string
  /** @maxLength 1000 */
  description: string
  /** @minimum 0 */
  price: number
  currency?: PostSubscriptionsPlansBodyCurrency
  billingInterval: PostSubscriptionsPlansBodyBillingInterval
  /** @minimum 0 */
  trialPeriodDays?: number
  /** */
  maxUsagePerMonth?: number
  isActive?: boolean
  isPublic?: boolean
  adminNotes?: string
}
