/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * The VoucherBook Complete API
 * Complete API documentation including public, admin, and internal endpoints
 * OpenAPI spec version: 1.0.0
 */

/**
 * Webhook processing result
 */
export interface ProcessWebhookResponse {
  processed: boolean
  /** Universally Unique Identifier */
  subscriptionId?: string
  action?: string
}
