/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Pika Complete API
 * Complete API documentation including public, admin, and internal endpoints
 * OpenAPI spec version: 1.0.0
 */
import type { PublishAdminVoucher200RedemptionsItemMetadata } from './publishAdminVoucher200RedemptionsItemMetadata'

export type PublishAdminVoucher200RedemptionsItem = {
  /** Universally Unique Identifier */
  id: string
  /** Universally Unique Identifier */
  userId: string
  codeUsed: string
  /** ISO 8601 datetime with timezone */
  redeemedAt: string
  metadata: PublishAdminVoucher200RedemptionsItemMetadata
  /** ISO 8601 datetime with timezone */
  createdAt: string
}
