/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Pika Complete API
 * Complete API documentation including public, admin, and internal endpoints
 * OpenAPI spec version: 1.0.0
 */
import type { VoucherState } from './voucherState'
import type { VoucherDiscountType } from './voucherDiscountType'
import type { PublishAdminVoucher200Location } from './publishAdminVoucher200Location'
import type { PublishAdminVoucher200ImageUrl } from './publishAdminVoucher200ImageUrl'
import type { PublishAdminVoucher200MaxRedemptions } from './publishAdminVoucher200MaxRedemptions'
import type { PublishAdminVoucher200Metadata } from './publishAdminVoucher200Metadata'
import type { PublishAdminVoucher200DeletedAt } from './publishAdminVoucher200DeletedAt'
import type { PublishAdminVoucher200Business } from './publishAdminVoucher200Business'
import type { PublishAdminVoucher200Category } from './publishAdminVoucher200Category'
import type { PublishAdminVoucher200CodesItem } from './publishAdminVoucher200CodesItem'
import type { PublishAdminVoucher200RedemptionsItem } from './publishAdminVoucher200RedemptionsItem'
import type { PublishAdminVoucher200ScansItem } from './publishAdminVoucher200ScansItem'
import type { PublishAdminVoucher200CustomerVouchersItem } from './publishAdminVoucher200CustomerVouchersItem'
import type { PublishAdminVoucher200DaysUntilExpiry } from './publishAdminVoucher200DaysUntilExpiry'

export type PublishAdminVoucher200 = {
  /** Universally Unique Identifier */
  id: string
  /** Universally Unique Identifier */
  businessId: string
  /** Universally Unique Identifier */
  categoryId?: string
  state: VoucherState
  /** Voucher title in requested language */
  title: string
  /** Voucher description in requested language */
  description: string
  /** Voucher terms and conditions in requested language */
  terms: string
  discountType: VoucherDiscountType
  /** Decimal number with 2 decimal places */
  discountValue: number
  currency?: string
  location: PublishAdminVoucher200Location
  imageUrl: PublishAdminVoucher200ImageUrl
  /** ISO 8601 datetime with timezone */
  validFrom: string
  /** ISO 8601 datetime with timezone */
  expiresAt: string
  maxRedemptions: PublishAdminVoucher200MaxRedemptions
  maxRedemptionsPerUser?: number
  currentRedemptions?: number
  scanCount?: number
  claimCount?: number
  metadata: PublishAdminVoucher200Metadata
  /** ISO 8601 datetime with timezone */
  deletedAt: PublishAdminVoucher200DeletedAt
  /** Complete business object when ?include=business */
  business?: PublishAdminVoucher200Business
  /** Complete category object when ?include=category */
  category?: PublishAdminVoucher200Category
  /** Voucher codes when ?include=codes */
  codes?: PublishAdminVoucher200CodesItem[]
  /** Redemption history when ?include=redemptions */
  redemptions?: PublishAdminVoucher200RedemptionsItem[]
  /** Scan analytics when ?include=scans */
  scans?: PublishAdminVoucher200ScansItem[]
  /** Customer wallet entries when ?include=customerVouchers */
  customerVouchers?: PublishAdminVoucher200CustomerVouchersItem[]
  isActive: boolean
  isExpired: boolean
  /**
   * @minimum 0
   * @maximum 1
   */
  redemptionRate: number
  daysUntilExpiry: PublishAdminVoucher200DaysUntilExpiry
  /** When the record was created */
  createdAt: string
  /** When the record was last updated */
  updatedAt: string
}
