/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * The VoucherBook Complete API
 * Complete API documentation including public, admin, and internal endpoints
 * OpenAPI spec version: 1.0.0
 */

export type RefundAdminTransaction200DisputeStatus =
  (typeof RefundAdminTransaction200DisputeStatus)[keyof typeof RefundAdminTransaction200DisputeStatus]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const RefundAdminTransaction200DisputeStatus = {
  warning: 'warning',
  needsResponse: 'needsResponse',
  underReview: 'underReview',
  won: 'won',
  lost: 'lost',
} as const
