/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Pika Complete API
 * Complete API documentation including public, admin, and internal endpoints
 * OpenAPI spec version: 1.0.0
 */

export type RegisterServiceRequestServiceType =
  (typeof RegisterServiceRequestServiceType)[keyof typeof RegisterServiceRequestServiceType]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const RegisterServiceRequestServiceType = {
  apiGateway: 'apiGateway',
  microservice: 'microservice',
  database: 'database',
  cache: 'cache',
  queue: 'queue',
  storage: 'storage',
  monitoring: 'monitoring',
} as const
