/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Pika Complete API
 * Complete API documentation including public, admin, and internal endpoints
 * OpenAPI spec version: 1.0.0
 */

/**
 * Current registration status
 */
export type RegistrationProgressResponseRegistrationStatus =
  (typeof RegistrationProgressResponseRegistrationStatus)[keyof typeof RegistrationProgressResponseRegistrationStatus]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const RegistrationProgressResponseRegistrationStatus = {
  in_progress: 'in_progress',
  submitted: 'submitted',
  approved: 'approved',
  rejected: 'rejected',
} as const
