/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Pika Complete API
 * Complete API documentation including public, admin, and internal endpoints
 * OpenAPI spec version: 1.0.0
 */

/**
 * Request password reset email
 */
export type ResendVerificationBody = {
  /** @minLength 1 */
  email: string
}
