/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Pika Complete API
 * Complete API documentation including public, admin, and internal endpoints
 * OpenAPI spec version: 1.0.0
 */
import type { RevokeTokenRequestTokenTypeHint } from './revokeTokenRequestTokenTypeHint'

/**
 * Token revocation request
 */
export interface RevokeTokenRequest {
  /**
   * Token to revoke
   * @minLength 1
   */
  token: string
  /** Type of authentication token */
  tokenTypeHint?: RevokeTokenRequestTokenTypeHint
  /** Revoke all tokens for user */
  allDevices?: boolean
}
