/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Pika Complete API
 * Complete API documentation including public, admin, and internal endpoints
 * OpenAPI spec version: 1.0.0
 */
import type { SendTransactionalEmailRequestTemplateKey } from './sendTransactionalEmailRequestTemplateKey'
import type { SendTransactionalEmailRequestVariables } from './sendTransactionalEmailRequestVariables'
import type { SendTransactionalEmailRequestAttachmentsItem } from './sendTransactionalEmailRequestAttachmentsItem'

/**
 * Send transactional email
 */
export interface SendTransactionalEmailRequest {
  userId: string
  templateKey: SendTransactionalEmailRequestTemplateKey
  variables: SendTransactionalEmailRequestVariables
  /** Override template subject */
  subject?: string
  /** @minLength 1 */
  replyTo?: string
  attachments?: SendTransactionalEmailRequestAttachmentsItem[]
  /** ISO 8601 datetime with timezone */
  sendAt?: string
  trackOpens?: boolean
  trackClicks?: boolean
}
