/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Pika Complete API
 * Complete API documentation including public, admin, and internal endpoints
 * OpenAPI spec version: 1.0.0
 */

export type SendInternalSystemNotificationBodyChannelsItem =
  (typeof SendInternalSystemNotificationBodyChannelsItem)[keyof typeof SendInternalSystemNotificationBodyChannelsItem]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const SendInternalSystemNotificationBodyChannelsItem = {
  email: 'email',
  inApp: 'inApp',
  sms: 'sms',
  push: 'push',
} as const
