/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * The VoucherBook Complete API
 * Complete API documentation including public, admin, and internal endpoints
 * OpenAPI spec version: 1.0.0
 */
import type { ServiceKeyValidationResponseRateLimit } from './serviceKeyValidationResponseRateLimit'

/**
 * Service key validation result
 */
export interface ServiceKeyValidationResponse {
  valid: boolean
  serviceName?: string
  permissions?: string[]
  rateLimit?: ServiceKeyValidationResponseRateLimit
}
