/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Pika Complete API
 * Complete API documentation including public, admin, and internal endpoints
 * OpenAPI spec version: 1.0.0
 */

export type ServiceRegistryQueryStatus =
  (typeof ServiceRegistryQueryStatus)[keyof typeof ServiceRegistryQueryStatus]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ServiceRegistryQueryStatus = {
  STARTING: 'STARTING',
  HEALTHY: 'HEALTHY',
  DEGRADED: 'DEGRADED',
  UNHEALTHY: 'UNHEALTHY',
  STOPPED: 'STOPPED',
} as const
