/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Pika Complete API
 * Complete API documentation including public, admin, and internal endpoints
 * OpenAPI spec version: 1.0.0
 */

export type ServiceRegistryResponseServicesItemEndpointsItemProtocol =
  (typeof ServiceRegistryResponseServicesItemEndpointsItemProtocol)[keyof typeof ServiceRegistryResponseServicesItemEndpointsItemProtocol]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ServiceRegistryResponseServicesItemEndpointsItemProtocol = {
  http: 'http',
  https: 'https',
  tcp: 'tcp',
  grpc: 'grpc',
} as const
