/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Pika Complete API
 * Complete API documentation including public, admin, and internal endpoints
 * OpenAPI spec version: 1.0.0
 */
import type { ServiceEndpointsResponseInstancesItemEndpointsItemProtocol } from './serviceEndpointsResponseInstancesItemEndpointsItemProtocol'

export type ServiceEndpointsResponseInstancesItemEndpointsItem = {
  protocol: ServiceEndpointsResponseInstancesItemEndpointsItemProtocol
  host: string
  /** */
  port: number
  path?: string
  healthCheckPath?: string
}
