/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Pika Complete API
 * Complete API documentation including public, admin, and internal endpoints
 * OpenAPI spec version: 1.0.0
 */
import type { ServiceRegistryResponseServicesItem } from './serviceRegistryResponseServicesItem'

/**
 * List of registered services
 */
export interface ServiceRegistryResponse {
  services: ServiceRegistryResponseServicesItem[]
  /** @minimum 0 */
  totalCount: number
  /** ISO 8601 datetime with timezone */
  lastUpdated: string
}
