/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Pika Complete API
 * Complete API documentation including public, admin, and internal endpoints
 * OpenAPI spec version: 1.0.0
 */
import type { ServiceRegistryResponseServicesItemServiceType } from './serviceRegistryResponseServicesItemServiceType'
import type { ServiceRegistryResponseServicesItemEndpointsItem } from './serviceRegistryResponseServicesItemEndpointsItem'
import type { ServiceRegistryResponseServicesItemEnvironment } from './serviceRegistryResponseServicesItemEnvironment'
import type { ServiceRegistryResponseServicesItemStatus } from './serviceRegistryResponseServicesItemStatus'
import type { ServiceRegistryResponseServicesItemMetadata } from './serviceRegistryResponseServicesItemMetadata'
import type { ServiceRegistryResponseServicesItemMetrics } from './serviceRegistryResponseServicesItemMetrics'

/**
 * Service instance in the registry
 */
export type ServiceRegistryResponseServicesItem = {
  /** Universally Unique Identifier */
  id: string
  /**
   * @minLength 1
   * @maxLength 100
   */
  serviceName: string
  serviceType: ServiceRegistryResponseServicesItemServiceType
  /** @pattern ^\d+\.\d+\.\d+$ */
  version: string
  /** @minLength 1 */
  instanceId: string
  /** @minItems 1 */
  endpoints: ServiceRegistryResponseServicesItemEndpointsItem[]
  environment: ServiceRegistryResponseServicesItemEnvironment
  region?: string
  availabilityZone?: string
  status: ServiceRegistryResponseServicesItemStatus
  /** ISO 8601 datetime with timezone */
  lastHealthCheck?: string
  healthCheckUrl?: string
  metadata?: ServiceRegistryResponseServicesItemMetadata
  tags?: string[]
  metrics?: ServiceRegistryResponseServicesItemMetrics
  registeredBy?: string
  /** ISO 8601 datetime with timezone */
  lastSeen: string
  /** */
  ttl?: number
  /** When the record was created */
  createdAt: string
  /** When the record was last updated */
  updatedAt: string
}
