/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Pika Complete API
 * Complete API documentation including public, admin, and internal endpoints
 * OpenAPI spec version: 1.0.0
 */

export type ServiceRegistryQueryEnvironment =
  (typeof ServiceRegistryQueryEnvironment)[keyof typeof ServiceRegistryQueryEnvironment]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ServiceRegistryQueryEnvironment = {
  development: 'development',
  staging: 'staging',
  production: 'production',
  test: 'test',
} as const
