/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * The VoucherBook Complete API
 * Complete API documentation including public, admin, and internal endpoints
 * OpenAPI spec version: 1.0.0
 */
import type { SocialLoginRequestProvider } from './socialLoginRequestProvider'
import type { SocialLoginRequestDeviceInfo } from './socialLoginRequestDeviceInfo'

/**
 * Request to authenticate via social provider
 */
export interface SocialLoginRequest {
  /** Social auth provider */
  provider: SocialLoginRequestProvider
  /**
   * Firebase ID token from social provider
   * @minLength 1
   */
  idToken: string
  /** Provider access token (optional) */
  accessToken?: string
  /** Device information for tracking */
  deviceInfo?: SocialLoginRequestDeviceInfo
  /** Marketing consent */
  marketingConsent?: boolean
}
