/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * The VoucherBook Complete API
 * Complete API documentation including public, admin, and internal endpoints
 * OpenAPI spec version: 1.0.0
 */
import type { SocialLoginBodyProvider } from './socialLoginBodyProvider'
import type { SocialLoginBodyDeviceInfo } from './socialLoginBodyDeviceInfo'

/**
 * Request to authenticate via social provider
 */
export type SocialLoginBody = {
  /** Social auth provider */
  provider: SocialLoginBodyProvider
  /**
   * Firebase ID token from social provider
   * @minLength 1
   */
  idToken: string
  /** Provider access token (optional) */
  accessToken?: string
  /** Device information for tracking */
  deviceInfo?: SocialLoginBodyDeviceInfo
  /** Marketing consent */
  marketingConsent?: boolean
}
