/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * The VoucherBook Complete API
 * Complete API documentation including public, admin, and internal endpoints
 * OpenAPI spec version: 1.0.0
 */

/**
 * Token type
 */
export type SocialLoginResponseTokenType =
  (typeof SocialLoginResponseTokenType)[keyof typeof SocialLoginResponseTokenType]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const SocialLoginResponseTokenType = {
  Bearer: 'Bearer',
} as const
