/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * The VoucherBook Complete API
 * Complete API documentation including public, admin, and internal endpoints
 * OpenAPI spec version: 1.0.0
 */

/**
 * User role in the system
 */
export type SocialLoginResponseUserRole =
  (typeof SocialLoginResponseUserRole)[keyof typeof SocialLoginResponseUserRole]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const SocialLoginResponseUserRole = {
  admin: 'admin',
  customer: 'customer',
  business: 'business',
} as const
