/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * The VoucherBook Complete API
 * Complete API documentation including public, admin, and internal endpoints
 * OpenAPI spec version: 1.0.0
 */

/**
 * Type of device used for authentication
 */
export type SocialLoginBodyDeviceInfoDeviceType =
  (typeof SocialLoginBodyDeviceInfoDeviceType)[keyof typeof SocialLoginBodyDeviceInfoDeviceType]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const SocialLoginBodyDeviceInfoDeviceType = {
  ios: 'ios',
  android: 'android',
  web: 'web',
  desktop: 'desktop',
} as const
