/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Pika Complete API
 * Complete API documentation including public, admin, and internal endpoints
 * OpenAPI spec version: 1.0.0
 */

/**
 * System health status
 */
export type StorageServiceHealthCheckProvidersStatusLocal =
  (typeof StorageServiceHealthCheckProvidersStatusLocal)[keyof typeof StorageServiceHealthCheckProvidersStatusLocal]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const StorageServiceHealthCheckProvidersStatusLocal = {
  healthy: 'healthy',
  degraded: 'degraded',
  unhealthy: 'unhealthy',
} as const
