/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Pika Complete API
 * Complete API documentation including public, admin, and internal endpoints
 * OpenAPI spec version: 1.0.0
 */

/**
 * Internal subscription data
 */
export interface StripeSubscriptionResponse {
  /** Universally Unique Identifier */
  id: string
  userId: string
  stripeSubscriptionId: string
  /** Universally Unique Identifier */
  planId: string
  planName: string
  status: string
  /** ISO 8601 datetime with timezone */
  currentPeriodStart?: string
  /** ISO 8601 datetime with timezone */
  currentPeriodEnd?: string
  cancelAtPeriodEnd: boolean
  /** ISO 8601 datetime with timezone */
  createdAt: string
  /** ISO 8601 datetime with timezone */
  updatedAt: string
}
