/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Pika Complete API
 * Complete API documentation including public, admin, and internal endpoints
 * OpenAPI spec version: 1.0.0
 */
import type { StripeWebhookEventOneOfOneonezeroDataObjectDataObjectType } from './stripeWebhookEventOneOfOneonezeroDataObjectDataObjectType'
import type { StripeWebhookEventOneOfOneonezeroDataObjectDataCustomer } from './stripeWebhookEventOneOfOneonezeroDataObjectDataCustomer'
import type { StripeWebhookEventOneOfOneonezeroDataObjectDataPaymentIntent } from './stripeWebhookEventOneOfOneonezeroDataObjectDataPaymentIntent'
import type { StripeWebhookEventOneOfOneonezeroDataObjectDataSubscription } from './stripeWebhookEventOneOfOneonezeroDataObjectDataSubscription'
import type { StripeWebhookEventOneOfOneonezeroDataObjectDataAmountTotal } from './stripeWebhookEventOneOfOneonezeroDataObjectDataAmountTotal'
import type { StripeWebhookEventOneOfOneonezeroDataObjectDataCurrency } from './stripeWebhookEventOneOfOneonezeroDataObjectDataCurrency'
import type { StripeWebhookEventOneOfOneonezeroDataObjectDataMetadata } from './stripeWebhookEventOneOfOneonezeroDataObjectDataMetadata'
import type { StripeWebhookEventOneOfOneonezeroDataObjectDataPaymentStatus } from './stripeWebhookEventOneOfOneonezeroDataObjectDataPaymentStatus'

export type StripeWebhookEventOneOfOneonezeroDataObjectData = {
  id: string
  objectType: StripeWebhookEventOneOfOneonezeroDataObjectDataObjectType
  customer: StripeWebhookEventOneOfOneonezeroDataObjectDataCustomer
  payment_intent: StripeWebhookEventOneOfOneonezeroDataObjectDataPaymentIntent
  subscription: StripeWebhookEventOneOfOneonezeroDataObjectDataSubscription
  amount_total: StripeWebhookEventOneOfOneonezeroDataObjectDataAmountTotal
  /**
   * @minLength 3
   * @maxLength 3
   */
  currency: StripeWebhookEventOneOfOneonezeroDataObjectDataCurrency
  metadata?: StripeWebhookEventOneOfOneonezeroDataObjectDataMetadata
  payment_status: StripeWebhookEventOneOfOneonezeroDataObjectDataPaymentStatus
}
