/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Pika Complete API
 * Complete API documentation including public, admin, and internal endpoints
 * OpenAPI spec version: 1.0.0
 */
import type { StripeWebhookEventOneOfSevenzeroDataObjectDataObjectType } from './stripeWebhookEventOneOfSevenzeroDataObjectDataObjectType'
import type { StripeWebhookEventOneOfSevenzeroDataObjectDataSubscription } from './stripeWebhookEventOneOfSevenzeroDataObjectDataSubscription'
import type { StripeWebhookEventOneOfSevenzeroDataObjectDataStatus } from './stripeWebhookEventOneOfSevenzeroDataObjectDataStatus'
import type { StripeWebhookEventOneOfSevenzeroDataObjectDataMetadata } from './stripeWebhookEventOneOfSevenzeroDataObjectDataMetadata'

export type StripeWebhookEventOneOfSevenzeroDataObjectData = {
  id: string
  objectType: StripeWebhookEventOneOfSevenzeroDataObjectDataObjectType
  customer: string
  subscription: StripeWebhookEventOneOfSevenzeroDataObjectDataSubscription
  amount_paid: number
  amount_due: number
  /**
   * @minLength 3
   * @maxLength 3
   */
  currency: string
  status: StripeWebhookEventOneOfSevenzeroDataObjectDataStatus
  metadata?: StripeWebhookEventOneOfSevenzeroDataObjectDataMetadata
}
