/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Pika Complete API
 * Complete API documentation including public, admin, and internal endpoints
 * OpenAPI spec version: 1.0.0
 */
import type { StripeWebhookEventOneOfFoureightDataObjectDataObjectType } from './stripeWebhookEventOneOfFoureightDataObjectDataObjectType'
import type { StripeWebhookEventOneOfFoureightDataObjectDataStatus } from './stripeWebhookEventOneOfFoureightDataObjectDataStatus'
import type { StripeWebhookEventOneOfFoureightDataObjectDataMetadata } from './stripeWebhookEventOneOfFoureightDataObjectDataMetadata'

export type StripeWebhookEventOneOfFoureightDataObjectData = {
  id: string
  objectType: StripeWebhookEventOneOfFoureightDataObjectDataObjectType
  customer: string
  status: StripeWebhookEventOneOfFoureightDataObjectDataStatus
  current_period_start: number
  current_period_end: number
  metadata?: StripeWebhookEventOneOfFoureightDataObjectDataMetadata
}
