/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Pika Complete API
 * Complete API documentation including public, admin, and internal endpoints
 * OpenAPI spec version: 1.0.0
 */
import type { StripeWebhookEventOneOfSevenzeroType } from './stripeWebhookEventOneOfSevenzeroType'
import type { StripeWebhookEventOneOfSevenzeroData } from './stripeWebhookEventOneOfSevenzeroData'
import type { StripeWebhookEventOneOfSevenzeroRequest } from './stripeWebhookEventOneOfSevenzeroRequest'

export type StripeWebhookEventOneOfSevenzero = {
  id: string
  type: StripeWebhookEventOneOfSevenzeroType
  data: StripeWebhookEventOneOfSevenzeroData
  created: number
  livemode: boolean
  pending_webhooks: number
  request: StripeWebhookEventOneOfSevenzeroRequest
}
