/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * The VoucherBook Complete API
 * Complete API documentation including public, admin, and internal endpoints
 * OpenAPI spec version: 1.0.0
 */
import type { StripeWebhookEventOneOfFivenineType } from './stripeWebhookEventOneOfFivenineType'
import type { StripeWebhookEventOneOfFivenineData } from './stripeWebhookEventOneOfFivenineData'
import type { StripeWebhookEventOneOfFivenineRequest } from './stripeWebhookEventOneOfFivenineRequest'

export type StripeWebhookEventOneOfFivenine = {
  id: string
  type: StripeWebhookEventOneOfFivenineType
  data: StripeWebhookEventOneOfFivenineData
  created: number
  livemode: boolean
  pending_webhooks: number
  request: StripeWebhookEventOneOfFivenineRequest
}
