/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * The VoucherBook Complete API
 * Complete API documentation including public, admin, and internal endpoints
 * OpenAPI spec version: 1.0.0
 */
import type { StripeWebhookEventOneOfNinefourDataObjectDataObjectType } from './stripeWebhookEventOneOfNinefourDataObjectDataObjectType'
import type { StripeWebhookEventOneOfNinefourDataObjectDataCustomer } from './stripeWebhookEventOneOfNinefourDataObjectDataCustomer'
import type { StripeWebhookEventOneOfNinefourDataObjectDataPaymentIntent } from './stripeWebhookEventOneOfNinefourDataObjectDataPaymentIntent'
import type { StripeWebhookEventOneOfNinefourDataObjectDataSubscription } from './stripeWebhookEventOneOfNinefourDataObjectDataSubscription'
import type { StripeWebhookEventOneOfNinefourDataObjectDataAmountTotal } from './stripeWebhookEventOneOfNinefourDataObjectDataAmountTotal'
import type { StripeWebhookEventOneOfNinefourDataObjectDataCurrency } from './stripeWebhookEventOneOfNinefourDataObjectDataCurrency'
import type { StripeWebhookEventOneOfNinefourDataObjectDataMetadata } from './stripeWebhookEventOneOfNinefourDataObjectDataMetadata'
import type { StripeWebhookEventOneOfNinefourDataObjectDataPaymentStatus } from './stripeWebhookEventOneOfNinefourDataObjectDataPaymentStatus'

export type StripeWebhookEventOneOfNinefourDataObjectData = {
  id: string
  objectType: StripeWebhookEventOneOfNinefourDataObjectDataObjectType
  customer: StripeWebhookEventOneOfNinefourDataObjectDataCustomer
  payment_intent: StripeWebhookEventOneOfNinefourDataObjectDataPaymentIntent
  subscription: StripeWebhookEventOneOfNinefourDataObjectDataSubscription
  amount_total: StripeWebhookEventOneOfNinefourDataObjectDataAmountTotal
  /**
   * @minLength 3
   * @maxLength 3
   */
  currency: StripeWebhookEventOneOfNinefourDataObjectDataCurrency
  metadata?: StripeWebhookEventOneOfNinefourDataObjectDataMetadata
  payment_status: StripeWebhookEventOneOfNinefourDataObjectDataPaymentStatus
}
