/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Pika Complete API
 * Complete API documentation including public, admin, and internal endpoints
 * OpenAPI spec version: 1.0.0
 */
import type { StripeWebhookEventOneOfEighttwoType } from './stripeWebhookEventOneOfEighttwoType'
import type { StripeWebhookEventOneOfEighttwoData } from './stripeWebhookEventOneOfEighttwoData'
import type { StripeWebhookEventOneOfEighttwoRequest } from './stripeWebhookEventOneOfEighttwoRequest'

export type StripeWebhookEventOneOfEighttwo = {
  id: string
  type: StripeWebhookEventOneOfEighttwoType
  data: StripeWebhookEventOneOfEighttwoData
  created: number
  livemode: boolean
  pending_webhooks: number
  request: StripeWebhookEventOneOfEighttwoRequest
}
