/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Pika Complete API
 * Complete API documentation including public, admin, and internal endpoints
 * OpenAPI spec version: 1.0.0
 */
import type { StripeWebhookEventOneOf } from './stripeWebhookEventOneOf'
import type { StripeWebhookEventOneOfOnethree } from './stripeWebhookEventOneOfOnethree'
import type { StripeWebhookEventOneOfTwofive } from './stripeWebhookEventOneOfTwofive'
import type { StripeWebhookEventOneOfThreeseven } from './stripeWebhookEventOneOfThreeseven'
import type { StripeWebhookEventOneOfFoureight } from './stripeWebhookEventOneOfFoureight'
import type { StripeWebhookEventOneOfFivenine } from './stripeWebhookEventOneOfFivenine'
import type { StripeWebhookEventOneOfSevenzero } from './stripeWebhookEventOneOfSevenzero'
import type { StripeWebhookEventOneOfEighttwo } from './stripeWebhookEventOneOfEighttwo'
import type { StripeWebhookEventOneOfNinefour } from './stripeWebhookEventOneOfNinefour'
import type { StripeWebhookEventOneOfOneonezero } from './stripeWebhookEventOneOfOneonezero'

export type StripeWebhookEvent =
  | StripeWebhookEventOneOf
  | StripeWebhookEventOneOfOnethree
  | StripeWebhookEventOneOfTwofive
  | StripeWebhookEventOneOfThreeseven
  | StripeWebhookEventOneOfFoureight
  | StripeWebhookEventOneOfFivenine
  | StripeWebhookEventOneOfSevenzero
  | StripeWebhookEventOneOfEighttwo
  | StripeWebhookEventOneOfNinefour
  | StripeWebhookEventOneOfOneonezero
