/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Pika Complete API
 * Complete API documentation including public, admin, and internal endpoints
 * OpenAPI spec version: 1.0.0
 */
import type { StripeWebhookEventOneOfDataObjectDataObjectType } from './stripeWebhookEventOneOfDataObjectDataObjectType'
import type { StripeWebhookEventOneOfDataObjectDataCustomer } from './stripeWebhookEventOneOfDataObjectDataCustomer'
import type { StripeWebhookEventOneOfDataObjectDataMetadata } from './stripeWebhookEventOneOfDataObjectDataMetadata'
import type { StripeWebhookEventOneOfDataObjectDataStatus } from './stripeWebhookEventOneOfDataObjectDataStatus'

export type StripeWebhookEventOneOfDataObjectData = {
  id: string
  objectType: StripeWebhookEventOneOfDataObjectDataObjectType
  /** */
  amount: number
  /**
   * @minLength 3
   * @maxLength 3
   */
  currency: string
  customer: StripeWebhookEventOneOfDataObjectDataCustomer
  metadata?: StripeWebhookEventOneOfDataObjectDataMetadata
  status: StripeWebhookEventOneOfDataObjectDataStatus
  created: number
}
