/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * The VoucherBook Complete API
 * Complete API documentation including public, admin, and internal endpoints
 * OpenAPI spec version: 1.0.0
 */

export type StripeWebhookEventOneOfOnethreeType =
  (typeof StripeWebhookEventOneOfOnethreeType)[keyof typeof StripeWebhookEventOneOfOnethreeType]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const StripeWebhookEventOneOfOnethreeType = {
  payment_intentpayment_failed: 'payment_intent.payment_failed',
} as const
