/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * The VoucherBook Complete API
 * Complete API documentation including public, admin, and internal endpoints
 * OpenAPI spec version: 1.0.0
 */
import type { StripeWebhookEventOneOfEighttwoDataObjectDataObjectType } from './stripeWebhookEventOneOfEighttwoDataObjectDataObjectType'
import type { StripeWebhookEventOneOfEighttwoDataObjectDataSubscription } from './stripeWebhookEventOneOfEighttwoDataObjectDataSubscription'
import type { StripeWebhookEventOneOfEighttwoDataObjectDataStatus } from './stripeWebhookEventOneOfEighttwoDataObjectDataStatus'
import type { StripeWebhookEventOneOfEighttwoDataObjectDataMetadata } from './stripeWebhookEventOneOfEighttwoDataObjectDataMetadata'

export type StripeWebhookEventOneOfEighttwoDataObjectData = {
  id: string
  objectType: StripeWebhookEventOneOfEighttwoDataObjectDataObjectType
  customer: string
  subscription: StripeWebhookEventOneOfEighttwoDataObjectDataSubscription
  amount_paid: number
  amount_due: number
  /**
   * @minLength 3
   * @maxLength 3
   */
  currency: string
  status: StripeWebhookEventOneOfEighttwoDataObjectDataStatus
  metadata?: StripeWebhookEventOneOfEighttwoDataObjectDataMetadata
}
