/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Pika Complete API
 * Complete API documentation including public, admin, and internal endpoints
 * OpenAPI spec version: 1.0.0
 */
import type { StripeWebhookEventOneOfOneonezeroType } from './stripeWebhookEventOneOfOneonezeroType'
import type { StripeWebhookEventOneOfOneonezeroData } from './stripeWebhookEventOneOfOneonezeroData'
import type { StripeWebhookEventOneOfOneonezeroRequest } from './stripeWebhookEventOneOfOneonezeroRequest'

export type StripeWebhookEventOneOfOneonezero = {
  id: string
  type: StripeWebhookEventOneOfOneonezeroType
  data: StripeWebhookEventOneOfOneonezeroData
  created: number
  livemode: boolean
  pending_webhooks: number
  request: StripeWebhookEventOneOfOneonezeroRequest
}
