/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * The VoucherBook Complete API
 * Complete API documentation including public, admin, and internal endpoints
 * OpenAPI spec version: 1.0.0
 */
import type { StripeWebhookEventOneOfNinefourType } from './stripeWebhookEventOneOfNinefourType'
import type { StripeWebhookEventOneOfNinefourData } from './stripeWebhookEventOneOfNinefourData'
import type { StripeWebhookEventOneOfNinefourRequest } from './stripeWebhookEventOneOfNinefourRequest'

export type StripeWebhookEventOneOfNinefour = {
  id: string
  type: StripeWebhookEventOneOfNinefourType
  data: StripeWebhookEventOneOfNinefourData
  created: number
  livemode: boolean
  pending_webhooks: number
  request: StripeWebhookEventOneOfNinefourRequest
}
