/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Pika Complete API
 * Complete API documentation including public, admin, and internal endpoints
 * OpenAPI spec version: 1.0.0
 */

export type StripeWebhookEventOneOfEighttwoDataObjectDataStatus =
  (typeof StripeWebhookEventOneOfEighttwoDataObjectDataStatus)[keyof typeof StripeWebhookEventOneOfEighttwoDataObjectDataStatus]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const StripeWebhookEventOneOfEighttwoDataObjectDataStatus = {
  draft: 'draft',
  open: 'open',
  paid: 'paid',
  uncollectible: 'uncollectible',
  void: 'void',
} as const
