/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Pika Complete API
 * Complete API documentation including public, admin, and internal endpoints
 * OpenAPI spec version: 1.0.0
 */
import type { SubmitBusinessRegistrationStep1200Step1Data } from './submitBusinessRegistrationStep1200Step1Data'
import type { SubmitBusinessRegistrationStep1200Step2Data } from './submitBusinessRegistrationStep1200Step2Data'
import type { SubmitBusinessRegistrationStep1200Step3Data } from './submitBusinessRegistrationStep1200Step3Data'
import type { SubmitBusinessRegistrationStep1200RegistrationStatus } from './submitBusinessRegistrationStep1200RegistrationStatus'

export type SubmitBusinessRegistrationStep1200 = {
  /** Registration ID */
  id: string
  /** User ID */
  userId: string
  /** Current step number */
  currentStep: number
  /** List of completed step numbers */
  stepsCompleted: number[]
  step1Data?: SubmitBusinessRegistrationStep1200Step1Data
  step2Data?: SubmitBusinessRegistrationStep1200Step2Data
  step3Data?: SubmitBusinessRegistrationStep1200Step3Data
  /** Current registration status */
  registrationStatus: SubmitBusinessRegistrationStep1200RegistrationStatus
  /** Business ID if created */
  businessId?: string
  /** When the record was created */
  createdAt: string
  /** When the record was last updated */
  updatedAt: string
}
