/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * The VoucherBook Complete API
 * Complete API documentation including public, admin, and internal endpoints
 * OpenAPI spec version: 1.0.0
 */
import type { SubmitBusinessRegistrationStep1BodyBusinessType } from './submitBusinessRegistrationStep1BodyBusinessType'

export type SubmitBusinessRegistrationStep1Body = {
  /**
   * Business name
   * @minLength 1
   * @maxLength 100
   */
  businessName: string
  /** Type of business */
  businessType: SubmitBusinessRegistrationStep1BodyBusinessType
  /** Category ID */
  categoryId: string
  /**
   * Primary language code
   * @minLength 2
   * @maxLength 2
   * @pattern ^[a-z]{2}$
   */
  primaryLanguage: string
}
