/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Pika Complete API
 * Complete API documentation including public, admin, and internal endpoints
 * OpenAPI spec version: 1.0.0
 */

/**
 * Subscription event type for webhooks and notifications
 */
export type SubscriptionWebhookEventEventType =
  (typeof SubscriptionWebhookEventEventType)[keyof typeof SubscriptionWebhookEventEventType]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const SubscriptionWebhookEventEventType = {
  customersubscriptioncreated: 'customer.subscription.created',
  customersubscriptionupdated: 'customer.subscription.updated',
  customersubscriptiondeleted: 'customer.subscription.deleted',
  customersubscriptiontrial_will_end: 'customer.subscription.trial_will_end',
  invoicepayment_failed: 'invoice.payment_failed',
  invoicepayment_succeeded: 'invoice.payment_succeeded',
  created: 'created',
  cancelled: 'cancelled',
  paymentFailed: 'paymentFailed',
  creditsAllocated: 'creditsAllocated',
  renewalReminder: 'renewalReminder',
  trialEnding: 'trialEnding',
} as const
