/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * The VoucherBook Complete API
 * Complete API documentation including public, admin, and internal endpoints
 * OpenAPI spec version: 1.0.0
 */
import type { SubscriptionPlanSearchParamsSortOrder } from './subscriptionPlanSearchParamsSortOrder'
import type { SubscriptionPlanSearchParamsBillingInterval } from './subscriptionPlanSearchParamsBillingInterval'

export interface SubscriptionPlanSearchParams {
  /**
   * Page number
   */
  page?: number
  /**
   * Items per page
   * @maximum 100
   */
  limit?: number
  /** Field to sort by */
  sortBy?: string
  /** Sort order */
  sortOrder?: SubscriptionPlanSearchParamsSortOrder
  /** Search query */
  search?: string
  billingInterval?: SubscriptionPlanSearchParamsBillingInterval
  isActive?: boolean
  isPublic?: boolean
  /** @minimum 0 */
  minPrice?: number
  /** @minimum 0 */
  maxPrice?: number
  createdBy?: string
}
