/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * The VoucherBook Complete API
 * Complete API documentation including public, admin, and internal endpoints
 * OpenAPI spec version: 1.0.0
 */

/**
 * Billing interval for subscriptions
 */
export type SubscriptionPlanDetailResponseInterval =
  (typeof SubscriptionPlanDetailResponseInterval)[keyof typeof SubscriptionPlanDetailResponseInterval]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const SubscriptionPlanDetailResponseInterval = {
  day: 'day',
  week: 'week',
  month: 'month',
  year: 'year',
} as const
