/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * The VoucherBook Complete API
 * Complete API documentation including public, admin, and internal endpoints
 * OpenAPI spec version: 1.0.0
 */
import type { SubscriptionPlanQueryParamsSortBy } from './subscriptionPlanQueryParamsSortBy'
import type { SubscriptionPlanQueryParamsSortOrder } from './subscriptionPlanQueryParamsSortOrder'
import type { SubscriptionPlanQueryParamsIsActive } from './subscriptionPlanQueryParamsIsActive'
import type { SubscriptionPlanQueryParamsInterval } from './subscriptionPlanQueryParamsInterval'
import type { SubscriptionPlanQueryParamsPlanType } from './subscriptionPlanQueryParamsPlanType'

export interface SubscriptionPlanQueryParams {
  /**
   * Page number
   */
  page?: number
  /**
   * Items per page
   * @maximum 100
   */
  limit?: number
  /** Field to sort plans by */
  sortBy?: SubscriptionPlanQueryParamsSortBy
  /** Sort order */
  sortOrder?: SubscriptionPlanQueryParamsSortOrder
  /** Search query */
  search?: string
  isActive?: SubscriptionPlanQueryParamsIsActive
  /** Billing interval for subscriptions */
  interval?: SubscriptionPlanQueryParamsInterval
  /** Plan type category */
  planType?: SubscriptionPlanQueryParamsPlanType
}
