/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Pika Complete API
 * Complete API documentation including public, admin, and internal endpoints
 * OpenAPI spec version: 1.0.0
 */

/**
 * Sort order
 */
export type SubscriptionPlanQueryParamsSortOrder =
  (typeof SubscriptionPlanQueryParamsSortOrder)[keyof typeof SubscriptionPlanQueryParamsSortOrder]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const SubscriptionPlanQueryParamsSortOrder = {
  asc: 'asc',
  desc: 'desc',
} as const
