/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * The VoucherBook Complete API
 * Complete API documentation including public, admin, and internal endpoints
 * OpenAPI spec version: 1.0.0
 */

export type SubscriptionCheckResponseSubscription = {
  /** Universally Unique Identifier */
  id: string
  /** Universally Unique Identifier */
  planId: string
  planName: string
  status: string
  features: string[]
}
