/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Pika Complete API
 * Complete API documentation including public, admin, and internal endpoints
 * OpenAPI spec version: 1.0.0
 */
import type { SubscriptionPlanDetailResponseInterval } from './subscriptionPlanDetailResponseInterval'
import type { SubscriptionPlanDetailResponseMetadata } from './subscriptionPlanDetailResponseMetadata'

/**
 * Single subscription plan details
 */
export interface SubscriptionPlanDetailResponse {
  /** Universally Unique Identifier */
  id: string
  /** Name of the subscription plan */
  name: string
  /** Description of the subscription plan */
  description?: string
  /**
   * Price per billing period
   * @minimum 0
   */
  price: number
  /**
   * Currency code (e.g., usd, gbp)
   * @minLength 3
   * @maxLength 3
   */
  currency?: string
  /** Billing interval for subscriptions */
  interval: SubscriptionPlanDetailResponseInterval
  /**
   * Number of intervals between billings
   */
  intervalCount?: number
  /**
   * Number of trial days
   * @minimum 0
   */
  trialPeriodDays?: number
  /** Array of feature descriptions */
  features: string[]
  /** Additional configuration */
  metadata?: SubscriptionPlanDetailResponseMetadata
  /** Stripe product ID */
  stripeProductId?: string
  /** Stripe price ID */
  stripePriceId?: string
  /** When the record was created */
  createdAt: string
  /** When the record was last updated */
  updatedAt: string
  /** Whether the record is active */
  isActive?: boolean
}
