/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Pika Complete API
 * Complete API documentation including public, admin, and internal endpoints
 * OpenAPI spec version: 1.0.0
 */

/**
 * Subscription status
 */
export type SubscriptionResponseStatus =
  (typeof SubscriptionResponseStatus)[keyof typeof SubscriptionResponseStatus]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const SubscriptionResponseStatus = {
  active: 'active',
  canceled: 'canceled',
  incomplete: 'incomplete',
  incompleteExpired: 'incompleteExpired',
  pastDue: 'pastDue',
  trialing: 'trialing',
  unpaid: 'unpaid',
} as const
