/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * The VoucherBook Complete API
 * Complete API documentation including public, admin, and internal endpoints
 * OpenAPI spec version: 1.0.0
 */

/**
 * Field to sort comments by
 */
export type SupportCommentSearchParamsSortBy =
  (typeof SupportCommentSearchParamsSortBy)[keyof typeof SupportCommentSearchParamsSortBy]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const SupportCommentSearchParamsSortBy = {
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
} as const
