/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Pika Complete API
 * Complete API documentation including public, admin, and internal endpoints
 * OpenAPI spec version: 1.0.0
 */
import type { SupportCommentSearchParamsSortBy } from './supportCommentSearchParamsSortBy'
import type { SupportCommentSearchParamsSortOrder } from './supportCommentSearchParamsSortOrder'

export interface SupportCommentSearchParams {
  /**
   * Page number
   */
  page?: number
  /**
   * Items per page
   * @maximum 100
   */
  limit?: number
  /** Field to sort comments by */
  sortBy?: SupportCommentSearchParamsSortBy
  /** Sort order - ascending (asc) or descending (desc) */
  sortOrder?: SupportCommentSearchParamsSortOrder
  /** Search query */
  search?: string
}
