/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Pika Complete API
 * Complete API documentation including public, admin, and internal endpoints
 * OpenAPI spec version: 1.0.0
 */

/**
 * Support ticket category/type
 */
export type SupportProblemListResponseDataItemType =
  (typeof SupportProblemListResponseDataItemType)[keyof typeof SupportProblemListResponseDataItemType]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const SupportProblemListResponseDataItemType = {
  billing: 'billing',
  technical: 'technical',
  account: 'account',
  general: 'general',
  bug_report: 'bug_report',
  feature_request: 'feature_request',
} as const
