/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Pika Complete API
 * Complete API documentation including public, admin, and internal endpoints
 * OpenAPI spec version: 1.0.0
 */

export type TicketStatsResponseAgentStatsItem = {
  agentId: string
  agentName: string
  /** @minimum 0 */
  ticketsHandled: number
  averageResponseTime: number
  averageResolutionTime: number
  /**
   * @minimum 0
   * @maximum 5
   */
  satisfactionScore?: number
}
