/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Pika Complete API
 * Complete API documentation including public, admin, and internal endpoints
 * OpenAPI spec version: 1.0.0
 */
import type { TokenResponseUserRole } from './tokenResponseUserRole'

/**
 * User information for password grant
 */
export type TokenResponseUser = {
  id: string
  /** @minLength 1 */
  email: string
  firstName: string
  lastName: string
  profilePicture?: string
  /** User role in the system */
  role: TokenResponseUserRole
}
