/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * The VoucherBook Complete API
 * Complete API documentation including public, admin, and internal endpoints
 * OpenAPI spec version: 1.0.0
 */
import type { TokenValidationResponseMetadata } from './tokenValidationResponseMetadata'

/**
 * Token validation result
 */
export interface TokenValidationResponse {
  valid: boolean
  userId?: string
  /** @minLength 1 */
  email?: string
  roles: string[]
  permissions: string[]
  /** ISO 8601 datetime with timezone */
  expiresAt?: string
  metadata?: TokenValidationResponseMetadata
}
