/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Pika Complete API
 * Complete API documentation including public, admin, and internal endpoints
 * OpenAPI spec version: 1.0.0
 */

export type UpdateUserSettings200SettingsNotificationsEmail = {
  enabled: boolean
  marketing: boolean
  productUpdates: boolean
  securityAlerts: boolean
  voucherExpiry: boolean
  businessUpdates: boolean
}
