/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Pika Complete API
 * Complete API documentation including public, admin, and internal endpoints
 * OpenAPI spec version: 1.0.0
 */

/**
 * Fields that can be updated by the user
 */
export type UpdateUserProfileBody = {
  /** @maxLength 50 */
  firstName?: string
  /** @maxLength 50 */
  lastName?: string
  /** @maxLength 100 */
  displayName?: string
  /**
   * Phone number in E.164 format
   * @pattern ^\+[1-9]\d{1,14}$
   */
  phoneNumber?: string
  /** @maxLength 500 */
  bio?: string
  /**
   * Date in YYYY-MM-DD format
   * @pattern ^\d{4}-\d{2}-\d{2}$
   */
  dateOfBirth?: string
  /**
   * @minLength 2
   * @maxLength 2
   * @pattern ^[a-z]{2}$
   */
  preferredLanguage?: string
}
