/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Pika Complete API
 * Complete API documentation including public, admin, and internal endpoints
 * OpenAPI spec version: 1.0.0
 */

/**
 * Status of voucher from customer perspective
 */
export type UpdateAdminVoucher200CustomerVouchersItemStatus =
  (typeof UpdateAdminVoucher200CustomerVouchersItemStatus)[keyof typeof UpdateAdminVoucher200CustomerVouchersItemStatus]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UpdateAdminVoucher200CustomerVouchersItemStatus = {
  available: 'available',
  claimed: 'claimed',
  redeemed: 'redeemed',
  expired: 'expired',
} as const
