/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * The VoucherBook Complete API
 * Complete API documentation including public, admin, and internal endpoints
 * OpenAPI spec version: 1.0.0
 */
import type { UpdateAdminVoucherState200CodesItemMetadataAnyOf } from './updateAdminVoucherState200CodesItemMetadataAnyOf'

export type UpdateAdminVoucherState200CodesItemMetadata =
  UpdateAdminVoucherState200CodesItemMetadataAnyOf | null
