/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Pika Complete API
 * Complete API documentation including public, admin, and internal endpoints
 * OpenAPI spec version: 1.0.0
 */

/**
 * Universally Unique Identifier
 */
export type UpdateAdminVoucherState200ScansItemUserId = string | null
