/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Pika Complete API
 * Complete API documentation including public, admin, and internal endpoints
 * OpenAPI spec version: 1.0.0
 */
import type { UpdateUserSettings200SettingsPrivacyProfileVisibility } from './updateUserSettings200SettingsPrivacyProfileVisibility'

export type UpdateUserSettings200SettingsPrivacyProfile = {
  visibility: UpdateUserSettings200SettingsPrivacyProfileVisibility
  showEmail: boolean
  showPhone: boolean
  showBirthDate: boolean
}
