/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Pika Complete API
 * Complete API documentation including public, admin, and internal endpoints
 * OpenAPI spec version: 1.0.0
 */
import type { UpdateUserSettingsRequestPrivacyProfile } from './updateUserSettingsRequestPrivacyProfile'
import type { UpdateUserSettingsRequestPrivacySearch } from './updateUserSettingsRequestPrivacySearch'
import type { UpdateUserSettingsRequestPrivacyAnalytics } from './updateUserSettingsRequestPrivacyAnalytics'
import type { UpdateUserSettingsRequestPrivacyMarketing } from './updateUserSettingsRequestPrivacyMarketing'

export type UpdateUserSettingsRequestPrivacy = {
  profile: UpdateUserSettingsRequestPrivacyProfile
  search: UpdateUserSettingsRequestPrivacySearch
  analytics: UpdateUserSettingsRequestPrivacyAnalytics
  marketing: UpdateUserSettingsRequestPrivacyMarketing
}
