/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * The VoucherBook Complete API
 * Complete API documentation including public, admin, and internal endpoints
 * OpenAPI spec version: 1.0.0
 */
import type { UpdateAdminVoucher200RedemptionsItemMetadataAnyOf } from './updateAdminVoucher200RedemptionsItemMetadataAnyOf'

export type UpdateAdminVoucher200RedemptionsItemMetadata =
  UpdateAdminVoucher200RedemptionsItemMetadataAnyOf | null
