/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * The VoucherBook Complete API
 * Complete API documentation including public, admin, and internal endpoints
 * OpenAPI spec version: 1.0.0
 */

/**
 * Voucher book status
 */
export type UpdateAdminVoucherBook200Status =
  (typeof UpdateAdminVoucherBook200Status)[keyof typeof UpdateAdminVoucherBook200Status]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UpdateAdminVoucherBook200Status = {
  draft: 'draft',
  readyForPrint: 'readyForPrint',
  published: 'published',
  archived: 'archived',
} as const
