/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Pika Complete API
 * Complete API documentation including public, admin, and internal endpoints
 * OpenAPI spec version: 1.0.0
 */

/**
 * Update business rating data
 */
export type UpdateAdminBusinessRatingBody = {
  /**
   * New rating value for the business
   * @minimum 0
   * @maximum 5
   */
  rating: number
}
