/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Pika Complete API
 * Complete API documentation including public, admin, and internal endpoints
 * OpenAPI spec version: 1.0.0
 */
import type { UpdateAdminProblemBodyPriority } from './updateAdminProblemBodyPriority'
import type { UpdateAdminProblemBodyType } from './updateAdminProblemBodyType'
import type { UpdateAdminProblemBodyStatus } from './updateAdminProblemBodyStatus'

/**
 * Admin update support problem
 */
export type UpdateAdminProblemBody = {
  /**
   * @minLength 1
   * @maxLength 200
   */
  title?: string
  /**
   * @minLength 1
   * @maxLength 5000
   */
  description?: string
  /** Support ticket priority level */
  priority?: UpdateAdminProblemBodyPriority
  /** Support ticket category/type */
  type?: UpdateAdminProblemBodyType
  /** Support ticket status */
  status?: UpdateAdminProblemBodyStatus
  assignedTo?: string
  /** ISO 8601 datetime with timezone */
  resolvedAt?: string
  files?: string[]
}
