/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * The VoucherBook Complete API
 * Complete API documentation including public, admin, and internal endpoints
 * OpenAPI spec version: 1.0.0
 */
import type { UpdateAdminVoucherState200LocationAnyOfType } from './updateAdminVoucherState200LocationAnyOfType'

export type UpdateAdminVoucherState200LocationAnyOf = {
  type: UpdateAdminVoucherState200LocationAnyOfType
  /** [longitude, latitude] - GeoJSON standard */
  coordinates: [number, number]
}
