/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * The VoucherBook Complete API
 * Complete API documentation including public, admin, and internal endpoints
 * OpenAPI spec version: 1.0.0
 */

/**
 * Subscription status
 */
export type UpdateStripeSubscriptionRequestStatus =
  (typeof UpdateStripeSubscriptionRequestStatus)[keyof typeof UpdateStripeSubscriptionRequestStatus]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UpdateStripeSubscriptionRequestStatus = {
  active: 'active',
  canceled: 'canceled',
  incomplete: 'incomplete',
  incompleteExpired: 'incompleteExpired',
  pastDue: 'pastDue',
  trialing: 'trialing',
  unpaid: 'unpaid',
} as const
