/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Pika Complete API
 * Complete API documentation including public, admin, and internal endpoints
 * OpenAPI spec version: 1.0.0
 */

export type UpdateUserSettingsBodyDisplayTimeFormat =
  (typeof UpdateUserSettingsBodyDisplayTimeFormat)[keyof typeof UpdateUserSettingsBodyDisplayTimeFormat]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UpdateUserSettingsBodyDisplayTimeFormat = {
  '12h': '12h',
  '24h': '24h',
} as const
