/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Pika Complete API
 * Complete API documentation including public, admin, and internal endpoints
 * OpenAPI spec version: 1.0.0
 */

/**
 * Type of voucher code
 */
export type UpdateAdminVoucher200CodesItemType =
  (typeof UpdateAdminVoucher200CodesItemType)[keyof typeof UpdateAdminVoucher200CodesItemType]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UpdateAdminVoucher200CodesItemType = {
  qr: 'qr',
  short: 'short',
  static: 'static',
} as const
