/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Pika Complete API
 * Complete API documentation including public, admin, and internal endpoints
 * OpenAPI spec version: 1.0.0
 */
import type { UpdateSubscriptionPlanRequestMetadata } from './updateSubscriptionPlanRequestMetadata'

/**
 * Update a subscription plan
 */
export interface UpdateSubscriptionPlanRequest {
  name?: string
  description?: string
  /** @minimum 0 */
  price?: number
  /** @minimum 0 */
  trialPeriodDays?: number
  features?: string[]
  isActive?: boolean
  metadata?: UpdateSubscriptionPlanRequestMetadata
  stripePriceId?: string
}
