/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Pika Complete API
 * Complete API documentation including public, admin, and internal endpoints
 * OpenAPI spec version: 1.0.0
 */
import type { UpdateNotificationPreferencesRequestEmail } from './updateNotificationPreferencesRequestEmail'
import type { UpdateNotificationPreferencesRequestInApp } from './updateNotificationPreferencesRequestInApp'
import type { UpdateNotificationPreferencesRequestSms } from './updateNotificationPreferencesRequestSms'
import type { UpdateNotificationPreferencesRequestPush } from './updateNotificationPreferencesRequestPush'
import type { UpdateNotificationPreferencesRequestQuietHours } from './updateNotificationPreferencesRequestQuietHours'

export interface UpdateNotificationPreferencesRequest {
  email?: UpdateNotificationPreferencesRequestEmail
  inApp?: UpdateNotificationPreferencesRequestInApp
  sms?: UpdateNotificationPreferencesRequestSms
  push?: UpdateNotificationPreferencesRequestPush
  quietHours?: UpdateNotificationPreferencesRequestQuietHours
}
