/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * The VoucherBook Complete API
 * Complete API documentation including public, admin, and internal endpoints
 * OpenAPI spec version: 1.0.0
 */
import type { UpdateUserSettingsRequestVersion } from './updateUserSettingsRequestVersion'
import type { UpdateUserSettingsRequestDisplay } from './updateUserSettingsRequestDisplay'
import type { UpdateUserSettingsRequestNotifications } from './updateUserSettingsRequestNotifications'
import type { UpdateUserSettingsRequestPrivacy } from './updateUserSettingsRequestPrivacy'
import type { UpdateUserSettingsRequestBusiness } from './updateUserSettingsRequestBusiness'
import type { UpdateUserSettingsRequestAccessibility } from './updateUserSettingsRequestAccessibility'
import type { UpdateUserSettingsRequestUpdatedAt } from './updateUserSettingsRequestUpdatedAt'

/**
 * Complete user settings object (replaces existing settings)
 */
export interface UpdateUserSettingsRequest {
  version: UpdateUserSettingsRequestVersion
  display: UpdateUserSettingsRequestDisplay
  notifications: UpdateUserSettingsRequestNotifications
  privacy: UpdateUserSettingsRequestPrivacy
  business?: UpdateUserSettingsRequestBusiness
  accessibility: UpdateUserSettingsRequestAccessibility
  updatedAt: UpdateUserSettingsRequestUpdatedAt
}
