/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * The VoucherBook Complete API
 * Complete API documentation including public, admin, and internal endpoints
 * OpenAPI spec version: 1.0.0
 */
import type { UpdateAdminProblem200Type } from './updateAdminProblem200Type'
import type { UpdateAdminProblem200Status } from './updateAdminProblem200Status'
import type { UpdateAdminProblem200Priority } from './updateAdminProblem200Priority'

export type UpdateAdminProblem200 = {
  /** Universally Unique Identifier */
  id: string
  ticketNumber?: string
  userId: string
  userName: string
  userEmail: string
  title: string
  description: string
  /** Support ticket category/type */
  type: UpdateAdminProblem200Type
  /** Support ticket status */
  status: UpdateAdminProblem200Status
  /** Support ticket priority level */
  priority: UpdateAdminProblem200Priority
  /** ISO 8601 datetime with timezone */
  resolvedAt?: string
  assignedTo?: string
  assignedToName?: string
  files?: string[]
  /** When the record was created */
  createdAt: string
  /** When the record was last updated */
  updatedAt: string
}
