/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * The VoucherBook Complete API
 * Complete API documentation including public, admin, and internal endpoints
 * OpenAPI spec version: 1.0.0
 */

export type UpdateUserSettings200SettingsNotificationsPush = {
  enabled: boolean
  marketing: boolean
  voucherExpiry: boolean
  businessUpdates: boolean
  orderUpdates: boolean
}
