/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * The VoucherBook Complete API
 * Complete API documentation including public, admin, and internal endpoints
 * OpenAPI spec version: 1.0.0
 */
import type { UpdateUserSettingsBodyPrivacyProfile } from './updateUserSettingsBodyPrivacyProfile'
import type { UpdateUserSettingsBodyPrivacySearch } from './updateUserSettingsBodyPrivacySearch'
import type { UpdateUserSettingsBodyPrivacyAnalytics } from './updateUserSettingsBodyPrivacyAnalytics'
import type { UpdateUserSettingsBodyPrivacyMarketing } from './updateUserSettingsBodyPrivacyMarketing'

export type UpdateUserSettingsBodyPrivacy = {
  profile: UpdateUserSettingsBodyPrivacyProfile
  search: UpdateUserSettingsBodyPrivacySearch
  analytics: UpdateUserSettingsBodyPrivacyAnalytics
  marketing: UpdateUserSettingsBodyPrivacyMarketing
}
