/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * The VoucherBook Complete API
 * Complete API documentation including public, admin, and internal endpoints
 * OpenAPI spec version: 1.0.0
 */
import type { UpdateUserSettings200SettingsPrivacyProfile } from './updateUserSettings200SettingsPrivacyProfile'
import type { UpdateUserSettings200SettingsPrivacySearch } from './updateUserSettings200SettingsPrivacySearch'
import type { UpdateUserSettings200SettingsPrivacyAnalytics } from './updateUserSettings200SettingsPrivacyAnalytics'
import type { UpdateUserSettings200SettingsPrivacyMarketing } from './updateUserSettings200SettingsPrivacyMarketing'

export type UpdateUserSettings200SettingsPrivacy = {
  profile: UpdateUserSettings200SettingsPrivacyProfile
  search: UpdateUserSettings200SettingsPrivacySearch
  analytics: UpdateUserSettings200SettingsPrivacyAnalytics
  marketing: UpdateUserSettings200SettingsPrivacyMarketing
}
