/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * The VoucherBook Complete API
 * Complete API documentation including public, admin, and internal endpoints
 * OpenAPI spec version: 1.0.0
 */
import type { UpdateAdminBusiness200CategoryId } from './updateAdminBusiness200CategoryId'
import type { UpdateAdminBusiness200ApprovedBy } from './updateAdminBusiness200ApprovedBy'
import type { UpdateAdminBusiness200ApprovedAt } from './updateAdminBusiness200ApprovedAt'
import type { UpdateAdminBusiness200LogoUrl } from './updateAdminBusiness200LogoUrl'
import type { UpdateAdminBusiness200DeletedAt } from './updateAdminBusiness200DeletedAt'
import type { UpdateAdminBusiness200User } from './updateAdminBusiness200User'
import type { UpdateAdminBusiness200Category } from './updateAdminBusiness200Category'
import type { UpdateAdminBusiness200BusinessRegistration } from './updateAdminBusiness200BusinessRegistration'

export type UpdateAdminBusiness200 = {
  /** Universally Unique Identifier */
  id: string
  /** User who owns this business */
  userId: string
  /**
   * Business name (resolved translation)
   * @maxLength 255
   */
  businessName: string
  /**
   * Business description (resolved translation)
   * @maxLength 255
   */
  businessDescription?: string
  /** Category this business belongs to */
  categoryId: UpdateAdminBusiness200CategoryId
  /** Whether business is verified */
  verified?: boolean
  /** Whether business is active */
  active?: boolean
  /** Whether business is approved by admin */
  approved?: boolean
  /** Admin who approved the business */
  approvedBy?: UpdateAdminBusiness200ApprovedBy
  /** When the business was approved */
  approvedAt?: UpdateAdminBusiness200ApprovedAt
  /**
   * Average rating of the business
   * @minimum 0
   * @maximum 5
   */
  avgRating?: number
  /** URL of the business logo */
  logoUrl?: UpdateAdminBusiness200LogoUrl
  /** Soft deletion timestamp */
  deletedAt: UpdateAdminBusiness200DeletedAt
  /** Business owner details when ?include=user */
  user?: UpdateAdminBusiness200User
  /** Category information when ?include=category */
  category?: UpdateAdminBusiness200Category
  /** Business registration info when ?include=businessRegistration */
  businessRegistration?: UpdateAdminBusiness200BusinessRegistration
  /** When the record was created */
  createdAt: string
  /** When the record was last updated */
  updatedAt: string
}
