/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Pika Complete API
 * Complete API documentation including public, admin, and internal endpoints
 * OpenAPI spec version: 1.0.0
 */
import type { UpdateAdminFile200FileType } from './updateAdminFile200FileType'
import type { UpdateAdminFile200Status } from './updateAdminFile200Status'
import type { UpdateAdminFile200Provider } from './updateAdminFile200Provider'
import type { UpdateAdminFile200Metadata } from './updateAdminFile200Metadata'

export type UpdateAdminFile200 = {
  /** Universally Unique Identifier */
  id: string
  userId: string
  userName?: string
  userEmail?: string
  fileKey: string
  fileName: string
  /** */
  fileSize: number
  mimeType: string
  /** File type category */
  fileType: UpdateAdminFile200FileType
  /** File processing status */
  status: UpdateAdminFile200Status
  /** Supported storage provider */
  provider: UpdateAdminFile200Provider
  bucketName?: string
  region?: string
  /** ISO 8601 datetime with timezone */
  uploadedAt?: string
  /** ISO 8601 datetime with timezone */
  deletedAt?: string
  metadata?: UpdateAdminFile200Metadata
  error?: string
  isPublic?: boolean
  /** @minimum 0 */
  downloadCount?: number
  /** ISO 8601 datetime with timezone */
  lastAccessedAt?: string
  /** When the record was created */
  createdAt: string
  /** When the record was last updated */
  updatedAt: string
}
