/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Pika Complete API
 * Complete API documentation including public, admin, and internal endpoints
 * OpenAPI spec version: 1.0.0
 */

export type UpdateUserSettingsBodyDisplayTheme =
  (typeof UpdateUserSettingsBodyDisplayTheme)[keyof typeof UpdateUserSettingsBodyDisplayTheme]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UpdateUserSettingsBodyDisplayTheme = {
  light: 'light',
  dark: 'dark',
  system: 'system',
} as const
