/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Pika Complete API
 * Complete API documentation including public, admin, and internal endpoints
 * OpenAPI spec version: 1.0.0
 */

/**
 * Support ticket status
 */
export type UpdateAdminProblem200Status =
  (typeof UpdateAdminProblem200Status)[keyof typeof UpdateAdminProblem200Status]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UpdateAdminProblem200Status = {
  open: 'open',
  assigned: 'assigned',
  in_progress: 'in_progress',
  waiting_customer: 'waiting_customer',
  waiting_internal: 'waiting_internal',
  resolved: 'resolved',
  closed: 'closed',
} as const
