/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * The VoucherBook Complete API
 * Complete API documentation including public, admin, and internal endpoints
 * OpenAPI spec version: 1.0.0
 */
import type { UpdateInternalUserMembershipBodyStatus } from './updateInternalUserMembershipBodyStatus'
import type { UpdateInternalUserMembershipBodyMetadata } from './updateInternalUserMembershipBodyMetadata'

/**
 * Update subscription from payment service
 */
export type UpdateInternalUserMembershipBody = {
  stripeSubscriptionId: string
  /** Subscription status */
  status: UpdateInternalUserMembershipBodyStatus
  /** ISO 8601 datetime with timezone */
  currentPeriodStart?: string
  /** ISO 8601 datetime with timezone */
  currentPeriodEnd?: string
  /** ISO 8601 datetime with timezone */
  canceledAt?: string
  cancelAtPeriodEnd?: boolean
  metadata?: UpdateInternalUserMembershipBodyMetadata
}
