/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * The VoucherBook Complete API
 * Complete API documentation including public, admin, and internal endpoints
 * OpenAPI spec version: 1.0.0
 */

/**
 * User role in the system
 */
export type UpdateAdminBusiness200UserRole =
  (typeof UpdateAdminBusiness200UserRole)[keyof typeof UpdateAdminBusiness200UserRole]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UpdateAdminBusiness200UserRole = {
  admin: 'admin',
  customer: 'customer',
  business: 'business',
} as const
