/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * The VoucherBook Complete API
 * Complete API documentation including public, admin, and internal endpoints
 * OpenAPI spec version: 1.0.0
 */
import type { UpdateUserSettingsRequestBusinessDashboard } from './updateUserSettingsRequestBusinessDashboard'
import type { UpdateUserSettingsRequestBusinessVouchers } from './updateUserSettingsRequestBusinessVouchers'
import type { UpdateUserSettingsRequestBusinessNotifications } from './updateUserSettingsRequestBusinessNotifications'

export type UpdateUserSettingsRequestBusiness = {
  dashboard: UpdateUserSettingsRequestBusinessDashboard
  vouchers: UpdateUserSettingsRequestBusinessVouchers
  notifications: UpdateUserSettingsRequestBusinessNotifications
}
