/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Pika Complete API
 * Complete API documentation including public, admin, and internal endpoints
 * OpenAPI spec version: 1.0.0
 */
import type { UpdateAdminFileBodyStatus } from './updateAdminFileBodyStatus'
import type { UpdateAdminFileBodyMetadata } from './updateAdminFileBodyMetadata'

/**
 * Admin update file details
 */
export type UpdateAdminFileBody = {
  fileName?: string
  /** File processing status */
  status?: UpdateAdminFileBodyStatus
  isPublic?: boolean
  metadata?: UpdateAdminFileBodyMetadata
}
