/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Pika Complete API
 * Complete API documentation including public, admin, and internal endpoints
 * OpenAPI spec version: 1.0.0
 */

/**
 * Support ticket status
 */
export type UpdateAdminProblem200Status =
  (typeof UpdateAdminProblem200Status)[keyof typeof UpdateAdminProblem200Status]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UpdateAdminProblem200Status = {
  open: 'open',
  assigned: 'assigned',
  inProgress: 'inProgress',
  waitingCustomer: 'waitingCustomer',
  waitingInternal: 'waitingInternal',
  resolved: 'resolved',
  closed: 'closed',
} as const
