/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * The VoucherBook Complete API
 * Complete API documentation including public, admin, and internal endpoints
 * OpenAPI spec version: 1.0.0
 */
import type { UpdateBusinessDetailsRequestOperatingHours } from './updateBusinessDetailsRequestOperatingHours'
import type { UpdateBusinessDetailsRequestSocialMedia } from './updateBusinessDetailsRequestSocialMedia'
import type { UpdateBusinessDetailsRequestAdditionalInfo } from './updateBusinessDetailsRequestAdditionalInfo'

export interface UpdateBusinessDetailsRequest {
  /** @maxLength 20 */
  phone?: string
  /** @maxLength 255 */
  email?: string
  /** @maxLength 255 */
  website?: string
  /** @maxLength 512 */
  logoUrl?: string
  /** @maxLength 255 */
  street?: string
  /** @maxLength 100 */
  city?: string
  /** @maxLength 100 */
  state?: string
  /** @maxLength 20 */
  postalCode?: string
  /**
   * @minLength 2
   * @maxLength 2
   */
  country?: string
  operatingHours?: UpdateBusinessDetailsRequestOperatingHours
  socialMedia?: UpdateBusinessDetailsRequestSocialMedia
  additionalInfo?: UpdateBusinessDetailsRequestAdditionalInfo
}
