/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * The VoucherBook Complete API
 * Complete API documentation including public, admin, and internal endpoints
 * OpenAPI spec version: 1.0.0
 */
import type { UpdateUserSettingsBodyVersion } from './updateUserSettingsBodyVersion'
import type { UpdateUserSettingsBodyDisplay } from './updateUserSettingsBodyDisplay'
import type { UpdateUserSettingsBodyNotifications } from './updateUserSettingsBodyNotifications'
import type { UpdateUserSettingsBodyPrivacy } from './updateUserSettingsBodyPrivacy'
import type { UpdateUserSettingsBodyBusiness } from './updateUserSettingsBodyBusiness'
import type { UpdateUserSettingsBodyAccessibility } from './updateUserSettingsBodyAccessibility'
import type { UpdateUserSettingsBodyUpdatedAt } from './updateUserSettingsBodyUpdatedAt'

/**
 * Complete user settings object (replaces existing settings)
 */
export type UpdateUserSettingsBody = {
  version: UpdateUserSettingsBodyVersion
  display: UpdateUserSettingsBodyDisplay
  notifications: UpdateUserSettingsBodyNotifications
  privacy: UpdateUserSettingsBodyPrivacy
  business?: UpdateUserSettingsBodyBusiness
  accessibility: UpdateUserSettingsBodyAccessibility
  updatedAt: UpdateUserSettingsBodyUpdatedAt
}
