/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Pika Complete API
 * Complete API documentation including public, admin, and internal endpoints
 * OpenAPI spec version: 1.0.0
 */
import type { VoucherState } from './voucherState'
import type { VoucherDiscountType } from './voucherDiscountType'
import type { UpdateAdminVoucherState200Location } from './updateAdminVoucherState200Location'
import type { UpdateAdminVoucherState200ImageUrl } from './updateAdminVoucherState200ImageUrl'
import type { UpdateAdminVoucherState200MaxRedemptions } from './updateAdminVoucherState200MaxRedemptions'
import type { UpdateAdminVoucherState200Metadata } from './updateAdminVoucherState200Metadata'
import type { UpdateAdminVoucherState200DeletedAt } from './updateAdminVoucherState200DeletedAt'
import type { UpdateAdminVoucherState200Business } from './updateAdminVoucherState200Business'
import type { UpdateAdminVoucherState200Category } from './updateAdminVoucherState200Category'
import type { UpdateAdminVoucherState200CodesItem } from './updateAdminVoucherState200CodesItem'
import type { UpdateAdminVoucherState200RedemptionsItem } from './updateAdminVoucherState200RedemptionsItem'
import type { UpdateAdminVoucherState200ScansItem } from './updateAdminVoucherState200ScansItem'
import type { UpdateAdminVoucherState200CustomerVouchersItem } from './updateAdminVoucherState200CustomerVouchersItem'
import type { UpdateAdminVoucherState200DaysUntilExpiry } from './updateAdminVoucherState200DaysUntilExpiry'

export type UpdateAdminVoucherState200 = {
  /** Universally Unique Identifier */
  id: string
  /** Universally Unique Identifier */
  businessId: string
  /** Universally Unique Identifier */
  categoryId?: string
  state: VoucherState
  /** Voucher title in requested language */
  title: string
  /** Voucher description in requested language */
  description: string
  /** Voucher terms and conditions in requested language */
  terms: string
  discountType: VoucherDiscountType
  /** Decimal number with 2 decimal places */
  discountValue: number
  currency?: string
  location: UpdateAdminVoucherState200Location
  imageUrl: UpdateAdminVoucherState200ImageUrl
  /** ISO 8601 datetime with timezone */
  validFrom: string
  /** ISO 8601 datetime with timezone */
  expiresAt: string
  maxRedemptions: UpdateAdminVoucherState200MaxRedemptions
  maxRedemptionsPerUser?: number
  currentRedemptions?: number
  scanCount?: number
  claimCount?: number
  metadata: UpdateAdminVoucherState200Metadata
  /** ISO 8601 datetime with timezone */
  deletedAt: UpdateAdminVoucherState200DeletedAt
  /** Complete business object when ?include=business */
  business?: UpdateAdminVoucherState200Business
  /** Complete category object when ?include=category */
  category?: UpdateAdminVoucherState200Category
  /** Voucher codes when ?include=codes */
  codes?: UpdateAdminVoucherState200CodesItem[]
  /** Redemption history when ?include=redemptions */
  redemptions?: UpdateAdminVoucherState200RedemptionsItem[]
  /** Scan analytics when ?include=scans */
  scans?: UpdateAdminVoucherState200ScansItem[]
  /** Customer wallet entries when ?include=customerVouchers */
  customerVouchers?: UpdateAdminVoucherState200CustomerVouchersItem[]
  isActive: boolean
  isExpired: boolean
  /**
   * @minimum 0
   * @maximum 1
   */
  redemptionRate: number
  daysUntilExpiry: UpdateAdminVoucherState200DaysUntilExpiry
  /** When the record was created */
  createdAt: string
  /** When the record was last updated */
  updatedAt: string
}
