/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Pika Complete API
 * Complete API documentation including public, admin, and internal endpoints
 * OpenAPI spec version: 1.0.0
 */
import type { UpdateAdminStorageConfigurationBodyProvider } from './updateAdminStorageConfigurationBodyProvider'
import type { UpdateAdminStorageConfigurationBodyConfig } from './updateAdminStorageConfigurationBodyConfig'
import type { UpdateAdminStorageConfigurationBodyGlobalSettings } from './updateAdminStorageConfigurationBodyGlobalSettings'

export type UpdateAdminStorageConfigurationBody = {
  /** Supported storage provider */
  provider: UpdateAdminStorageConfigurationBodyProvider
  config?: UpdateAdminStorageConfigurationBodyConfig
  globalSettings?: UpdateAdminStorageConfigurationBodyGlobalSettings
}
