/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * The VoucherBook Complete API
 * Complete API documentation including public, admin, and internal endpoints
 * OpenAPI spec version: 1.0.0
 */
import type { UpdateAdminCurrentUser401DetailsItem } from './updateAdminCurrentUser401DetailsItem'

export type UpdateAdminCurrentUser401 = {
  /**
   * @minimum 100
   * @maximum 599
   */
  statusCode: number
  error: string
  message: string
  details?: UpdateAdminCurrentUser401DetailsItem[]
  /** Request correlation ID */
  correlationId?: string
  /** ISO 8601 datetime with timezone */
  timestamp?: string
}
