/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * The VoucherBook Complete API
 * Complete API documentation including public, admin, and internal endpoints
 * OpenAPI spec version: 1.0.0
 */
import type { UpdateAdminVoucherBodyTitle } from './updateAdminVoucherBodyTitle'
import type { UpdateAdminVoucherBodyDescription } from './updateAdminVoucherBodyDescription'
import type { UpdateAdminVoucherBodyTermsAndConditions } from './updateAdminVoucherBodyTermsAndConditions'
import type { VoucherDiscountType } from './voucherDiscountType'
import type { UpdateAdminVoucherBodyLocation } from './updateAdminVoucherBodyLocation'
import type { UpdateAdminVoucherBodyImageUrl } from './updateAdminVoucherBodyImageUrl'
import type { UpdateAdminVoucherBodyMaxRedemptions } from './updateAdminVoucherBodyMaxRedemptions'
import type { UpdateAdminVoucherBodyMetadata } from './updateAdminVoucherBodyMetadata'

export type UpdateAdminVoucherBody = {
  /** Universally Unique Identifier */
  categoryId?: string
  /** Title translations by language code */
  title?: UpdateAdminVoucherBodyTitle
  /** Description translations by language code */
  description?: UpdateAdminVoucherBodyDescription
  /** Terms and conditions translations by language code */
  termsAndConditions?: UpdateAdminVoucherBodyTermsAndConditions
  discountType?: VoucherDiscountType
  /** */
  discountValue?: number
  currency?: string
  location?: UpdateAdminVoucherBodyLocation
  imageUrl?: UpdateAdminVoucherBodyImageUrl
  /** ISO 8601 datetime with timezone */
  validFrom?: string
  /** ISO 8601 datetime with timezone */
  expiresAt?: string
  /** */
  maxRedemptions?: UpdateAdminVoucherBodyMaxRedemptions
  /** */
  maxRedemptionsPerUser?: number
  metadata?: UpdateAdminVoucherBodyMetadata
}
