/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Pika Complete API
 * Complete API documentation including public, admin, and internal endpoints
 * OpenAPI spec version: 1.0.0
 */

export interface UpdateMyBusinessRequest {
  /**
   * Business name
   * @minLength 1
   * @maxLength 100
   */
  businessName?: string
  /**
   * Business description
   * @maxLength 500
   */
  businessDescription?: string
  /** Category ID */
  categoryId?: string
}
