/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Pika Complete API
 * Complete API documentation including public, admin, and internal endpoints
 * OpenAPI spec version: 1.0.0
 */
import type { UploadAdminBusinessLogo404DetailsItem } from './uploadAdminBusinessLogo404DetailsItem'

export type UploadAdminBusinessLogo404 = {
  /**
   * @minimum 100
   * @maximum 599
   */
  statusCode: number
  error: string
  message: string
  details?: UploadAdminBusinessLogo404DetailsItem[]
  /** Request correlation ID */
  correlationId?: string
  /** ISO 8601 datetime with timezone */
  timestamp?: string
}
