/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * The VoucherBook Complete API
 * Complete API documentation including public, admin, and internal endpoints
 * OpenAPI spec version: 1.0.0
 */
import type { UserPaymentMethodsResponsePaymentMethodsItemWalletType } from './userPaymentMethodsResponsePaymentMethodsItemWalletType'

export type UserPaymentMethodsResponsePaymentMethodsItemWallet = {
  type: UserPaymentMethodsResponsePaymentMethodsItemWalletType
  /**
   * @minLength 4
   * @maxLength 4
   */
  dynamicLast4?: string
}
