/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Pika Complete API
 * Complete API documentation including public, admin, and internal endpoints
 * OpenAPI spec version: 1.0.0
 */

/**
 * User subscription status
 */
export interface UserSubscriptionStatusResponse {
  userId: string
  hasActiveSubscription: boolean
  subscriptionType?: string
  /** ISO 8601 datetime with timezone */
  expiresAt?: string
  /** @minimum 0 */
  creditsRemaining: number
  canBookSessions: boolean
}
