/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * The VoucherBook Complete API
 * Complete API documentation including public, admin, and internal endpoints
 * OpenAPI spec version: 1.0.0
 */
import type { UserInfoResponseRole } from './userInfoResponseRole'

export interface UserInfoResponse {
  /** User ID */
  id: string
  /** @minLength 1 */
  email: string
  emailVerified?: boolean
  firstName: string
  lastName: string
  /** Combined first and last name */
  fullName?: string
  profilePicture?: string
  /** User role in the system */
  role: UserInfoResponseRole
  /** User permissions */
  permissions?: string[]
  /** User locale */
  locale?: string
  createdAt?: string
  updatedAt?: string
}
