/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Pika Complete API
 * Complete API documentation including public, admin, and internal endpoints
 * OpenAPI spec version: 1.0.0
 */
import type { UserAuthDataRole } from './userAuthDataRole'
import type { UserAuthDataStatus } from './userAuthDataStatus'

/**
 * User data for authentication
 */
export interface UserAuthData {
  id: string
  /** @minLength 1 */
  email: string
  password?: string
  firstName: string
  lastName: string
  phoneNumber?: string
  /** User role in the system */
  role: UserAuthDataRole
  /** User account status */
  status: UserAuthDataStatus
  emailVerified: boolean
  /** ISO 8601 datetime with timezone */
  createdAt: string
  /** ISO 8601 datetime with timezone */
  lastLoginAt?: string
}
