/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * The VoucherBook Complete API
 * Complete API documentation including public, admin, and internal endpoints
 * OpenAPI spec version: 1.0.0
 */
import type { UserSettingsPrivacyProfile } from './userSettingsPrivacyProfile'
import type { UserSettingsPrivacySearch } from './userSettingsPrivacySearch'
import type { UserSettingsPrivacyAnalytics } from './userSettingsPrivacyAnalytics'
import type { UserSettingsPrivacyMarketing } from './userSettingsPrivacyMarketing'

export type UserSettingsPrivacy = {
  profile: UserSettingsPrivacyProfile
  search: UserSettingsPrivacySearch
  analytics: UserSettingsPrivacyAnalytics
  marketing: UserSettingsPrivacyMarketing
}
