/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Pika Complete API
 * Complete API documentation including public, admin, and internal endpoints
 * OpenAPI spec version: 1.0.0
 */
import type { UserVouchersListResponseDataItemVoucher } from './userVouchersListResponseDataItemVoucher'
import type { CustomerVoucherStatus } from './customerVoucherStatus'
import type { UserVouchersListResponseDataItemRedeemedAt } from './userVouchersListResponseDataItemRedeemedAt'

export type UserVouchersListResponseDataItem = {
  voucher: UserVouchersListResponseDataItemVoucher
  claimedAt: string
  status: CustomerVoucherStatus
  redeemedAt?: UserVouchersListResponseDataItemRedeemedAt
}
