/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Pika Complete API
 * Complete API documentation including public, admin, and internal endpoints
 * OpenAPI spec version: 1.0.0
 */
import type { UserSettingsNotificationsEmail } from './userSettingsNotificationsEmail'
import type { UserSettingsNotificationsPush } from './userSettingsNotificationsPush'
import type { UserSettingsNotificationsSms } from './userSettingsNotificationsSms'
import type { UserSettingsNotificationsInApp } from './userSettingsNotificationsInApp'

export type UserSettingsNotifications = {
  email: UserSettingsNotificationsEmail
  push: UserSettingsNotificationsPush
  sms: UserSettingsNotificationsSms
  inApp: UserSettingsNotificationsInApp
}
