/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * The VoucherBook Complete API
 * Complete API documentation including public, admin, and internal endpoints
 * OpenAPI spec version: 1.0.0
 */
import type { UserProfileResponseRole } from './userProfileResponseRole'
import type { UserProfileResponseStatus } from './userProfileResponseStatus'

/**
 * Authenticated user's complete profile
 */
export interface UserProfileResponse {
  id: string
  /** @minLength 1 */
  email: string
  /** @maxLength 50 */
  firstName: string
  /** @maxLength 50 */
  lastName: string
  /** Computed full name (firstName + lastName) */
  name: string
  /**
   * Phone number in E.164 format
   * @pattern ^\+[1-9]\d{1,14}$
   */
  phoneNumber?: string
  avatarUrl?: string
  /**
   * Date in YYYY-MM-DD format
   * @pattern ^\d{4}-\d{2}-\d{2}$
   */
  dateOfBirth?: string
  /**
   * @minLength 2
   * @maxLength 2
   * @pattern ^[a-z]{2}$
   */
  preferredLanguage?: string
  /** User role in the system */
  role: UserProfileResponseRole
  /** User account status */
  status: UserProfileResponseStatus
  emailVerified: boolean
  phoneVerified?: boolean
  /** Primary business for business users */
  primaryBusinessId?: string
  /** ISO 8601 datetime with timezone */
  createdAt: string
  /** ISO 8601 datetime with timezone */
  updatedAt: string
  /** ISO 8601 datetime with timezone */
  lastLoginAt?: string
}
