/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Pika Complete API
 * Complete API documentation including public, admin, and internal endpoints
 * OpenAPI spec version: 1.0.0
 */
import type { UserFileSummaryResponseFilesByType } from './userFileSummaryResponseFilesByType'
import type { UserFileSummaryResponseFilesByStatus } from './userFileSummaryResponseFilesByStatus'

/**
 * User file summary for internal use
 */
export interface UserFileSummaryResponse {
  userId: string
  /** @minimum 0 */
  totalFiles: number
  /**
   * Total size in bytes
   * @minimum 0
   */
  totalSize: number
  filesByType: UserFileSummaryResponseFilesByType
  filesByStatus: UserFileSummaryResponseFilesByStatus
  /** ISO 8601 datetime with timezone */
  oldestFile?: string
  /** ISO 8601 datetime with timezone */
  newestFile?: string
}
