/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * The VoucherBook Complete API
 * Complete API documentation including public, admin, and internal endpoints
 * OpenAPI spec version: 1.0.0
 */

export type UserCommunicationPreferencesResponsePushTokensItemPlatform =
  (typeof UserCommunicationPreferencesResponsePushTokensItemPlatform)[keyof typeof UserCommunicationPreferencesResponsePushTokensItemPlatform]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UserCommunicationPreferencesResponsePushTokensItemPlatform = {
  ios: 'ios',
  android: 'android',
  web: 'web',
  desktop: 'desktop',
  other: 'other',
} as const
