/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Pika Complete API
 * Complete API documentation including public, admin, and internal endpoints
 * OpenAPI spec version: 1.0.0
 */
import type { UserPaymentMethodsResponsePaymentMethodsItem } from './userPaymentMethodsResponsePaymentMethodsItem'

export interface UserPaymentMethodsResponse {
  paymentMethods: UserPaymentMethodsResponsePaymentMethodsItem[]
  /** Universally Unique Identifier */
  defaultPaymentMethodId?: string
  hasValidPaymentMethod: boolean
}
