/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * The VoucherBook Complete API
 * Complete API documentation including public, admin, and internal endpoints
 * OpenAPI spec version: 1.0.0
 */

export type ValidateVoucherResponseVoucherLocationAnyOfType =
  (typeof ValidateVoucherResponseVoucherLocationAnyOfType)[keyof typeof ValidateVoucherResponseVoucherLocationAnyOfType]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ValidateVoucherResponseVoucherLocationAnyOfType = {
  Point: 'Point',
} as const
