/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * The VoucherBook Complete API
 * Complete API documentation including public, admin, and internal endpoints
 * OpenAPI spec version: 1.0.0
 */
import type { CustomerVoucherStatus } from './customerVoucherStatus'
import type { ValidateVoucherResponseVoucherCustomerVouchersItemNotificationPreferences } from './validateVoucherResponseVoucherCustomerVouchersItemNotificationPreferences'
import type { ValidateVoucherResponseVoucherCustomerVouchersItemRedeemedAt } from './validateVoucherResponseVoucherCustomerVouchersItemRedeemedAt'

export type ValidateVoucherResponseVoucherCustomerVouchersItem = {
  /** Universally Unique Identifier */
  id: string
  /** Universally Unique Identifier */
  customerId: string
  /** ISO 8601 datetime with timezone */
  claimedAt: string
  status: CustomerVoucherStatus
  notificationPreferences: ValidateVoucherResponseVoucherCustomerVouchersItemNotificationPreferences
  /** ISO 8601 datetime with timezone */
  redeemedAt: ValidateVoucherResponseVoucherCustomerVouchersItemRedeemedAt
  /** ISO 8601 datetime with timezone */
  createdAt: string
  /** ISO 8601 datetime with timezone */
  updatedAt: string
}
