/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Pika Complete API
 * Complete API documentation including public, admin, and internal endpoints
 * OpenAPI spec version: 1.0.0
 */

/**
 * Source of the voucher scan
 */
export type ValidateVoucherResponseVoucherScansItemScanSource =
  (typeof ValidateVoucherResponseVoucherScansItemScanSource)[keyof typeof ValidateVoucherResponseVoucherScansItemScanSource]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ValidateVoucherResponseVoucherScansItemScanSource = {
  camera: 'camera',
  gallery: 'gallery',
  link: 'link',
  share: 'share',
} as const
