/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * The VoucherBook Complete API
 * Complete API documentation including public, admin, and internal endpoints
 * OpenAPI spec version: 1.0.0
 */
import type { ValidateVoucherResponseVoucher } from './validateVoucherResponseVoucher'

/**
 * Voucher validation result
 */
export interface ValidateVoucherResponse {
  isValid: boolean
  /** Reason if validation failed */
  reason?: string
  /** Voucher details if valid */
  voucher?: ValidateVoucherResponseVoucher
}
