/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * The VoucherBook Complete API
 * Complete API documentation including public, admin, and internal endpoints
 * OpenAPI spec version: 1.0.0
 */

export type ValidateInternalVoucher200VoucherScansItemLocationAnyOfType =
  (typeof ValidateInternalVoucher200VoucherScansItemLocationAnyOfType)[keyof typeof ValidateInternalVoucher200VoucherScansItemLocationAnyOfType]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ValidateInternalVoucher200VoucherScansItemLocationAnyOfType = {
  Point: 'Point',
} as const
