/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Pika Complete API
 * Complete API documentation including public, admin, and internal endpoints
 * OpenAPI spec version: 1.0.0
 */
import type { ValidateInternalVoucher200VoucherCustomerVouchersItemNotificationPreferencesAnyOf } from './validateInternalVoucher200VoucherCustomerVouchersItemNotificationPreferencesAnyOf'

export type ValidateInternalVoucher200VoucherCustomerVouchersItemNotificationPreferences =
  ValidateInternalVoucher200VoucherCustomerVouchersItemNotificationPreferencesAnyOf | null
