/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Pika Complete API
 * Complete API documentation including public, admin, and internal endpoints
 * OpenAPI spec version: 1.0.0
 */

export type VerifyAdminUserBodyType =
  (typeof VerifyAdminUserBodyType)[keyof typeof VerifyAdminUserBodyType]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const VerifyAdminUserBodyType = {
  EMAIL: 'EMAIL',
  PHONE: 'PHONE',
  ACCOUNT_CONFIRMATION: 'ACCOUNT_CONFIRMATION',
} as const
