/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Pika Complete API
 * Complete API documentation including public, admin, and internal endpoints
 * OpenAPI spec version: 1.0.0
 */

export type VerifyUserRequestVerificationType =
  (typeof VerifyUserRequestVerificationType)[keyof typeof VerifyUserRequestVerificationType]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const VerifyUserRequestVerificationType = {
  email: 'email',
  phone: 'phone',
  accountConfirmation: 'accountConfirmation',
} as const
