/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Pika Complete API
 * Complete API documentation including public, admin, and internal endpoints
 * OpenAPI spec version: 1.0.0
 */
import type { VerifyAdminUserBodyType } from './verifyAdminUserBodyType'

export type VerifyAdminUserBody = {
  type: VerifyAdminUserBodyType
  token?: string
  /**
   * @minLength 6
   * @maxLength 6
   */
  code?: string
  userId?: string
  email?: string
  phoneNumber?: string
}
