/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Pika Complete API
 * Complete API documentation including public, admin, and internal endpoints
 * OpenAPI spec version: 1.0.0
 */

/**
 * Email verification token
 */
export interface VerifyEmailRequest {
  /**
   * Email verification token from email link
   * @minLength 1
   */
  token: string
}
