/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Pika Complete API
 * Complete API documentation including public, admin, and internal endpoints
 * OpenAPI spec version: 1.0.0
 */

/**
 * Analytics grouping period
 */
export type VoucherAnalyticsQueryParamsGroupBy =
  (typeof VoucherAnalyticsQueryParamsGroupBy)[keyof typeof VoucherAnalyticsQueryParamsGroupBy]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const VoucherAnalyticsQueryParamsGroupBy = {
  day: 'day',
  week: 'week',
  month: 'month',
} as const
