/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Pika Complete API
 * Complete API documentation including public, admin, and internal endpoints
 * OpenAPI spec version: 1.0.0
 */

/**
 * Field to sort vouchers by
 */
export type VoucherQueryParamsSortBy =
  (typeof VoucherQueryParamsSortBy)[keyof typeof VoucherQueryParamsSortBy]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const VoucherQueryParamsSortBy = {
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  expiresAt: 'expiresAt',
  discountValue: 'discountValue',
  title: 'title',
} as const
