/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Pika Complete API
 * Complete API documentation including public, admin, and internal endpoints
 * OpenAPI spec version: 1.0.0
 */
import type { VoucherScanSource } from './voucherScanSource'
import type { Coordinates } from './coordinates'
import type { DeviceInfo } from './deviceInfo'

/**
 * Request to track voucher scan
 */
export interface VoucherScanRequest {
  scanSource?: VoucherScanSource
  location?: Coordinates
  deviceInfo?: DeviceInfo
}
