/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * The VoucherBook Complete API
 * Complete API documentation including public, admin, and internal endpoints
 * OpenAPI spec version: 1.0.0
 */

export type VoucherScanRequestScanSource =
  (typeof VoucherScanRequestScanSource)[keyof typeof VoucherScanRequestScanSource]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const VoucherScanRequestScanSource = {
  camera: 'camera',
  gallery: 'gallery',
  link: 'link',
  share: 'share',
  qr: 'qr',
  print: 'print',
  digital: 'digital',
  web: 'web',
  email: 'email',
  social: 'social',
} as const
