/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Pika Complete API
 * Complete API documentation including public, admin, and internal endpoints
 * OpenAPI spec version: 1.0.0
 */

/**
 * Type of voucher book
 */
export type VoucherBookType =
  (typeof VoucherBookType)[keyof typeof VoucherBookType]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const VoucherBookType = {
  monthly: 'monthly',
  specialEdition: 'specialEdition',
  regional: 'regional',
  seasonal: 'seasonal',
  promotional: 'promotional',
} as const
