/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Pika Complete API
 * Complete API documentation including public, admin, and internal endpoints
 * OpenAPI spec version: 1.0.0
 */

/**
 * Only published books visible to public
 */
export type VoucherBookDetailResponseDataStatus =
  (typeof VoucherBookDetailResponseDataStatus)[keyof typeof VoucherBookDetailResponseDataStatus]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const VoucherBookDetailResponseDataStatus = {
  published: 'published',
} as const
