/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Pika Complete API
 * Complete API documentation including public, admin, and internal endpoints
 * OpenAPI spec version: 1.0.0
 */
import type { VoucherCodeType } from './voucherCodeType'
import type { VoucherCodeResponseMetadata } from './voucherCodeResponseMetadata'

/**
 * Voucher code information
 */
export interface VoucherCodeResponse {
  /** Universally Unique Identifier */
  id: string
  code: string
  type: VoucherCodeType
  isActive: boolean
  metadata?: VoucherCodeResponseMetadata
}
