/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * The VoucherBook Complete API
 * Complete API documentation including public, admin, and internal endpoints
 * OpenAPI spec version: 1.0.0
 */
import type { VoucherState } from './voucherState'
import type { VoucherDiscountType } from './voucherDiscountType'
import type { VoucherScanResponseVoucherImageUrl } from './voucherScanResponseVoucherImageUrl'
import type { VoucherScanResponseVoucherMaxRedemptions } from './voucherScanResponseVoucherMaxRedemptions'
import type { VoucherScanResponseVoucherMetadata } from './voucherScanResponseVoucherMetadata'
import type { VoucherScanResponseVoucherCodesItem } from './voucherScanResponseVoucherCodesItem'

export type VoucherScanResponseVoucher = {
  /** Universally Unique Identifier */
  id: string
  /** Universally Unique Identifier */
  businessId: string
  /** Universally Unique Identifier */
  categoryId?: string
  state: VoucherState
  /** Multilingual voucher title */
  title?: unknown
  /** Multilingual voucher description */
  description?: unknown
  /** Multilingual voucher terms */
  terms?: unknown
  discountType: VoucherDiscountType
  /** @minimum 0 */
  discountValue: number
  currency?: string
  /** GeoJSON Point or Polygon */
  location?: unknown
  imageUrl?: VoucherScanResponseVoucherImageUrl
  validFrom: string
  expiresAt: string
  /** @minimum 1 */
  maxRedemptions?: VoucherScanResponseVoucherMaxRedemptions
  /** @minimum 1 */
  maxRedemptionsPerUser?: number
  /** @minimum 0 */
  currentRedemptions?: number
  metadata?: VoucherScanResponseVoucherMetadata
  codes?: VoucherScanResponseVoucherCodesItem[]
  /** When the record was created */
  createdAt: string
  /** When the record was last updated */
  updatedAt: string
}
