/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Pika Complete API
 * Complete API documentation including public, admin, and internal endpoints
 * OpenAPI spec version: 1.0.0
 */
import type { VoucherScanRequestScanSource } from './voucherScanRequestScanSource'
import type { VoucherScanRequestLocation } from './voucherScanRequestLocation'
import type { VoucherScanRequestDeviceInfo } from './voucherScanRequestDeviceInfo'

/**
 * Request to track voucher scan
 */
export interface VoucherScanRequest {
  scanSource?: VoucherScanRequestScanSource
  location?: VoucherScanRequestLocation
  deviceInfo?: VoucherScanRequestDeviceInfo
}
