/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Pika Complete API
 * Complete API documentation including public, admin, and internal endpoints
 * OpenAPI spec version: 1.0.0
 */

/**
 * Type of discount the voucher provides
 */
export type VoucherListResponseDataItemDiscountType =
  (typeof VoucherListResponseDataItemDiscountType)[keyof typeof VoucherListResponseDataItemDiscountType]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const VoucherListResponseDataItemDiscountType = {
  fixed: 'fixed',
  percentage: 'percentage',
} as const
