/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Pika Complete API
 * Complete API documentation including public, admin, and internal endpoints
 * OpenAPI spec version: 1.0.0
 */

export type VoucherClaimRequestNotificationPreferences = {
  enableReminders?: boolean
  /**
   * @minimum 1
   * @maximum 30
   */
  reminderDaysBefore?: number
}
