/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Pika Complete API
 * Complete API documentation including public, admin, and internal endpoints
 * OpenAPI spec version: 1.0.0
 */
import type { VoucherScanResponseVoucher } from './voucherScanResponseVoucher'
import type { VoucherScanResponseNearbyLocationsItem } from './voucherScanResponseNearbyLocationsItem'

/**
 * Voucher scan tracking result
 */
export interface VoucherScanResponse {
  /** Public voucher information */
  voucher: VoucherScanResponseVoucher
  /** Universally Unique Identifier */
  scanId: string
  canClaim: boolean
  alreadyClaimed: boolean
  nearbyLocations?: VoucherScanResponseNearbyLocationsItem[]
}
